### ISSUE TITLE
Make Meetings composite available without requiring React

### ISSUE THREAD

**Issue by alkwa-msft** [Azure/communication-ui-library#1000]
**What feature are you requesting?**
^topic. Today we expose Chat composite and Calling composite. Perhaps in the future we should explore Meetings composite as well.

**What would be the benefit of adding this feature?**
Customers want to be able to use the Meetings composite but they are not necessarily using React.

**What solution would be ideal for you?**
A similar API to what we offer from a script tag for Calling/Chat composite.

**Comment by anjulgarg** [comment]
@alkwa-msft Can we close this issue now that we have the static html samples in place?

**Comment by alkwa-msft** [comment]
@anjulgarg sounds good to me.

**Comment by JamesBurnside** [comment]
Note: we do not have one yet for CallWithChatComposite
