### ISSUE TITLE
callInvitationURL Not working

### ISSUE THREAD

**Issue by pablo-meyer** [Azure/communication-ui-library#1009]
Not sure if this is a bug. But the callInvitationURL isnt working in the callComposite.  How is this supposed to work? I couldn't find any documentation.

**Comment by alkwa-msft** [comment]
The string you provide to this prop will get copied into the users clipboard when they click on this button when clicking on participants.

![image](https://user-images.githubusercontent.com/79329532/140092035-772c073a-a111-4680-9cde-47ee9648cfa9.png)

The scenario assumes that using this URL will allow other users to join the same call. So this is a great way to get the URL to share to a colleague.

**Comment by pablo-meyer** [comment]
@alkwa-msft  Understood.  However it doesn't seem to work.  I've setup a callInvitationURL and I don't get the "Copy Invite link" option under "participants"

Note: using the stand alone:

  <script src="https://github.com/Azure/communication-ui-library/releases/latest/download/callComposite.js"></script>

Side question.  Can I find documentation on this call composite script file?

**Comment by alkwa-msft** [comment]
For trying out the callInvitationUrl can you try using our story that lets you try using the composite in storybook?

https://azure.github.io/communication-ui-library/?path=/story/composites-call-basicexample--basic-example

**Comment by alkwa-msft** [comment]
We should definitely fix those. Thanks for sharing those details.
