### ISSUE TITLE
Missing some translation in French

### ISSUE THREAD

**Issue by rceraline** [Azure/communication-ui-library#1041]
I use callComposite in a non react environment. In order to translate the component in French, I followed the documentation [Build your own composite js bundle files](https://azure.github.io/communication-ui-library/?path=/docs/use-composite-in-non-react-environment--page#build-your-own-composite-js-bundle-files) and added the locale property.

The code looks like the following:
```
import { AzureCommunicationTokenCredential } from '@azure/communication-common';
import { CallComposite, COMPOSITE_LOCALE_FR_FR, createAzureCommunicationCallAdapter } from '@azure/communication-react';
import React from 'react';
import ReactDOM from 'react-dom';

export const loadCallComposite = async function (args, htmlElement, props) {
  const { userId, token, groupId, displayName } = args;
  const adapter = await createAzureCommunicationCallAdapter({
    userId,
    displayName: displayName ?? 'anonymous',
    credential: new AzureCommunicationTokenCredential(token),
    locator: { groupId }
  });

  props = {
    ...props,
    locale: COMPOSITE_LOCALE_FR_FR
  };

  ReactDOM.render(React.createElement(CallComposite, { ...props, adapter }, null), htmlElement);
  return adapter;
};
```

I was able to create the bundle successfully.

However, I noticed that some translations were missing. Is there a way to add those missing translations? See the pictures below.

Thanks,

![image](https://user-images.githubusercontent.com/3820705/140751890-7b17d1e2-37af-44dc-9b22-50ebe1541c55.png)
![image](https://user-images.githubusercontent.com/3820705/140751910-d4b2c49f-8079-4e53-b663-bcd23c43fe44.png)

**Comment by anjulgarg** [comment]
Hi @rceraline 
Thanks for bringing this to our attention.

We will be adding the missing translations to the package in our next beta release i.e., 1.0.0-beta.8
You should also be able to see the translated strings in our nightly alpha release in a couple of days once the following PR goes in https://github.com/Azure/communication-ui-library/pull/1047
