### ISSUE TITLE
Is there a way to be informed that the call is started?

### ISSUE THREAD

**Issue by rceraline** [Azure/communication-ui-library#1057]
Hi,

I am using callComposite without react. I can easily be informed when the call is ended with this event.
```
callAdapter.on('callEnded, (event) => {
  console.log(event.callId);
})
```
Is there something similar but when the call is started, after the user clicks on the button "start call"?

Thanks,
Rémi

**Comment by anjulgarg** [comment]
Hi @rceraline, that's a good question. There is no direct event that you can subscribe to for identifying if a call has started.
However, you can use the following code to achieve this.
```ts
adapter.onStateChange((state) => {
   console.log(state.call?.state === 'Connected');
});
```

@PorterNan Please correct me if I am missing something?

**Comment by rceraline** [comment]
Thanks @anjulgarg, that would do the job
