### ISSUE TITLE
messages not always retrieved in Chat (Non-React)

### ISSUE THREAD

**Issue by alcail** [Azure/communication-ui-library#1137]
**Describe the bug; what happened?**

Copy from IcM https://portal.microsofticm.com/imp/v3/incidents/details/273222048/home

**Issue:** 

The customer has implemented the JavaScript Chat SDK with UI Composites (Non-React)
The issue they're facing is that historical messages are not always being displayed when switching between users in an existing chat.  
Here below the link for reference the customer used to implement chat functionality.
https://azure.github.io/communication-ui-library/?path=/story/use-composite-in-non-react-environment--page
 
**Troubleshooting:**

During our call, we discovered that the historical chat messages always load on the initial click.
When you click again on the user's chat and toggle between participants, after the 2nd and consecutive clicks, the get messages API is not being called in the Network calls . 
I asked cx to reproduce the issue and save the network calls to a HAR file so that we can further investigate  (Please see attached Network Trace)
Attachments: 

Screenshot of missing chat messages (see eorrchatmsg.png in IcM)
Teams Meeting recording of customer reproducing issue- https://microsoft-my.sharepoint.com/:v:/p/jameelaesa/EbZS-qVTKxhHuVa9xUr2LFIBVQDVz2HDRli-oXSFxgZJgw?e=3jKUSD 
Network trace is attached (see chatapiCcontent20211119.har in IcM) - you will see towards the end in the network trace the messages API is not being called anymore so messages are not being retrieved.

**What are the steps to reproduce the issue?**

**What behavior did you expect?**

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
- Version [e.g. 1.8.0]

**Is there any additional information?**

**Comment by alcail** [comment]
created bug https://skype.visualstudio.com/SPOOL/_workitems/edit/2653046

**Comment by Jcodevisible** [comment]
Hi can we please get the workaround posted here for visibility?

**Comment by alcail** [comment]
Customers are reusing the Chat composite React component and when they close chat pane, the adapter is gone but chat composite isn't.
So the next time they use it the Chat composite won't call adapter.initial() because React think the chat composite is good to go.
Customers will need call adapter.initial() again.
We will add better documentation on this.

**Comment by alkwa-msft** [comment]
The work-around for this fix is to supply a react "key". We suggest using `new Date()` as this will always yield a fairly unique value.

![image](https://user-images.githubusercontent.com/79329532/154350178-9335e5e7-e0c9-4914-b7c4-2c43abdc151c.png)
