### ISSUE TITLE
The Control Bar Buttons do not render in a SharePoint Framework project

### ISSUE THREAD

**Issue by aakashbhardwaj619** [Azure/communication-ui-library#1301]
**Describe the bug; what happened?****
The Control Bar Buttons like **MicrophoneButton**, **ScreenShareButton**, and **SendBox** buttons do not render in a [SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview) 1.13.1** project. The project is using **Node 14.17.0** and **TypeScript v3.9** ([Reference](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.13#new-features-and-capabilities)).

**What are the steps to reproduce the issue?**
1. Create a new SharePoint Framework project ([Reference](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)).
2. Add the 1.0.0 version of **@azure/communication-react** library.
3. Use the MicrophoneButton and ScreenShareButton controls in a React component.
```typescript
<ControlBar layout={'horizontal'}>
    <MicrophoneButton checked={true} />
    <ScreenShareButton checked={true} />
</ControlBar>
```
4. Build and deploy the solution on a SharePoint site. The controls' icons do not render properly as shown in the below screenshots. There is no element inside the `<i></i>` tags.

**What behavior did you expect?**
The microphone and screen share icons should be visible.

**If applicable, provide screenshots:**
<img width="406" alt="ControlButtonError" src="https://user-images.githubusercontent.com/33526902/149275171-3c933327-5df7-407c-832c-709613d8b295.png">
![ControlButtonError2](https://user-images.githubusercontent.com/33526902/149275701-19818a53-f238-4762-996f-44a538f6aa58.png)

**In what environment did you see the issue?**

- OS & Device: Windows 11
- Browser: Microsoft Edge
- Version: 1.0.0

**Comment by JamesBurnside** [comment]
Hi @aakashbhardwaj619 to help you further I believe we'll need to be able to repro your scenario. Could you provide instructions for how to set up a framework site to repro this issue?
For example what parameters should we plug into the yo command:
![image](https://user-images.githubusercontent.com/2684369/149415634-380a835e-537e-4d6c-875c-3af0c4b2eb46.png)
And then how can we see the code running live?

@anjulgarg do you know if we need to call anything like `registerIcons()` when using raw components?

**Comment by aakashbhardwaj619** [comment]
Hi @JamesBurnside It's an SPFx Application Customizer extension. I've also uploaded my solution to [this repo](https://github.com/aakashbhardwaj619/spfx-acs-ui-extension) so you can clone it and follow the steps mentioned [here](https://github.com/aakashbhardwaj619/spfx-acs-ui-extension#minimal-path-to-awesome) to reproduce the issue.

**Comment by aakashbhardwaj619** [comment]
Hi, @mgamis-msft! Sorry for the late response as I was occupied with a couple of high-priority tasks. I tried to add the code change but it is giving the below build error. Do I need to add some imports or any other packages?
![ACSIconError](https://user-images.githubusercontent.com/33526902/152985071-e4a97449-75ab-44a6-8467-1e9e4bc857c7.png)

I had copied the files from my original solution into this sample solution so there are some unnecessary imports of hooks and FluentThemeProvider. But I will be using these in my actual solution.

**Comment by anjulgarg** [comment]
Hi @aakashbhardwaj619 You will need to import `DEFAULT_COMPONENT_ICONS` from `@azure/communication-react`

**Comment by aakashbhardwaj619** [comment]
Thanks, @anjulgarg! The Control Bar icons work now after adding the below lines:

```typescript
import { DEFAULT_COMPONENT_ICONS } from '@azure/communication-react';
import { registerIcons } from '@uifabric/styling';
registerIcons({ icons: DEFAULT_COMPONENT_ICONS });
```
