### ISSUE TITLE
Cannot exit storybook when in full screen

### ISSUE THREAD

**Issue by cherchyk** [Azure/communication-ui-library#1525]
on https://azure.github.io/communication-ui-library/?path=/docs/overview--page
I pressed "go full screen"
and there is no way to get back of the "full screen"

Chrome Browser 32" screen

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
- Version [e.g. 1.8.0]

**Is there any additional information?**

**Comment by carocao-msft** [comment]
Ok I'm looking into this!

**Comment by carocao-msft** [comment]
Hi, I have merged a PR to enable keyboard shortcuts for the storybook. Now you can use keyboard shortcuts (F) to enter and exit full-screen mode :)

**Comment by JamesBurnside** [comment]
Adding on to this issue, the keyboard fix definitely helps but is undiscoverable for users who enter fullscreen via the UI interface. We either need to:
* Ensure a "close" UI button is shown when in fullscreen to go back to non-fullscreen (better)
* Remove the fullscreen functionality

Storybook by default does show a close button when in fullscreen:
![image](https://user-images.githubusercontent.com/2684369/156099357-1047322c-b512-42d5-8ef2-78c78a77bdfb.png)

Likely in our effort to reduce the amount of visual elements on the page we accidentally removed this -- we should add this back in.

**Comment by JamesBurnside** [comment]
Fix has now been deployed to https://aka.ms/acsstorybook as part of 1.1.1-beta.1 deployment. Closing this issue. Thanks @cherchyk for bringing this issue up!
