### ISSUE TITLE
Ref Docs CI fails on @azure/communication-react@1.0.1 

### ISSUE THREAD

**Issue by danieljurek** [Azure/communication-ui-library#1568]
Moving from https://github.com/Azure/azure-sdk-for-js/issues/20574

Docs are generated for version 1.0.0 until this is fixed. 

Example build: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=279861&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102

Error:

```
##[error][User Error]: Failed to install npm package @azure/communication-react with command: 
	npm install @azure/communication-react --prefix . 2>&1
```

Process: 

1. Fix the issue with docs CI
2. Remove the entry for `@azure/communication-react` from the `[Language-Settings.ps1](https://github.com/Azure/azure-sdk-for-js/blob/main/eng/scripts/Language-Settings.ps1#L260)` `$PackageExclusions` variable.

**Comment by danieljurek** [comment]
> @danieljurek is there somewhere we can see the full logs of the failed npm install command?
>
> My guess is we moved some dependencies to peer dependencies that could potentially cause npm install to fail (cc @prprabhu-ms for vis)

Continuing here... I'll check with the docs team to see if we can get more logs in the CI process to get a better picture of what's happening here.

**Comment by JamesBurnside** [comment]
The DCOM build system uses npm7 so the npm install will fail without `--legacy-peer-deps`, however DCOM does not support a way to pass this flag in for just our package - we need to resolve our peer dependency conflict issue.

This issue is blocked on: https://github.com/microsoft/fluentui/issues/21082

**Comment by JamesBurnside** [comment]
@danieljurek we have pushed a new version (1.2.0) with a fix to remove the conflicting peer deps. Can you try re-enabling the doc generation?

**Comment by danieljurek** [comment]
Preliminary build testing shows success. I've opened a PR to fix: https://github.com/Azure/azure-sdk-for-js/pull/21252/files

**Comment by JamesBurnside** [comment]
Thanks for updating that @danieljurek! When should we see changes reflected in https://docs.microsoft.com/en-us/javascript/api/@azure/communication-react ?

**Comment by JamesBurnside** [comment]
Closing as this looks to have been resolved with the fix to the conflicting peer deps.
