### ISSUE TITLE
Video call experience in Communication ui library - CallComposite sample

### ISSUE THREAD

**Issue by martinesmann** [Azure/communication-ui-library#1650]
**Describe the bug; what happened?**
It is not always possible to see remote participants videos.
It is not always possible to share local video.

When using the Call Composite sample, https://azure.github.io/communication-ui-library/?path=/docs/composites-call-joinexistingcall--join-existing-call

**What are the steps to reproduce the issue?**
Preview https://azure.github.io/communication-ui-library/?path=/docs/composites-call-joinexistingcall--join-existing-call
1) Enter needed values to join a call
2) Join call with a few participants, using unique join values
3) Share video/voice.

If a person starts sharing video, a set of random events seem to occur. 
Person A shares video with B og C
B also starts video sharing, then B’s remote participants view stops showing video from A. 
B stops video, but can still not able to see any remote videos. 
B needs to rejoin the call to see the video of A and never start video sharing…
A seems to be in the same “situation” and there not able to see video from B… 
Sometimes the moon and stars align perfect and magically both A and B are able to see video … but it seems totally random... 

Many other, seemingly, random scenarios occur as part of starting and stopping video. Also the “console.log” is very chatty with warnings and errors with respect to local video already started etc. 

I guess this is not the intended behaviour… but what am I doing wrong?

**What behavior did you expect?**
Video and voice should be visible to all participants, behave like a Microsoft Teams call.

**If applicable, provide screenshots:**
n/a

**In what environment did you see the issue?**

- OS & Device: MacOS, iOS, Windows, Android
- Browser: Microsoft Edge, Google Chrome, Apple Safari
- Version: latest version of browser and os on all devices.

**Is there any additional information?**

**Comment by willieburger34** [comment]
I am having the exact same issue - compiled the latest call composite. Can only see my own video and none of the other participants video. 
Clicking on Show Participants in Mobile Form Factor crashes the component and the browser.

Tested in both Chrome and Edge

 btn.onclick=async ()=>{
            var dvParams = document.getElementById("dvParmaters");

            dvParams.style.display = 'none';
            const endpointUrl = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx';
            const user = txtUser.value;
            const displayName = txtDisplay.value;
            const token = txtToken.value;
            const groupId = txtGroupId.value;

            callAdapter = await callComposite.loadCallComposite(
              {
                groupId, // Provide any GUID to join a group
                displayName: displayName,
                userId: user,
                token: token
              },
              document.getElementById('video-call-container'),
              {
                  formFactor:'mobile'
              }
            );

        };

**Comment by martinesmann** [comment]
Hi @mgamis-msft 
Thanks for following up on the issue. Let me try and clarify and be more precise in the description. 

I used the sample code to join a group call/group id (a self picked guid) I did **not** join a Team's Call. 
https://azure.github.io/communication-ui-library/?path=/docs/composites-call-joinexistingcall--join-existing-call. 

To clarify 1) 
I joined a group call (**not** a Teams call) with 4 participants all with a unique: token, user id  and display name and a shared group id value (allowing the participants to join the same call)
For simplicity, let's call the participants P1, P2, P3, P4. 

To clarify 2) 
After joining the call with P1...P4. 

Case 1: 
If P1 starts to share video not all (if any) participants in the call can see the shared video feed. P2...P4 do not get any indication of video being shared. (Again this happens from time to time, seems very random/unpredictable) 

Case 2:
P1 has successfully shared video with at least 1 other participant (let's say P2). All other participants do not share video. 
P2 can see video from P1. If P2 decides to also share video, then the video feed from P1 on P2's "screen" stops/disappears as if P1 stopped sharing video. (Again this happens from time to time, seems very random/unpredictable) 

Case 3:
No access to video/microphone. A participant can also be meet with the error message that video and/or microphone access has not been granted to the web application. Checking browser settings (video icon to the right on the address bar reveals that the access is granted.) 
I P1 turns on and off video a few times, rapidly and continuously then at some point this error message and appear. 
Other error messages can also show-up in the debug console log (F12 dev tools). These warning messages are mostly "can not stop local video stream as it is already stooped".

To clarify 3)  
All cases have been observed on all devices (iOS, Android, Mac, Windows, Edge, Chrome, Safari) but not consistently, they have a tendency too pop-up randomly. 
As an example, I tested on on an iPhone (latest os version) and everything was working perfect, no issues... half an hour later nothing worked and all the above cases could be reproduced. 
The same for Mac, PC.   

I hope the above helps to better understand the behaviour.

**Comment by willieburger34** [comment]
Hi @mgamis-msft 

I have managed to replicate the exact same issue using the single HTML file below. You can access the site using the link below.

https://bicsolxmediaxstxdev001.blob.core.windows.net/testvoip/TestCall.html

Below is what it looks like after both has joined to call from two different machines and enabled their cameras.

![image](https://user-images.githubusercontent.com/95677729/158551787-31f9b608-3aa3-4bf8-b761-1d34acb1e49c.png)

The full source for the site below.

![image](https://user-images.githubusercontent.com/95677729/158552076-abc2d18a-e72e-49f6-a468-87c9cdf5de6a.png)

I hope this helps.

**Comment by mgamis-msft** [comment]
Thanks @martinesmann for the details. We are seeing the video streams not rendering with our samples when participants join in quick succession. 

Thanks @willieburger34 for providing a sample for us. We are also seeing similar behavior here. 

We are investigating the cause of this issue more deeply.

**Comment by willieburger34** [comment]
Hi @mgamis-msft thank you so much. I will follow this thread :) Have a good day!

**Comment by martinesmann** [comment]
Thanks @mgamis-msft for looking into the issue. Please keep us updated on any progress :) Have a great day!

**Comment by martinesmann** [comment]
@mgamis-msft Is there any update og other information to share on the issue? 
My client has moved into production with ACS service and use this ui framework and the users are starting to experience the issues and and reporting them to the clients customer support team.

**Comment by mgamis-msft** [comment]
@martinesmann I apologize for the delay on this issue. We currently are not able to work around the calling infrastructure issue on the client side in the meantime before March 25.

**Comment by martinesmann** [comment]
@mgamis-msft Thanks for the update and looking very much forward to the update on the 25th. 
Will the fix include an update to the current ui library? I'm trying to prepare for any updates that may need to be done on my end.

**Comment by mgamis-msft** [comment]
@martinesmann Sorry for the slow response but there would be no update to the current ui library required,

**Comment by prabhjot-msft** [comment]
The issue has been fixed and expected behaviour can be seen for the video calling. Feel free to open another issue if you face any other challenges.

**Comment by prabhjot-msft** [comment]
The issue has been fixed and expected behaviour can be seen for the video calling. Feel free to open another issue if you face any other challenges.
