### ISSUE TITLE
Group calls using the UI Library can yield an unexpected rendering experience in the video gallery

### ISSUE THREAD

**Issue by alkwa-msft** [Azure/communication-ui-library#1702]
We have detected an issue in our calling backend that is causing our client code that manages client state to become inconsistent. This yields a calling experience in which some participants may not be able to see all participants on the call. We will have an update by EOD March 25, 2022 when the change is expected to be rolled out to our production clusters. We are sorry for the inconvenience and will continue to update this issue with either the issue has been resolved or if there are more additional areas we will need to look into.

**Comment by prabhjot-msft** [comment]
Bug has been fixed. Closing the issue.
