### ISSUE TITLE
VideoTile error in iOS Safari <=13.3

### ISSUE THREAD

**Issue by m-muratori** [Azure/communication-ui-library#1712]
**Describe the bug; what happened?**
On iOS Safari <=13.3 the VideoTile component raises an error when rendered. This occurs with or without an active video stream. A similar error occurs when VideoGallery is rendered. 
With newer version of iOS ( >= 13.4) this error does not occur.

**What are the steps to reproduce the issue?**
Simply place a VideoTile or a VideoGallery component in the render tree.
You can also notice an error navigating to the Local Preview sample page in the UI Library: https://azure.github.io/communication-ui-library/?path=/story/examples-localpreview--local-preview

**What behavior did you expect?**
VideoTile and Videogallery should render correctly.

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/26094189/159668734-67e2710b-b649-4b85-96a2-51ab98351539.png)

**In what environment did you see the issue?**
- OS & Device: iPhone XS
- Browser: Apple Safari
- Version: <=13.3

**Is there any additional information?**

**Comment by prabhjot-msft** [comment]
@m-muratori we are looking into the issue, will keep you posted.

**Comment by prabhjot-msft** [comment]
@m-muratori could you please provide call id or browser/console logs for the occurring issue?

**Comment by prprabhu-ms** [comment]
Thanks a lot for helping with the logs.

The exact problem encountered was:

```
[Error] ReferenceError: Can't find variable: ResizeObserver
	VideoTile (bundle.js:144838:85)
	renderWithHooks (bundle.js:355661)
	mountIndeterminateComponent (bundle.js:358423)
	callCallback (bundle.js:344611)
	dispatchEvent
	invokeGuardedCallbackDev (bundle.js:344660)
	invokeGuardedCallback (bundle.js:344720)
	beginWork$1 (bundle.js:364462)
	performUnitOfWork (bundle.js:363298)
	workLoopSync (bundle.js:363235)
	renderRootSync (bundle.js:363201)
	performSyncWorkOnRoot (bundle.js:362818)
	performSyncWorkOnRoot
	(funzione anonima) (bundle.js:352071)
	unstable_runWithPriority (bundle.js:375691)
	flushSyncCallbackQueueImpl (bundle.js:352066)
	flushSyncCallbackQueue (bundle.js:352054)
	scheduleUpdateOnFiber (bundle.js:362418)
	dispatchAction (bundle.js:356787)
	dispatchAction
	(funzione anonima) (bundle.js:3030)
	asyncFunctionResume
	(funzione anonima)
	promiseReactionJob
```

The problem is that we depend on `ResizeObserver`, which supposedly works iOS 13.1+:  https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#browser_compatibility

But MDN is sometimes off about exact browser versions that implement an API. Your experiments show that this isn't working for 13.3-.

But turns out that Azure Communication Services Calling SDK only supports iOS 15+, so you'd still not be able to use iOS 13.1 (even if we were to find a workaround for `ResizeObserver`.

**Comment by prprabhu-ms** [comment]
I'll close once we've updated our documentation to correctly reflect supported versions (drop stale reference iOS 13, link to actual modality documentation).
