### ISSUE TITLE
Compile time issues in Xcode using 'AzureCommunicationUI', '1.0.0-beta.2'

### ISSUE THREAD

**Issue by Kamaljeetsinghpunia** [Azure/communication-ui-library#1810]
Xcode is showing multiple compile time errors in the library 'AzureCommunicationUI', '1.0.0-beta.2'.

![Screenshot 2022-04-20 at 4 05 25 PM](https://user-images.githubusercontent.com/95396105/164213769-6270a217-69df-4e0d-b2eb-fd156109d835.png)

I am using Xcode 12.3 and swift language version 5

Library name and version is 'AzureCommunicationUI', '1.0.0-beta.2'

**Comment by alkwa-msft** [comment]
This issue is related to the ios UI Lib and using xcode. We have duplicated your issue into the correct repo and will be closing this specific issue.

https://github.com/Azure/communication-ui-library-ios/issues/134
