### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by juaram2** [Azure/communication-ui-library#1828]
**Describe the bug; what happened?**

console error: findDOMNode is deprecated in StrictMode

**What are the steps to reproduce the issue?**
createAdapter 

**What behavior did you expect?**
I don't want to delete Strict mode No console error

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/26706369/165070125-422ece4e-fbe6-44d6-b377-d14e528206e0.png)

**In what environment did you see the issue?**
- npm version 7.24.0
- node v16.10.0
- next version 12.1.0,

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
**Google Chrome**
- Version [e.g. 1.8.0]
 **100.0.4896.127**

**Is there any additional information?**
nextConfig setting
**reactStrictMode: true**
I want to keep reactStrictMode : true

**Comment by carocao-msft** [comment]
Hi, this is a known issue from Fluent UI https://github.com/microsoft/fluentui/issues/19286, unfortunately there is nothing we can do on our end. A large fix is needed from Fluent UI react-northstar to resolve this warning. Let me know if there is anything else I can help with. Thanks for raising this issue! :)

**Comment by mgamis-msft** [comment]
This issue has become stale. This can only be fixed in Fluent UI react-northstar or if we move out of using Fluent UI react-northstar in our `MessageThread` component which not in our plans right now. If others feel strongly about this issue we can re-open it.
