### ISSUE TITLE
Change of date format in every chat messages in chat composite

### ISSUE THREAD

**Issue by sangeethav123** [Azure/communication-ui-library#1862]
By using cross-platform - Chat composite js bundle file (Azure communication services the UI Library) for chat, we are looking for more friendlier date time strings per message like MM/DD/YY, h:mm A (Ex: 04/27/22, 9:40 AM) instead of YYYY/MM/DD h:mm A(2022/05/05 6.30 p.m)

**Comment by alkwa-msft** [comment]
Thanks for logging this issue. Something we can start to look into. Do you have any suggestions on how you would envision this API to customize the date time format?
 
 An additional question.
 
 I am curious would you prefer this type of date format for every message or is it preferred to use terms like "Yesterday" to refer to 5/4/22 (in the case that today is 5/5/22 and the message was sent on the previous day?)

**Comment by carocao-msft** [comment]
> 

Hi，
Thanks for the additional information！ We will be posting a draft PR with some usage documentation to see if it matches your expectations :)

**Comment by carocao-msft** [comment]
Hi, we have created a draft PR for this issue, basically we added a new prop for MessageThread so you can pass in a function to format the timestamps in anyway you like. We have added an example about how to customize timestamp formats in this PR as well, located in storybook/message thread  https://github.com/Azure/communication-ui-library/pull/1863. Let me know if that resolves your issue :) Thank you!

**Comment by sangeethav123** [comment]
Hi,

Thanks for the quick response and progress on #1862 issue!

I have gone through the #1863 PR.
Please correct me if I'm wrong, in that PR, time format is only customized but we need date format to be customized like MM/DD/YY and adding a comma between date and time (04/27/22, 9:40 AM). Is it possible to do that using sample code?

And, one more question.

Can I use that CustomizedFormatTimeStampForChatMessage like below sample code for onRenderMessage?
Because, we are using Chat composite js bundle file (Azure communication services the UI Library) for chat.
***@***.***
***@***.***

**Comment by carocao-msft** [comment]
Hi,
For the first question, yes we can customize both date and time. I will update the PR to include a sample of that.
For the second question, sorry I can't see the sample code you attached.

**Comment by sangeethav123** [comment]
> 

Hi, updated sample code in last comment. Please take a look on it. 
Thanks!

**Comment by carocao-msft** [comment]
Hi, thanks for your snippet! We are going to take a closer look into it

**Comment by sangeethav123** [comment]
Hi,

I have gone through your PR for date time formatting and this is what we expected.
Can you please share me the sample code that how to use this within onRenderMessages or where to use it ?
FYI, you can check the previous conversation in which I have attached some screenshots that we have used!.

**Comment by carocao-msft** [comment]
Hi, 
We still need some more discussion internally before we release this new feature for production use. A storybook snippet will be provided for this feature so you can see it in action. It will not be in onRenderMessages, will be passed in through locale. 
I will update you once we can release this for production use! :)

**Comment by PorterNan** [comment]
Update:
We got this #1863 checked in for the problem, it will be in our next beta version very soon, please keep your eyes on next beta release 😉
