### ISSUE TITLE
Issue when creating the adapter

### ISSUE THREAD

**Issue by harrychy8** [Azure/communication-ui-library#1873]
Hi team,

I have seen some issues on the customer end when creating the callAdapter. 

- CallError: CallClient.createCallAgent: User stack init timeout
- CallClient.getDeviceManager: GetDeviceManager failed

I cannot repro it from my end, and I would like to know the reason that it happened.

My code:
```
try {
  setAdapter(
    await createAzureCommunicationCallAdapter({
      userId: { communicationUserId },
      credential: new AzureCommunicationTokenCredential(token),
      locator: callLocator,
      displayName: name,
    })
  );
  } catch (e) {
    logger.logError(`Failed to create call adapter - ${e.toString()} `);
  }
},
```

**Comment by edwardlee-msft** [comment]
Thank you for filing this issue @harrychy8. To help further investigate, do you happen to know if the errors are being seen by multiple users or if the same user is reporting both errors?

Are you able to provide client-side logs and/or a telemetry correlation ID?

**Comment by harrychy8** [comment]
Thank you very much for your time and help!

**Comment by edwardlee-msft** [comment]
Thank you providing the log ids.
According to the Calling team the timeout is happening under network conditions that don't allow the sdk to initiate the stack properly within 25 seconds.

Are the customers experiencing network connectivity issues?

**Comment by harrychy8** [comment]
Thank you for the fast reply!

I would not think so. 25 sec sounds very bad to me, even for a slow network. Plus the fact that 2% of our customer base is like about 100~people is experiencing this issue every week. Are there other possibilities?  

Best,
Harry

**Comment by edwardlee-msft** [comment]
Hi @harrychy8,
Would you like to discuss further with the Calling team on a call? I can connect you as they would also like to continue this discussion.

**Comment by harrychy8** [comment]
Hi @edwardlee-msft ,

That would be great! Please invite me to the call! Btw here is a detailed summary of data: for the past **7 days**, there were **3539 classes** that happened. out of them,

-  **40** got the "Failed to create call adapter - CallError: CallClient.getDeviceManager: GetDeviceManager failed"
-  **89** got the "Failed to create call adapter - CallError: CallClient.createCallAgent: User stack init timeout"
- **6** got the "Failed to create call adapter - CallError: CallClient.createCallAgent: Failed to create CallAgent"

![image](https://user-images.githubusercontent.com/15678482/168140382-74d67599-77fc-481e-b6ef-23d85280960d.png)

Hope that would help! Thank you for the help and yes please invite me to any Teams meetings :D

Sincerely,
Harry

**Comment by edwardlee-msft** [comment]
Hi @harrychy8 , connected you with the Calling Team on Teams. Please let me know if you are able to see the @mention.

**Comment by prprabhu-ms** [comment]
@edwardlee-msft @harrychy8

Housekeeping. Were we able to collect / forward feedback to the headless Calling team for this issue. Should we close this tracking issue (quality issues should be tracked internally as they do not relate to UI library directly, though I'm very happy that we were able to funnel the issues where they can be dealt with).

Once we know we are tracking these issues at a better place, let's close this bug here.

**Comment by harrychy8** [comment]
Thank you for reminding me! Yes we are tracking it internally and I am closing this issue now.
