### ISSUE TITLE
Aspect ratio incorrect for local video in Video Gallery

### ISSUE THREAD

**Issue by paulnearney** [Azure/communication-ui-library#1902]
The aspect ratio for the local video feed is incorrect. It always shows stretched or compressed, and changes aspect ratio as the screen size changes. This is true whether the local window floats or is embedded in the grid.

The remote video feeds behave correctly and keep the correct aspect ratio as the screen size changes.

I see the same behaviour in the "ui-library-starting-with-calling-stateful" demo.

I'm using:
    "@azure/communication-calling": "1.4.4",
    "@azure/communication-common": "2.0.0",
    "@azure/communication-react": "1.2.0",

Is this a known issue?

**Comment by mgamis-msft** [comment]
Hi @paulnearney, Thank you for filing this issue and the details. I will look into this today.

**Comment by mgamis-msft** [comment]
> > Hi @paulnearney, Thank you for filing this issue and the details. I will look into this today.
> 
> Hi, any update on this at all? any more info you need from me?

Hi @paulnearney, 

I have a pull request to change the default video stream option for the local stream view to `{ scalingMode: 'Crop', isMirrored: true }`. It might take a while for you to see the changes on the next release.

But in the meantime, you can pass in these VideoStreamOptions to `localVideoViewOptions` prop of `VideoGallery` like so:
![Screenshot 2022-05-18 150839](https://user-images.githubusercontent.com/79475487/169168837-fc5b7138-24d3-4689-932e-c2de1273ca73.png)
(first add `import { VideoStreamOptions } from "@azure/communication-react" at the top`;

**Comment by paulnearney** [comment]
Fantastic, thanks - that fixed the issue
