### ISSUE TITLE
Chat examples in storybook don't set the parent width/height only on the message thread

### ISSUE THREAD

**Issue by alkwa-msft** [Azure/communication-ui-library#1903]
^Topic

This means that you need to scroll all the way to the bottom of the message thread to access the sendbox :(
In this example the parent container is around the message thread and the sendbox. Either the explicit width/height
should only be around the messageThread or we need to set a new parent container around the message thread exclusively
with an explicit width/height.

Context: MessageThread will act like a "div" and try to take up as much space as it can in order to allow for an "infinite scroll". This means that the usage of MessageThread would require an explicit width/height set on the parent or on itself perhaps? 

Unsure if this is the only area so please do search across chat sample code in storybook/github so we don't have this issue anymore.

https://azure.github.io/communication-ui-library/iframe.html?id=quickstarts-statefulchatclient--page&viewMode=docs#compose-chat-components

![image](https://user-images.githubusercontent.com/79329532/168844279-16c3eaa9-6c30-4b53-ad31-a300455d1a3b.png)
github.io/communication-ui-library/?path=/docs/quickstarts-statefulchatclient--page

**Comment by mgamis-msft** [comment]
Thanks @alkwa-msft for filing this issue and the details. I will take a look at this today
