### ISSUE TITLE
UI Library - Local preview not working when we disable and enable it again - video stuck

### ISSUE THREAD

**Issue by sai0909** [Azure/communication-ui-library#1946]
Link - https://azure.github.io/communication-ui-library/?path=/docs/examples-localpreview--local-preview

From the above link, When we disable the video and enable it again, it gets stuck.

**Comment by prprabhu-ms** [comment]
Thanks for reporting this. I have a PR up to fix the local video story.

http://aka.ms/acsstorybook will be fixed once this PR merges and we do a beta or stable release.
