### ISSUE TITLE
Add CallComposite for Teams Users 

### ISSUE THREAD

**Issue by uharston** [Azure/communication-ui-library#1951]
**What feature are you requesting?**
I have been trying connect as with my Teams identity inside my custom application. I am using the '@azure/communication-identity' package. 

`const identityClient = new CommunicationIdentityClient(token);`
`const teamsToken = await identityClient.getTokenForTeamsUser(idp_access_token)`
      
 So far I have not seen a way in create a CallComposite with a teams identity? 
 
 Has anyone been able to do this so far? CallComposite depends on a CallAdapter which depends on an ACS userId. For Teams Users you only receive a token to create a CallClient. The UI implementation is up to you at that point from what I have seen in the docs.
 
 **Does ACS have UI components for Teams Users?**
 
 https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-voice-video-calling-custom-teams-client

**Comment by ddematheu2** [comment]
@uharston We currently don't support Teams identity through the UI Library. Curious to learn more about your scenario so we can prioritize appropriately to bring these capabilities in.

**Comment by ddematheu2** [comment]
The quickstart linked above is related to placing calls to Teams users. Just want to confirm whether your scenario is to enable a Teams user with their identity to use the Call Composite? Or is it to take the Call Composite to place a call to Teams user (per the Quickstart linked)

**Comment by prprabhu-ms** [comment]
Just noting that support for using Teams identity via the `getTokenForTeamsUser` method is in public preview: https://docs.microsoft.com/en-us/azure/communication-services/concepts/teams-endpoint

I've notified the relevant folks that the quickstarts you linked should probably also have a banner making this clear.

The UI library does not  support this feature *yet* and it is not stabilized fully in the service layer.

**Comment by PorterNan** [comment]
> Just noting that support for using Teams identity via the `getTokenForTeamsUser` method is in public preview: https://docs.microsoft.com/en-us/azure/communication-services/concepts/teams-endpoint
> 
> I've notified the relevant folks that the quickstarts you linked should probably also have a banner making this clear.
> 
> The UI library does not support this feature _yet_ and it is not stabilized fully in the service layer.

Noted that, chat capability directly from teams wouldn't be supported by our sdk, it is only supported by Graph API for now, so we don't expect meeting composite and chat composite will be working in short term

**Comment by prprabhu-ms** [comment]
Closing this issue as there are no AIs in the UI library.

Please feel free to continue this discussion over at [our Q&A topic](https://docs.microsoft.com/en-us/answers/topics/azure-communication-services.html) for a more holistic response.
