### ISSUE TITLE
User-Agent not supported in iOS WKWebView

### ISSUE THREAD

**Issue by bfwg** [Azure/communication-ui-library#1977]
**Describe the bug; what happened?**
We ran into an issue where ACS UI throws User-Agent not support when running the web page inside an iOS WKWebView.

**What are the steps to reproduce the issue?**
Create a WKWebView in an iOS app, and load the page which has ACS UI conference.

**What behavior did you expect?**
The conference works just like in an iOS Safari

**If applicable, provide screenshots:**

**In what environment did you see the issue?**
Development

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] iOS
- Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox] WKWebView
- Version [e.g. 1.8.0]1.2.0

**Is there any additional information?**

**Comment by bfwg** [comment]
We are setting the WKWebView's User-Agent to a hardcoded iOS Safari UA as a workaround at the moment.

**Comment by alkwa-msft** [comment]
https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features

We only support calling experiences on webpages through safari on ios. We don't support web views at this time.

![image](https://user-images.githubusercontent.com/79329532/172736661-23c5d66b-699e-4192-8b09-8a7c7329365c.png)
