### ISSUE TITLE
Call id mismatch in CallAdapterState

### ISSUE THREAD

**Issue by levimiller-qhrtech** [Azure/communication-ui-library#2010]
**Describe the bug; what happened?**
The CallState call id doesn't match the actual call id.

**What are the steps to reproduce the issue?**
Create a CallAdapter, log it to the console, join a call, and compare adapter.call.id to adapter.getState().call.id

(It is intermittent, but I get it 99% of the time)

**What behavior did you expect?**
I'd expect the actual call id to match the call id in CallAdapterState.

**If applicable, provide screenshots:**
<img width="318" alt="Screen Shot 2022-06-21 at 3 51 21 PM" src="https://user-images.githubusercontent.com/69543580/174910356-89662beb-f6b9-4b26-80ce-08f5e8a00b78.png">

**In what environment did you see the issue?**
Google Chrome Version 102.0.5005.115 (Official Build) (x86_64)
 
**Is there any additional information?**
For context, I'm trying to get the callId from the adapter to find the call in the callAgent and pass it to \<CallProvider\>:

```
// uses createAzureCommunicationCallAdapterFromClient
const { callClient, callAgent, adapter } = customHook(props);
const [callId, setCallId] = useState<string>();
const [call, setCall] = useState<Call>();

useEffect(() => {
  const onStateChange = (state: CallAdapterState) => setCallId(state.call?.id);
  adapter.onStateChange(onStateChange);
  return () => adapter?.offStateChange(onStateChange);
}, [adapter]);

useEffect(() => {
  setCall(callAgent?.calls.find((c) => c.id === callId));
}, [callAgent, callIdsRef.current, callId]);

<CallClientProvider callClient={callClient}>
  <CallAgentProvider callAgent={callAgent}>
    <CallProvider call={call}>
    .....
      </CallProvider>
  </CallAgentProvider>
</CallClientProvider>
```

If I don't do this, then I can't use the useSelector hook because the callId in the props is undefined.

**Comment by anjulgarg** [comment]
Hi @levimiller-qhrtech 
Thanks for sharing the code snippet.
I understand you are trying to provide the call object for the current ongoing call to the `CallProvider`.

Did you trying passing the call object returned by `callAgent.join` to `CallProvider` ?

**Comment by levimiller-qhrtech** [comment]
I'm not calling callAgent.join directly, I'm using the `CallComposite`. I just need `CallProvider` for a custom component.

**Comment by levimiller-qhrtech** [comment]
Also, as a workaround I'm using `const callId = (adapter as any).call.id` in place of `const callId = adapter.getState().call.id`

**Comment by prprabhu-ms** [comment]
@PorterNan do we have the intricacies of call ID in the call adapter documented somewhere?

**Comment by PorterNan** [comment]
Hi @levimiller-qhrtech, thanks for reporting the issue, do you know which version of our package you are using? We do have a bug fix for this https://github.com/Azure/communication-ui-library/pull/1818/
But not sure if the version you are using is beta or stable one

**Comment by levimiller-qhrtech** [comment]
I'm currently using "@azure/communication-react": "1.2.0", but I'll try on the most recent version

**Comment by PorterNan** [comment]
> Yeah, I tested "@azure/communication-react": "1.2.2-beta.1" and can't reproduce it anymore 🙂
> 
> Sorry for the trouble

Thanks for the verification! Gald that the bug has been fixed!
