### ISSUE TITLE
No instruction to add EndpointUrl and cd samples\Chat is not working

### ISSUE THREAD

**Issue by iaulakh** [Azure/communication-ui-library#2020]
**Describe the bug; what happened?**
1) Github readme has no instruction to set EndpointUrl
2) cd samples\Chat is not working on Mac OS

```
communication-ui-library % cd samples\Chat
cd: no such file or directory: samplesChat
```

**What are the steps to reproduce the issue?**
Please follow instructions from https://github.com/Azure/communication-ui-library/tree/main/samples/Chat for `local run`

**What behavior did you expect?**
1) Github readme has no instruction to set EndpointUrl -> should have instructions to set
2) cd samples\Chat is not working on Mac OS -> should be  cd samples/Chat

**In what environment did you see the issue?**

- OS & Device: Mac
- Browser - Chrome

**Comment by carocao-msft** [comment]
Hi, I am looking into this issue, for cd samples\Chat it actually should be cd samples/Chat, will update that! Looking into setting endpointurl instructions as well :)

**Comment by carocao-msft** [comment]
For setting up endpoint url and connection strings, you can see instructions here 
<img width="1111" alt="Screen Shot 2022-06-27 at 9 51 35 AM" src="https://user-images.githubusercontent.com/96077406/175994328-d92fe3e1-05c0-4c98-a5df-f8676eabbdae.png">

**Comment by carocao-msft** [comment]
Pr here for the update https://github.com/Azure/communication-ui-library/pull/2022. Let me know it there is anything else I can help! :)

**Comment by carocao-msft** [comment]
Merged the update. Let me know if there is anything else you would like me to help! :)

**Comment by alkwa-msft** [comment]
Closing this issue. Please re-open if there is still an issue.
