### ISSUE TITLE
Encountered ERROR during rush install

### ISSUE THREAD

**Issue by strawhat-shima** [Azure/communication-ui-library#2029]
When I git cloned and executed rush install, an ERROR occurred on the way.

Linking local projects

LINKING: @azure/communication-react

ERROR: Internal Error: Cannot find installed dependency "@fluentui/react" in
"C:\projects\meet\sample\communication-ui-library\common\temp\node_modules\.pnpm\local\C%3A%2Fprojects%2Fmeet%2Fsample%2Fcommunication-ui-library%2Fcommon%2Ftemp%2Fprojects%2Fcommunication-react.tgz\node_modules"
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.

**Comment by carocao-msft** [comment]
Hi, Do you mind trying rush install again? 
And then rush install -p if rush install fails to ensure the install did not get into an incorrect state

**Comment by alkwa-msft** [comment]
@strawhat-shima pinging to see if you were still able to repro this issue and give us additional information or if the above instructions were able to help you out?

**Comment by strawhat-shima** [comment]
I'm sorry to reply late. I tried install -p and the result was the same.
There may be something wrong with my environment. I will try it on another PC at a later and report the result.

**Comment by mgamis-msft** [comment]
@strawhat-shima If you are still seeing issues, please try `rush update --full`.

**Comment by strawhat-shima** [comment]
Thanks, I tried rush update -all but it ended with another error.

ERROR: Internal Error: Cannot load shrinkwrap at
"C:\projects\meet\sample\communication-ui-library\common\temp\pnpm-lock.yaml"
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.

But, I tried it on another PC and rush install was successful. I will proceed with this. Thank you very much.
