### ISSUE TITLE
Message Status Indicator not working consistently in (Azure communication services the UI Library) for chat

### ISSUE THREAD

**Issue by sangeethav123** [Azure/communication-ui-library#2058]
We were using cross-platform - Chat composite js bundle file (Azure communication services the UI Library) for chat.
(https://azure.github.io/communication-ui-library/?path=/docs/use-composite-in-non-react-environment--page)
Using this we are sending and receiving messages between chat users and the issue is, message status indicator(Sent & Seen) is not working consistently.
 
Example: Message sent from X person to Y person and its read by Y, indicator is shown as Seen(working fine). But, if any refresh made in X chat window or if X switches to some other chat and back to Y chat again, indicator should remain in seen status (already Read by Y) but, its showing as sent in X chat window.

FYR, 
![seen icon issue](https://user-images.githubusercontent.com/97170459/177979352-a8b2bcd3-d985-43a7-82cd-2b6108d1a9cc.gif)
.

**Comment by mgamis-msft** [comment]
Hi @sangeethav123, thanks for filing this issue. We will take a look.

**Comment by mgamis-msft** [comment]
@sangeethav123 I cannot reproduce this when refreshing one chat composite with one thread. 
May I ask how you are switching chat threads? Are you using multiple chat composites or just one?

**Comment by sangeethav123** [comment]
Hi,
We are using only one chat composite js bundle. For switching between chat threads, we are just passing the necessary tokens, threadId and userId.
FYI, I have attached code which we have followed for loading chat window below ,

loadChat: async function(chatUserDetails , threadId) {
            const { user, token } = { token: chatUserDetails.userToken, user: { communicationUserId: chatUserDetails.azureUserId } };

            const onFetchAvatarPersonaData = () =>
                new Promise((resolve) => {
                    return resolve({
                        imageUrl: this.profileImageUrl+this.selectedUserDetails.selectedUserResponse.username
                    });
                });

            const onRenderMessage = (messageProps, defaultOnRender) => {
                messageProps.showDate = true;
                if(messageProps.message.mine) {
                    messageProps.messageContainerStyle = {
                        backgroundColor: '#007994',
                        color: '#FFFFFF !important',
                        borderRadius: '8px !important',
                        right: 0,
                        '& .ui-chat__messageheader': {
                            textAlign: 'right'
                        }
                    };
                } else {
                    messageProps.messageContainerStyle = {
                        borderRadius: '8px !important',
                        backgroundColor: 'white',
                        left: 0
                    };
                }
                return defaultOnRender ? defaultOnRender(messageProps) : '';
            };

            this.chatAdapter =  await chatComposite.loadChatComposite({
                    displayName: chatUserDetails.fullName,
                    threadId: threadId,
                    endpoint: this.azureEndpointUrl,
                    userId: user,
                    token: token
                },
                document.getElementById('chat-containerNew'),{
                    options: { topic: false, participantPane: false},key:Date.now(),
                    onFetchAvatarPersonaData: onFetchAvatarPersonaData, onRenderMessage: onRenderMessage
                });
        },

**Comment by mgamis-msft** [comment]
@sangeethav123 Thank you for sharing your code. It helped me create a simpler but similar thread switching chat. However, I was not able to reproduce it what you are seeing. I have attached a video of my testing. 

https://user-images.githubusercontent.com/79475487/178701297-3db6d62a-96c6-427e-89a1-87cc650cb645.mp4

The code I used is in this attached txt file.
[multi-chat-thread-js-bundle-app.txt](https://github.com/Azure/communication-ui-library/files/9100923/multi-chat-thread-js-bundle-app.txt)

I may have missed steps/scenarios in how to reproduce the issue you are seeing so we have filed a bug to track this issue. Please add any other additional details.

Also if you are using the prebuilt bundles in your code (not the url in your script tag), please ensure you have the latest bundles.

**Comment by sangeethav123** [comment]
Hi,

I have now used the latest bundle, the issue on message indicator is solved. But I didn't get timestamp for every messages, its showing only for the first message which we have sent/received.
It happens in your previous attached video also. How to fix that?

**Comment by mgamis-msft** [comment]
@sangeethav123 Thanks for letting us know. 
For your follow up question, currently our Chat Adapter has this behavior of only showing the timestamp of the first message when a group of messages come from the same sender. Unfortunately, we have not made it customizable at this point. Please file another issue so that we can mark it as an enhancement for our backlog.
