### ISSUE TITLE
Message Timestamp not showing for every message in (Azure communication services the UI Library) for chat 

### ISSUE THREAD

**Issue by sangeethav123** [Azure/communication-ui-library#2099]
We were using cross-platform - Chat composite js bundle file (Azure communication services the UI Library) for chat.
(https://azure.github.io/communication-ui-library/?path=/docs/use-composite-in-non-react-environment--page)

Currently its only showing the timestamp of the first message when a group of messages come from the same sender. Because of this we may not able to know the exact timestamp of the last received message. 
Example: In the screenshot attached below,
The first **hi** message sent **yesterday** and the last **hi** message sent **today** but, the receiver cannot able to know the exact timestamp of last message.
![image](https://user-images.githubusercontent.com/97170459/179698599-6f717e4c-ef34-46e7-9e41-4feb2b0382e0.png)

**Comment by prabhjot-msft** [comment]
Hi @sangeethav123, I am looking into the issue. Will post here once I have some update.

**Comment by carocao-msft** [comment]
Hi @sangeethav123 , thanks for bringing this up! 
I am wondering if you prefer to have timestamps on all messages or only show timestamps when there is a certain time gap between each message?

**Comment by sangeethav123** [comment]
Hi,
I prefer to have timestamps when there is a certain time gap between each messages

**Comment by carocao-msft** [comment]
Sounds good thanks! We will create a work item for this new feature and update you once it's available :)

**Comment by carocao-msft** [comment]
Hi, we have made the changes and got this PR https://github.com/Azure/communication-ui-library/pull/2299 checked in for the problem, it will be in our next beta version very soon, please keep your eyes on next beta release 😉
