### ISSUE TITLE
stream-media-loading-spinner always shows when someone sharing the screen.

### ISSUE THREAD

**Issue by GHY18** [Azure/communication-ui-library#2186]
There is always a loading spinner when someone sharing the screen.
![image](https://user-images.githubusercontent.com/39253803/183823762-7e15694c-b49a-4ccd-b884-b1a8ea1e594a.png)
I implemented the calling app with CallComposite, and wonder how to fix it. 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/39253803/183802390-3af7c0ef-803c-471a-a820-edfde2c091ae.png">

- `@azure/communication-react` npm package version (if applicable): 1.3.0
- `@azure/communication-calling` npm package version (if applicable): 1.5.4
- `@azure/communication-chat` npm package version (if applicable): 1.2.0

- OS & Device: iOS, Windows on iPhone XR, PC
- Browser: Microsoft Edge, Google Chrome, Apple Safari

**Comment by PorterNan** [comment]
Thanks for reporting the regression, a PR has being merged into main branch https://github.com/Azure/communication-ui-library/pull/2191 to fix this bug, please wait for next version release to get the fix, a temporary workaround is downgrade the version to 1.2.0 or use our beta version

Will send another update here whenever we push the new version which fixes the regression

**Comment by PorterNan** [comment]
Hi, we've released a new stable patch version 1.3.1 to address this regression, please take a try and verify if that works for you, and feel free to reopen the issue if you find the problem still exists.
