### ISSUE TITLE
Display name is not allowed to be set for Teams users.

### ISSUE THREAD

**Issue by NicolasHumann** [Azure/communication-ui-library#2214]
Hi,

I want to use ACS to start and join a Teams meeting. I retrieve the JoinWebUrl from the Graph and the Token from ACS.
When I start the call adapter I have this error in the Console

callComposite.js:2 
        
       Uncaught (in promise) CallError: CallClient.createCallAgent: Display name is not allowed to be set for Teams users.
    at Ze (callComposite.js:2:3244183)
    at $e.<anonymous> (callComposite.js:2:3243853)
    at Generator.throw (<anonymous>)
    at s (callComposite.js:2:3243620)

```
const callAdapter = await callComposite.loadCallComposite(
                        {
                            groupId: uuidv4(),
                            userId: userId,
                            callInvitationURL: meeting.joinWebUrl,
                            token: meeting.azureCommunicationToken.token
                        },
                        document.getElementById('video-call-container')
                    );
```

I tried to put displayName as null, but same error.
What should I do?

Thank you

**Comment by PorterNan** [comment]
Hi, thanks for reporting the issue, for now callComposite.js bundle only support groupId scenario, we might add teams meeting and more scenarioes to it in the future, but if you want to take a try now, it's highly recommended to use our react version - it has the full compatibility with teams meeting
Check it here https://azure.github.io/communication-ui-library/iframe.html?viewMode=docs&id=composites-call-joinexistingcall--join-existing-call#basic-usage

**Comment by dmceachernmsft** [comment]
@NicolasHumann we should see this fix in the next beta release. We had a fix for the JS bundle go in for this PR: https://github.com/Azure/communication-ui-library/pull/2230

Of course feel free to clone and build the JS bundle yourself in the mean time!

**Comment by prprabhu-ms** [comment]
If I am reading this correctly, the issue here was that the JS bundle did not expose a way to join a Teams call.
That support was added in #2230.

The chat bundle hosted on GitHub was updated with that fix in the last beta release: https://github.com/Azure/communication-ui-library/releases/tag/PublicPreview%2F1.3.2-beta.1

Please let us know by reopening this bug if you still see this issue.

Thanks for reporting!
