### ISSUE TITLE
Unable to change the style of myChatMessageContainer for the MessageThread component

### ISSUE THREAD

**Issue by jboinembalome** [Azure/communication-ui-library#2257]
**Describe the bug; what happened?**
First of all, thank you very much for your work.
The `MessageThread `component has a "styles" prop allowing us to change the style of the following elements:
- `myChatMessageContainer`
- `chatMessageContainer`

If we add style for both elements we can see that the style is applied for `chatMessageContainer `and not for `myChatMessageContainer`.

**What are the steps to reproduce the issue?**

1. Create a constant containing the style to be applied:
```
const messageThreadStyle : MessageThreadStyles = {
  chatMessageContainer: {
    background: '#F5F5F5',
    borderRadius: '8px'
  },
  myChatMessageContainer: {
    background: 'cornflowerblue',
    borderRadius: '8px'
  }
};
```

2. Add the style to the MessageThread component:
<MessageThread
        userId={currentUserId}
        messages={messages}
        showMessageStatus={true}
        showMessageDate={true}
        styles={messageThreadStyle}
 />

3. If you start your project, you will get the following result:
![image](https://user-images.githubusercontent.com/70820612/186355102-9b217bf9-820a-443a-a0cd-85f5aa1ffdeb.png)

As we can see, the background of `myChatMessageContainer `is in red.

**What behavior did you expect?**
If possible, I would like to have the possibility to add styling for `myChatMessageContainer `in order to be consistent with `chatMessageContainer `.

**If applicable, provide screenshots:**
Instead of this:
![image](https://user-images.githubusercontent.com/70820612/186355102-9b217bf9-820a-443a-a0cd-85f5aa1ffdeb.png)

I would like this:
![image](https://user-images.githubusercontent.com/70820612/186356638-57368ccf-bbef-42f6-b95a-dd62f75b33a1.png)

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): 1.3.1-beta.1

- OS & Device: Windows
- Browser: Google Chrome
- Browser Version: 104.0.5112.102 (Official Build) (64-bit)

**Is there any additional information?**
After analyzing the source code, it seems that the style is not applied because of the condition line 361 of the **MessageThread.tsx** file:  
```
const myChatMessageStyle =
          styles?.myChatMessageContainer || message.status === 'failed'
            ? FailedMyChatMessageContainer
            : defaultMyChatMessageContainer;
```

We could add a `failedMyChatMessageContainer `prop in addition to `myChatMessageContainer `and `chatMessageContainer`, this way we could have the following code:
```
const isFailed = message.status === 'failed';
const failedMyChatMessageStyle = styles?.failedMyChatMessageStyle || FailedMyChatMessageContainer;
const myChatMessageStyle = isFailed ? failedMyChatMessageStyle : styles?.myChatMessageContainer || defaultMyChatMessageContainer;   
const chatMessageStyle = styles?.chatMessageContainer || defaultChatMessageContainer;
messageProps.messageContainerStyle = message.mine ? myChatMessageStyle : chatMessageStyle;

```

If you wish, I can work on it. I would be very happy to do this! 👍

**Comment by anjulgarg** [comment]
Hi @jboinembalome 
Thanks for bringing this to our attention and digging into the source code to find the exact issue.
We would love it if you contribute to the library for fixing this bug.

Feel free to fork the repo and create a PR.
The solution offered by you looks good.

Looking forward to your PR.
Let us know if you need help. :)
