### ISSUE TITLE
Autoscrolling of messages in Safari and WebKit based browsers

### ISSUE THREAD

**Issue by Roy19** [Azure/communication-ui-library#2321]
**Describe the bug; what happened?**
On Safari/WebKit based browsers, on scrolling upwards for previous messages, new messages are continuously fetched and are added continuously and the messages list keeps autoscrolling to the top till the first message is received at which point scrolling is stopped. This however doesn't happen in Chrome or Firefox based browsers.

**What are the steps to reproduce the issue?**
Using [this](https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-starting-with-chat-stateful) sample repo, we place our user ids, access tokens and chat thread id here and scroll up in Safari or iOS mobile browsers. You can see that autoscrolling to the top happens continuously until the first message is reached. This however doesn't happen in Chrome or Firefox. Use a chat thread with more than 200 messages. 

**What behavior did you expect?**
Scrolling behaviour should be consistent as with Chrome and Firefox i.e. autoscrolling to the top should be stopped.

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version: 1.2.0
- `@azure/communication-chat` npm package version: 1.1.0

- OS & Device: MacOS, iOS
- Browser: Apple Safari
- Browser Version: Apple Safari on MacOS 14.1.0

**Comment by JamesBurnside** [comment]
Thanks for filing this issue, we'll take a look at this as soon as possible.

**Comment by edwardlee-msft** [comment]
Thank you for filing this issue and bringing it to our attention.
We were able to reproduce the issue on Safari MacOS with our latest communication-react package version of 1.3.1 and are working on a resolving this bug.

**Comment by Roy19** [comment]
@edwardlee-msft @JamesBurnside any idea when a public release might be available with the issue resolved?

**Comment by edwardlee-msft** [comment]
Hi @Roy19, we are still working on the issue and will get back to you with an update as soon as one is available.

**Comment by edwardlee-msft** [comment]
Status update: We are still looking into this issue and are currently working on integrating a fix into our packages. 
I will provide a new update once a fix is available.

**Comment by Roy19** [comment]
@edwardlee-msft I see that the pull request has been merged. Is there a release planned out for this bug?

**Comment by edwardlee-msft** [comment]
Hi @Roy19 ,

We are working on having a release ready that includes this bug fix soon. 
I will update you once the release is available.

**Comment by Roy19** [comment]
Sounds good. Thanks @edwardlee-msft.

**Comment by prprabhu-ms** [comment]
The fix was released in the latest beta release: https://github.com/Azure/communication-ui-library/blob/36c8c2789833aace33e43e25f931b957f744555b/packages/communication-react/CHANGELOG.md?plain=1#L98

and will be included in the next stable release of the package.

**Comment by carocao-msft** [comment]
Hi, we have recently released stable 1.4.0 and the fix was included in this release. Going to close this issue and please open another github issue if you have more questions! 
Here is the changelog for stable release 1.4.0 https://github.com/Azure/communication-ui-library/blob/main/packages/communication-react/CHANGELOG.md#140
