### ISSUE TITLE
Are there any plans to support landscape on mobile? And can I zoom in and out when I share?

### ISSUE THREAD

**Issue by General-Zhang** [Azure/communication-ui-library#2373]
When the landscape screen is displayed on mobile phone, the scope of the screen is too small, can you display it on the right side like Teams client?

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/41287016/192980129-c0cc09a3-6c3a-4410-bad0-816b6361f75e.png)

**Comment by anjulgarg** [comment]
Hi @General-Zhang 
Thanks for reaching out to us.
We understand the challenges with using screen share on mobile devices and are working towards improving this experience.
However, we don't have a timeline to share for these improvements.
Please stay tuned and look out for this in one of our future releases.

As an alternative, you can create a custom calling experience with customized video gallery layout using pure UI Components.

Closing this issue. We have noted your feedback.
Thank you.
