### ISSUE TITLE
Video Aspect in CallComposite

### ISSUE THREAD

**Issue by Andre-Bertram** [Azure/communication-ui-library#2375]
**Describe the bug; what happened?**
   **Using CallComposite:**
   Between 900px and 1447px, the video aspect of a conference call with three participants, is skewed compared to other breakpoints. 
   The crop quality of the videos is slight more fuzzy and unnecessarily zoomed-in.

**What are the steps to reproduce the issue?**
  **Using CallComposite:**
  - Create a conference with three participants
  - Enable two video such that both videos are shown on whichever participant
  - Adjust viewport between 900px and 1447px
  - Notice that video is aspect ratio is skewed and bit fuzzy

**What behavior did you expect?**
  - Video aspect of other callers not zoomed-in unnecessarily
  -  Video quality remains the same as with other breakpoints outside the mentioned range.
 
**If applicable, provide screenshots:**
   
![image](https://user-images.githubusercontent.com/107880737/193121209-fbc22fb1-fb91-4807-84ab-f8418ec32358.png)

**In what environment did you see the issue?**
- `@azure/communication-react` : ^1.3.1
- `@azure/communication-calling` ^1.3.0
- `@azure/communication-chat`: ^1.2.1

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browsers: Google Chrome, Edge
- Browsers Version: [105.0.5195.127, 105.0.1343.53 ]

**Is there any additional information?**

**Comment by prabhjot-msft** [comment]
@Andre-Bertram thanks for filing the issue, we are investigating and will provide an update soon

**Comment by prabhjot-msft** [comment]
@Andre-Bertram Thank you for bringing the issue to our attention. Could you please provide some information for further clarification:
1. The range mentioned in the issue that is between 900px and 1447px, is it just along the width of the screen(x-axis)?
2. Would you prefer the videos to be displayed side-by-side in this viewport rather than in stacked layout or do you prefer the control over the aspect ratio in the same layout?
3. We did not see the fuzziness while adjusting the viewport. Could you also provide the OS & device used.

**Comment by Andre-Bertram** [comment]
@prabhjot-msft Apologies for the delay.

To answer your questions:
 1. Yes, this is just along the x-axis.
 2. In our use case users might require some control over the visible area in each video tile. Optimally we'd have control over 
     the maximum amount the video stream would be cropped in a percentage. That way the user would be able to select 
     between the current style and the presenter style where the tile is letterboxed and not cropped at all.
3. The OS devices used were Windows and Mac desktops. I don't think this is a deal-breaker as it only appears when the videos 
    are zoomed in
    
We are open to suggestions that make the experience better, as well.

**Comment by prabhjot-msft** [comment]
@Andre-Bertram Thanks for the clarification. We understand the issues you are facing currently using the call composites. We are working on adding more features to the composites for handling these scenarios. However, we don't have a timeline to share for these improvements. In the meantime, you can try creating a custom calling experience using the pure UI components where you will have more control over the videos being rendered. 
Closing this issue. We have noted the feedback. Thank you.
