### ISSUE TITLE
Screen Blinks at VideoGallery on Safari (IPad)

### ISSUE THREAD

**Issue by strawhat-shima** [Azure/communication-ui-library#2409]
I have created an app using CallWithChatComposite.
A user of iPad (iOS14, safari) reported that VideoGallery blinks at high speed.
It seems that the number of tiles repeats 2 and 4. ControlBar buttons are also difficult to press.

**Comment by anjulgarg** [comment]
Hi @strawhat-shima 
Thanks for reaching out to us.
To understand the issue better, would it be possible to provide screenshots/videos of how the app renders on the device mentioned?

**Comment by strawhat-shima** [comment]
Thank you for your reply. I'm sorry, it was a report from a user, so I don't have an environment where I can check it at the moment. I'll try to reproduce it, but I feel it's difficult to take a snapshot of the phenomenon.

**Comment by prprabhu-ms** [comment]
If we do get to reproduce this, it would be good to get the package versions used for `@azure/communication-react` and `@azure/communication-calling`.

**Comment by JamesBurnside** [comment]
@strawhat-shima have you had any more reports of this issue? If so could you let us know the versions of `@azure/communication-react` and `@azure/communication-calling` your application is using

**Comment by strawhat-shima** [comment]
Sorry for the late report. I can confirm the phenomenon with some other iPads, but not with some others, so I'm guessing that it's probably an iOS version issue. I will report again when I can confirm the improvement by updating the version of the terminal where the phenomenon has been confirmed.

**Comment by strawhat-shima** [comment]
I report the situation after that. The phenomenon definitely occurs in iOS14.4 and does not occur in 14.7 or later. We encourage users to update their iOS to the latest version.
