### ISSUE TITLE
I can't turn on and off the microphone and camera after entering the room with ipad

### ISSUE THREAD

**Issue by strawhat-shima** [Azure/communication-ui-library#2422]
**Describe the bug; what happened?**
In a sample program using CallWithChatComposite, after joining a group call on an Ipad, tapping the microphone and camera toggle buttons on the ControlBar does not respond. Local video before entering the room can be turned on and off.
at IPad iOS15.7

**Comment by dmceachernmsft** [comment]
Thanks for raising the issue @strawhat-shima! I will bring this to the team and we will start taking a peak into this. In the mean time could you send me a little more information about which version of the communication-ui-library that you are using?

**Comment by dmceachernmsft** [comment]
I believe I was able to reproduce the issue. To clarify when you action the microphone and camera buttons the buttons don't toggle microphone and camera state and they open the device selection tabs?

**Comment by dmceachernmsft** [comment]
Update: From what we can tell this is a issue with Fluent one of our dependencies so we have filed and issue with them: https://github.com/microsoft/fluentui/issues/25323 

A short term fix for this issue would be to set the `formFactor` prop on the CallWithChat composite to `'mobile'` and you will get the standard buttons that you can action properly on mobile devices.

**Comment by strawhat-shima** [comment]
Thank you for confirmation. I tried adding the isIPad function and setting the formFactor to 'mobile'. I can now switch the mic on/off. Thank you for your workaround.

**Comment by JamesBurnside** [comment]
We've had reports of this happening on touch screen desktop devices. We need to push on Fluent to get a fix for this, reopening this issue to keep this on our radar

**Comment by micahgodbolt** [comment]
The guidance that I got is that split button overflows should always include the primary action. 

![d507d35e-6ad4-4eb1-9e89-94a1c652018f](https://user-images.githubusercontent.com/1434956/214908160-b7cdaf51-199f-428d-b57a-5699e9dbfd98.jpg)

**Comment by micahgodbolt** [comment]
in the case of a mute button and an audio input switcher, those should be 2 different button. One regular button and one icon button with a little space between them.
