### ISSUE TITLE
CallWithChatComposite component fails to extract chat thread ID from Teams meeting link containing "thread.tacv2"

### ISSUE THREAD

**Issue by mamazgut** [Azure/communication-ui-library#2477]
**Describe the bug; what happened?**
CallWithChatComposite component cannot properly parse Microsoft Teams meeting link and extract chat thread id. The problem is probably in the `parseTeamsUrl.ts` file. The regular expression is only working for links containing "thread.v2", but not "thread.tacv2"

**What are the steps to reproduce the issue?**

1. Navigate to https://azure.github.io/communication-ui-library/?path=/story/composites-call-with-chat-jointeamsmeeting--join-teams-meeting
2. In the navigation pan select "Preview"
3. Provide all information required to join meeting (including meeting link containing "thread.tacv2")
4. Result: The control is not initialized and console displays error message  `Uncaught (in promise) Error: Could not get chat thread from teams link`

**What behavior did you expect?**
Proper initialization of a component

**If applicable, provide screenshots:**
Not applicable

**In what environment did you see the issue?**
Production

- `@azure/communication-react` npm package version: 1.4.0
- `@azure/communication-calling` npm package version: 1.6.3
- `@azure/communication-chat` npm package version: 1.3.0

- OS & Device: Windows/PC
- Browser: tested in Edge (Chromium)
- Browser Version: 107.0.1418.24

**Is there any additional information?**
No

**Comment by JamesBurnside** [comment]
Hi @mamazgut, unfortunately channel-scheduled meetings are not supported today: https://learn.microsoft.com/en-us/azure/communication-services/concepts/join-teams-meeting#limitations-and-known-issues.

We'll look into making the error thrown more appropriate to highlight this.
