### ISSUE TITLE
[Storybook] duplicated typing indicator event being sent in chat composite

### ISSUE THREAD

**Issue by jpeng-ms** [Azure/communication-ui-library#2478]
**Describe the bug; what happened?**
Please see the video below:

https://user-images.githubusercontent.com/109105353/199550433-a45e0609-b928-4b97-b11c-caaa30c1482e.mov

noticed in console, another typing indicator event being sent out immediately after the message even though user did not start typing

**What are the steps to reproduce the issue?**

1. start typing a message
2. hit enter to sent the message
3. noticed in console, another typing indicator event being sent out even user did not start typing

**What behavior did you expect?**

1. only sent typing indicator when user starts typing

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): [e.g. 1.3.0]
- `@azure/communication-calling` npm package version (if applicable): [e.g. 1.5.4-beta.1]
- `@azure/communication-chat` npm package version (if applicable): [e.g. 1.2.2]

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser: [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
- Browser Version: [e.g. 1.8.0]

**Is there any additional information?**

please let me know if this is the wrong place to report this bug

**Comment by carocao-msft** [comment]
Hi Thanks for raising this issue! We are looking into it

**Comment by jpeng-ms** [comment]
issue only happening when you sent messages using enter key (13) on keyboard, if you click on sent button, then this issue would not appear

**Comment by JamesBurnside** [comment]
Thanks @jpeng-ms for the detailed repro and extra info, looks like we are triggering the typing indicator in the sendbox when any key (including the enter key) is pressed: https://github.com/Azure/communication-ui-library/blob/368c4cefaea1ee51d11c7e4b2e6f8555442a6989/packages/react-components/src/components/SendBox.tsx#L370-L372

This should be an easy fix in the Sendbox Component to check if the enter key was pressed here for sending the message and not typing purposes, something like:
```ts
onKeyDown={(ev) => { 
  const keyWasSendingMessage = ev.key === 'Enter' && (ev.shiftKey === false || !supportNewline);
  if (!keyWasSendingMessage) {
    onTyping?.();
  }
}
```

**Comment by dmceachernmsft** [comment]
Closing as is old and looks like there is a solution. Feel free to reopen if issue arises again!
