### ISSUE TITLE
'Dialpad' is not exported from '@azure/communication-react'

### ISSUE THREAD

**Issue by lucasm107** [Azure/communication-ui-library#2521]
**Describe the bug; what happened?**
'Dialpad' is not exported from '@azure/communication-react'

**What are the steps to reproduce the issue?**
create a new app (react 17 o react 18)
npm install @azure/communication-react

then:
```
import { Dialpad } from '@azure/communication-react';

function App() {
  return (
    <div className="App">
      Hello
      <Dialpad />
    </div>
  );
}

export default App;`
```
=> Attempted import error: 'Dialpad' is not exported from '@azure/communication-react'.

**What behavior did you expect?**
Use the Dialpad component

**In what environment did you see the issue?**
"@azure/communication-react": "^1.4.0",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-scripts": "4.0.3"

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser: Chrorme
- Browser Version: 107.0.5304.88 (Build oficial) (64 bits)

**Is there any additional information?**
no

**Comment by ddematheu2** [comment]
Hey @lucasm107 

Thanks for reporting this issue. There is a missed instruction on the documentation to use our beta package to leverage the Dialpad component. 

You will find the component on your beta version: @azure/communication-react@1.3.2-beta.1

**Comment by edwardlee-msft** [comment]
Thank you for bringing this to our attention. We have now updated our storybook documentation to include package version details for features in public preview.
Documentation update will be available in our next beta release coming soon.
