### ISSUE TITLE
Flag `disableEditing` doesn't do anything in MessageThread

### ISSUE THREAD

**Issue by giulianabaratto** [Azure/communication-ui-library#2569]
**Describe the bug; what happened?**
I'm trying to disable message editing by sending the prop `disableEditing={true}` to MessageThread component. However, the prop doesn't change anything -- the action button is still showing whenever I hover the Message. 

Looking at [the source code](https://github.com/Azure/communication-ui-library/blob/f5a4ff658a1c3ab3246ac1c3d55014ebda73ba55/packages/react-components/src/components/MessageThread.tsx), it seems like the prop is not being passed on to the Message component. There are only 2 references to `disableEditing` and it's on type definition -- and the `props` from MessageThread are not passed on to Message directly.

As a last test, I've also tried to run storybook locally and allowing `disableEditing` to be controlled by the interface -- but I've got the same result. Even when its value is `true`, action buttons are still showing.

**What are the steps to reproduce the issue?**
Try setting the `disableEditing` flag as `true` in MessageThread component and check if action buttons still appear.

**What behavior did you expect?**
By setting `disableEditing={true}`, I expected the action buttons to not appear -- or at least to not allow editing / removing the messages.

**If applicable, provide screenshots:**
Screenshot of local storybook, with `disableEditing` set as `true`:

![image](https://user-images.githubusercontent.com/62035745/205329259-4a5b99da-aa25-495e-8fe3-2485ccc56499.png)

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): 1.3.1
- `@azure/communication-chat` npm package version (if applicable): 1.3.0

- Browser: Google Chrome
- Browser Version: 107.0.5304.123

**Is there any additional information?**
I guess not.

**Comment by karinatber** [comment]
I'm having same trouble here!

**Comment by anjulgarg** [comment]
Hi @giulianabaratto 
Thanks for reaching out to us with the bug and taking some time to investigate the root cause.
We have created a PR to fix this.
https://github.com/Azure/communication-ui-library/pull/2570

This fix should be in the next stable version.

In the meantime, if you absolutely need this feature for your product, I suggest building the package locally with this fix.

**Comment by giulianabaratto** [comment]
@anjulgarg thank you so much, for the fast response and resolution! 😄 Just for planning purposes, any idea when the next stable version will be available?

**Comment by edwardlee-msft** [comment]
Hi @giulianabaratto,
Providing a quick update, we are close to releasing a stable release! I will notify you here once it's available :).
Have a great week and hope you had a wonderful start to the new year.

**Comment by dmceachernmsft** [comment]
Hi @giulianabaratto! Good news! 1.5.0 went live today. included should be a fix for your issue! Please let us know if there is any other questions you have! 😊

https://www.npmjs.com/package/@azure/communication-react/v/1.5.0
