### ISSUE TITLE
`i.CallClient is not a constructor` error  in `CallComposite`

### ISSUE THREAD

**Issue by henrynoowah** [Azure/communication-ui-library#2617]
**Describe the bug; what happened?**

- Azure Commuinication Call causing error when requesting call connection
![image](https://user-images.githubusercontent.com/79410456/209794182-d07cc02c-031a-43d4-a112-5b069b0a8ff5.png)

- I have followed the [GetStarted - CallComposite
](https://azure.github.io/communication-ui-library/?path=/docs/composites-call-basicexample--basic-example) thus updated the code on branch [fix/azure-call-composite](https://github.com/iCloudHospital/cloudhospital.nextjs/tree/fix/azure-call-composite) hoping this would solve the issue but no luck

- Project environment
  - next: `12.3.4` 
  - node:  `16.13.0`
  - typescript: `4.7.4`
  - react": `17.0.2`,

- Please help me out and check if I am doing something wrong with the way of using `CallComposite` component

example: 
```tsx
import { GroupCallLocator } from '@azure/communication-calling'
import { AzureCommunicationTokenCredential } from '@azure/communication-common'
import {
  CallAdapter,
  CallComposite,
  createStatefulCallClient,
  useAzureCommunicationCallAdapter
} from '@azure/communication-react'
import Loading from '@components/common/Loading'
import { mediaQuerySize } from '@constants'
import useResizeHandler from '@hooks/useResizeHandler'
import { log } from '@utils/log'
import { useTranslation } from 'next-i18next'
import { FC, useContext, useEffect, useMemo } from 'react'
import { Context } from 'src/context/ContextProvider'

interface Params {
  displayName: string
  isClosingAcs: boolean
  setIsClosingAcs: Function
  setIsModalOpen: Function
  communicationUserId: string
  credential: AzureCommunicationTokenCredential
  locator: GroupCallLocator
}

const AzureCommunications: FC<Params> = ({
  displayName,
  isClosingAcs,
  setIsClosingAcs,
  setIsModalOpen,
  communicationUserId,
  credential,
  locator
}) => {
  const { setGroupCallId, showCommunications, groupCallId } = useContext(Context)
  const { t } = useTranslation(['common'])

  const windowWidth = useResizeHandler()
  const isMobile = useMemo(() => windowWidth < mediaQuerySize.sm, [windowWidth])

  const statefulCallClient = createStatefulCallClient({
    userId: { communicationUserId }
  })

  const callAdaptorArgs = useMemo(
    () => ({
      userId: { communicationUserId },
      displayName,
      credential,
      locator
    }),
    [communicationUserId, displayName, credential, locator]
  )

  const adapter = useAzureCommunicationCallAdapter(
    callAdaptorArgs,
    async (adapter: CallAdapter): Promise<CallAdapter> => {
      console.log('afterCreate', adapter)
      return adapter
    },
    async (adapter: CallAdapter): Promise<void> => {
      console.log('beforeDispose', adapter)
      await adapter.leaveCall().catch((e) => {
        console.error('Failed to leave call', e)
      })
    }
  )

  useEffect(() => {
    if (adapter) {
      console.log(adapter)
      log('has callAdapter. add callEnded event')
      adapter.on('callEnded', (event) => {
        log('callEnded: ', event.callId)
        setGroupCallId(null)
      })
    }
  }, [adapter])

  useEffect(() => {
    if (isClosingAcs) {
      log('call disposed')
      setGroupCallId(null)
      showCommunications(false)
      setIsClosingAcs(false)
      setIsModalOpen(false)
    }
  }, [isClosingAcs])

  return (
    <>
      {adapter ? (
        <CallComposite adapter={adapter} formFactor={isMobile ? 'mobile' : 'desktop'} />
      ) : (
        <Loading message={t('common:call:initializing_call')} />
      )}
    </>
  )
}

export default AzureCommunications

```

**What are the steps to reproduce the issue?**

**What behavior did you expect?**
- CallCompsite to run as expected

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version: `1.4.1`
- `@azure/communication-calling` npm package version: `1.4.4`

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser: Google Chrome
- Browser Version: `07.0.5304.110` (Official Build) (arm64)

**Comment by alkwa-msft** [comment]
Thanks for sharing this issue. I will be looking into it today.

**Comment by alkwa-msft** [comment]
Hello. I ran the storybook snippet code in a CRA instance and it worked for me. Perhaps there is more you can share about your setup? If there was a repo or something I can try out that would be helpful.

I did see you were using next.js for your project. I do know the calling sdk only works on the browser. So if you are trying to initialize things such as the CallClient but you are in Node as opposed to on the browser it could be an issue?  

@henrynoowah

**Comment by henrynoowah** [comment]
@alkwa-msft 
Hi, thank you for the response,
- I have checked that all Components using the SDK has been imported dynamically with `ssr` settings to false
- All values that are used in `adapter` is also managed using `useMemo` hooks

<br>

😓 apologies for not being able to shaire the repo for internal reasons

**Comment by henrynoowah** [comment]
@alkwa-msft 
Hi, I have received a possible solution for this issue on https://github.com/Azure/communication-ui-library/discussions/2616#discussioncomment-4554346

> I don't know why but the error is gone when I switch swcMinify: true to false in next.config.js Had similar experience with swcMinify conflicts with ACS before.

I still think it would be a improvement if this problem could be solved when `swcMinify` set to `true` when using Nextjs

**Comment by alkwa-msft** [comment]
Sounds like we currently have a mitigation which is fantastic! Created a new github issue for an SWC investigation https://github.com/Azure/communication-ui-library/issues/2620

This is definitely an interesting issue. It is a bit of a slippery slope as you can imagine customers may want us all to support every web framework that they may be using. The goal of this repo is creating a set of react Ui components to help power Azure Communications Services calls and chat experiences.  In this case we would have the UI Library support what we can as a React library but no explicit support for specific frameworks at this time such as Next.JS. 

While technically Next.js uses React it also does other things such as bringing in swc and doing their own minification which is more challenging for us to support at this time. If we do find something we can definitely look into bug fixes with the UI Library.
