### ISSUE TITLE
[Web] [Video streatched when a iPhone/Mobile in Landscape Mode]

### ISSUE THREAD

**Issue by durjanh** [Azure/communication-ui-library#2652]
**Describe the bug; what happened?**

When a user changes the phone orientation mode from Portrait to Landscape.  The video gets stretched on web/mobile screen. The screenshot I have provided is from Google Pixel Phone

**What are the steps to reproduce the issue?**
The code I used from the sample UI Library Application (ui-library-starting-with-calling-stateful)
the only changes I made were width and height from 100vw to 90vw and  height from 100vh to 85vh

**What behaviour did you expect?**

Not to stretched

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/7289173/212926077-1d422a1c-3467-49b5-a24f-e9fceeb92a9f.png)
![image](https://user-images.githubusercontent.com/7289173/212926836-2231bc3d-7034-4863-8f76-f7dd103eb5da.png)

**In what environment did you see the issue?**
Staging and Test

- `@azure/communication-react` npm package version (1.3.0]
- `@azure/communication-calling` npm package version (1.9.1]
- `@azure/communication-chat` npm package version (1.2.2]

- OS & Device: [e.g. Windows, iOS iPhone X, Android Google Pixel] on [iPhone 11, PC]
- Browser: [e.g. Google Chrome,]
- Browser Version: [e.g. 1.8.0]

**Is there any additional information?**

If you need a sample app let me know as I said I didn't change much just the width and height to show our logo.

**Comment by mgamis-msft** [comment]
Hi @durjanh, thanks for bringing this to our attention.

I am investigating this issue.

**Comment by mgamis-msft** [comment]
Hi @durjanh, could you try adding this import:
```
import { VideoStreamOptions } from '@internal/react-components';
```
and these variables:
```
const localVideoViewOptions = {
  scalingMode: 'Crop',
  isMirrored: true
} as VideoStreamOptions;

const remoteVideoViewOptions = {
  scalingMode: 'Crop'
} as VideoStreamOptions;
```
and add them as props to your VideoGallery like so:
```
<VideoGallery         
   {...videoGalleryProps}
   localVideoViewOptions={localVideoViewOptions}
   remoteVideoViewOptions={remoteVideoViewOptions}
   layout="floatingLocalVideo"
/>
```
Let me know if that works for you.

**Comment by durjanh** [comment]
Hi @mgamis-msft,

Thank you very much for the quick update.
I will test it and let you know.

Thanks

**Comment by durjanh** [comment]
Hi @mgamis-msft,

It did work. Thank you very much for your help!

Thanks
