### ISSUE TITLE
Unable to find control that displays list of threads of a participants

### ISSUE THREAD

**Issue by fpereiramapfrepr** [Azure/communication-ui-library#2669]
What feature are you requesting?

A React control that takes the endpoint, userid, token and displays the previous conversations\threadid that that users have participated.

What would be the benefit of adding this feature?

This way "Authenticated Customers" could see their chat/conversations history instead of only creating a new thread.

Thanks!

**Comment by alkwa-msft** [comment]
At this time we are focusing on building components that customers want to use in a majority of cases. We are open to proposals about features that people may want and are happy to also provide review if anyone would want to submit any components as well. 

Perhaps you can create something and share it with us? We would love to see what you are envisioning with this type of thread list component? Perhaps we can move this issue to be more a discussion?

Going to close now but feel free to re-open and share any new details as to how we can help you out?
