### ISSUE TITLE
Allow to remove default actions on MessageThread component

### ISSUE THREAD

**Issue by McFoggy** [Azure/communication-ui-library#2670]
I hesitated in creating an issue instead of a RFE.
As far as I understood the API, today the component is not usable in our context since we cannot disable several unwanted actions.

**What feature are you requesting?**

I'd like to disable actions on chat messages when using `MessageThread` component `@azure/communication-react` 

**What would be the benefit of adding this feature?**

To not pollute the UI with unexpected /unused features.

**What solution would be ideal for you?**

Have an API to disable actions or even better an API to register actions instead of the standard ones.
If no actions are registered then nothing is shown.

**What alternatives have you considered?**

Could use directly `@fluentui/react-northstar` but that would mean code again a lot of things instead of using `MessageThread` component.

**Is there any additional information for your request?**

no

**Attach screenshots or images add detail to your request:**

![image](https://user-images.githubusercontent.com/1119660/214110606-3685c87c-ca7b-4143-b8b3-cadd9a3ca786.png)

**Comment by carocao-msft** [comment]
Hi, you can use the prop disableEditing to remove the flyout menu, just need to pass disableEditing={true} to messageThread component. Let me know if this resolves your issue!
