### ISSUE TITLE
Chrome does not display the other party's video

### ISSUE THREAD

**Issue by strawhat-shima** [Azure/communication-ui-library#2676]
I found out today. In a sample program using CallWithChatComposite, When I join a group call on Chrome, the other party's video is not displayed / Screen sharing is still "displaying the screen" and it is not displayed even after a long time. When I join a group call on Edge, I can see the other person's video and see the other person's screen. What are the possible causes?

the Calling project's package.json

  "dependencies": {
    "@azure/communication-calling": "1.4.4",
    "@azure/communication-chat": "1.2.0",
    "@azure/communication-common": "2.1.0",
    "@azure/communication-identity": "1.2.0",
    "@azure/communication-react": "1.3.1",
    "@azure/core-http": "1.2.6",
    "@babel/preset-react": "^7.16.7",
    "@fluentui/react": "~8.67.3",
    "@fluentui/react-icons": "~1.1.145",
    "@webpack-cli/serve": "^1.6.1",
    "jquery": "^3.6.0",
    "merge": "^2.1.1",
    "mobile-detect": "~1.4.5",
    "react": "~16.14.0",
    "react-dom": "16.14.0",
    "react-router-dom": "^5.3.1",
    "reactstrap": "^8.10.1",
    "reselect": "~4.1.5",
    "uuid": "^8.3.2"
  },

**Comment by alkwa-msft** [comment]
Thanks for sharing this issue. This should not be happening. We can continue to look into it but if we have a call ID we can use to reference then we can look further into what we are detecting in the call. 

- Is there any additional repo steps?
-  Are they 100% consistent?

**Comment by strawhat-shima** [comment]
When I checked the phenomenon, the call ID was as follows.
groupid: 62ce3378-3c2e-48f7-89c7-873211bcdc90
threadid: 19:2M-GQXd-FTHddvQQ_tHwN1DNPZC_Ha7WRuO55_KdEUU1@thread.v2

No special steps. It was discovered when the two of us were testing the call.

**Comment by alkwa-msft** [comment]
Was this a 100% repro?

In order to get the call Id you need to get the id property on the call object. We also surface the call Id in the adapter

**Comment by strawhat-shima** [comment]
Not 100%
In this morning test, Neither PC-1 nor PC-2 showed each other's video.
In this afternoon's test, both showed video.
However, PC-3 does not display the video of PC-1,2.

**Comment by carocao-msft** [comment]
Thanks for providing all those info! We are looking into this issue

**Comment by levimiller-qhrtech** [comment]
Any updates on this? We seem to also be running into the same issue intermittently:

**Comment by levimiller-qhrtech** [comment]
From further testing, this is possibly related to the 109.0.5414.75 (ish) chrome build.

**Comment by alkwa-msft** [comment]
@levimiller-qhrtech 
@strawhat-shima 

can we confirm if this issue is still occurring? After having chatted with my colleagues in the calling team. There was a detected disruption on chrome 109. However after Jan 25th we noticed a drop in these types of intermittent issues.

**Comment by strawhat-shima** [comment]
Thank you for your explanation.
The last time I checked the problem was on the morning of January 26th (Japan time), and there seems to be no problem after that.

**Comment by Andre-Bertram** [comment]
@alkwa-msft This appears to still being an ongoing issue. As a work around we're having Chrome versions update to the latest as it doesn't break on versions greater 109.0.5414.74/75/87 (give and take)

**Comment by edwardlee-msft** [comment]
Thank you for confirming that the issue was resolved with your work around. 
This issue will now be closed, we recommend users update to the latest chrome version or at least avoid using versions 109.0.5414.74/75/87.
