### ISSUE TITLE
Missing property for message bubble alignment in ChatComposite

### ISSUE THREAD

**Issue by fpereiramapfrepr** [Azure/communication-ui-library#2683]
When using the ChatComposite there is not option documented to align my messages to the right.

Looking for something like :
```
<ChatComposite
  myMessageAlignment='right'
  // other props
/>

```
![ChatMessageExamples](https://user-images.githubusercontent.com/100782509/214948749-723f1cf2-e650-4484-9956-746f3895a8f0.png)

Currently all messages are being aligned to the left. 

Thanks

**Comment by carocao-msft** [comment]
Hi Thanks for raising this issue, currently our composite doesn't support these styling changes, if you prefer more customization, please take a look at our chat components! Let me know if this solves your question :)

**Comment by fpereiramapfrepr** [comment]
Hi,

The weird thing is that when I run the  Chat Hero app locally I can see the bubble message  alignments implemented correctly.

![ChatBubbles](https://user-images.githubusercontent.com/100782509/215093294-7a413c43-75d5-4168-a4d6-3a81a687ac82.png)

Is it the ThemeProvider that makes this behaviour changes on the chat ?

On the ChatScreen code I see:

```
<ChatComposite
            adapter={adapter}
            fluentTheme={currentTheme.theme}
            options={{
              autoFocus: 'sendBoxTextField'
            }}
            onFetchAvatarPersonaData={onFetchAvatarPersonaData}
          />
```

Thanks for the help you can give

**Comment by carocao-msft** [comment]
Hi, the messages sent by yourself should align on the right, and messages from others should align on the left. Do you mind sharing how you are currently implementing the chat composite, it will help us to understand better what's going on here

**Comment by jorgecolon413** [comment]
We are working on the same app and this is our implementation of the ``ChatComposite`` : 

```
const ChatComponent = (props) => {
    // A well-formed token is required to initialize the chat and calling adapters.    

    const { currentTheme } = { name: 'Light', theme: lightTheme };

    const credential = useMemo(() => {
        try {
            return new AzureCommunicationTokenCredential(props.userToken);
        } catch {
            console.error('Failed to construct token credential');
            return undefined;
        }

    }, [props.userToken]);

    // Memoize arguments to `useAzureCommunicationChatAdapter` so that
    // a new adapter is only created when an argument change              
    const chatAdapterArgs = useMemo(
        () => ({
            endpoint: props.endpoint,
            userId: props.userId,
            displayName: props.displayName,
            credential,
            threadId: props.threadId
        }),
        [props.endpoint, props.userId, props.displayName, credential, props.threadId]
    );

    const chatAdapter = useAzureCommunicationChatAdapter(chatAdapterArgs);

    if (!!chatAdapter) {
        chatAdapter.loadPreviousChatMessages(20);
        return (
            <div style={{ height: '80vh', display: 'flex' }}>
                <div style={containerStyle}>
                    <ChatComposite adapter={chatAdapter}
                        fluentTheme={lightTheme} options={{ autoFocus: 'sendBoxTextField' }} />
                </div>
            </div>
        );
    }
    if (credential === undefined) {
        return <h3>Failed to construct credential. Provided token is malformed.</h3>;
    }
    return <h3>Initializing...</h3>;
}

const containerStyle = {
    margin: '0.5rem',
    width: '55vw'
};


export default ChatComponent;

```
Here is a video representation of the issue: 

![chrome-capture-2023-0-27](https://user-images.githubusercontent.com/58268872/215166710-c343543b-df5f-448f-a07c-8cecdea0a2f9.gif)

Thanks for your time!

**Comment by carocao-msft** [comment]
Hey just want to verify did you get the lightTheme from @azure/communication-react? Also do you have any styling changes outside of the chat components that might be affecting how the chat screen is rendering? 
Just a shot in the dark, what happens if you remove fluentTheme={lightTheme} ?

**Comment by jorgecolon413** [comment]
Here are my dependencies: 
```
    "@azure/communication-calling": "^1.4.4",
    "@azure/communication-chat": "^1.2.0",
    "@azure/communication-react": "^1.4.1",
    "@azure/msal-browser": "^2.15.0",
    "@azure/msal-react": "^1.0.1",
    "@fluentui/react": "^8.104.7",
``` 
But we manage to get our messages to display in the right side of the chat thread by making sure of using the fromFlatCommunicationIdentifier() function when creating the chatAdpater object:

```
 const chatAdapterArgs = useMemo(
        () => ({
            endpoint: props.endpoint,
            userId: fromFlatCommunicationIdentifier(props.userId),
            displayName: props.displayName,
            credential,
            threadId: props.threadId
        }),
        [props.endpoint, props.userId, props.displayName, credential, props.threadId]
    );
```

Here is how it looks like:
![chrome-capture-2023-0-30](https://user-images.githubusercontent.com/58268872/215481005-3b79c101-1ce8-41e1-bd7b-e6534ebb5b70.gif)

Thanks for your feedback!

**Comment by carocao-msft** [comment]
Hi I'm glad now it's working as expected! Yes you need to pass the userid through fromFlatCommunicationIdentifier before passing it to the adapter, because the adapter takes a CommunicationIdentifierKind instead of a string. 
Are the remote participant's messages aligned to the left?

**Comment by dmceachernmsft** [comment]
Seems there was a resolution here so closing 😊 feel free to reopen if problem arises again.
