### ISSUE TITLE
Chat Composite call returns Invalid Hook call error in Teams Toolkit project

### ISSUE THREAD

**Issue by AlbertoPerez8** [Azure/communication-ui-library#2685]
I am running a Teams Toolkit project to create a Teams project and planned to use the Chat Composite component to add chat functionality. But I'm running into the issue that the component returns the following error: 
"Uncaught (in promise) Error: Provided userId is invalid. Please provide valid identifier object."

I'm validating the necessary parameters using the Azure github component webapp and do not run into any other issues.

The userIds is are ACS issued identifier created through the use of Azure functions and they return valid tokens and chat thread IDs when using ACS API calls directly.

These are the packages currently installed for ACS and react:
        "@azure/abort-controller": "^1.0.0",
        "@azure/communication-calling": "1.4.4",
        "@azure/communication-chat": ">=1.2.0",
        "@azure/communication-common": "2.0.0",
        "@azure/communication-identity": "~1.1.0",
        "@azure/communication-react": "1.5.0",
        "@fluentui/react-northstar": "^0.62.0",
        "@microsoft/teams-js": "^2.2.0",
        "@microsoft/teamsfx": "^2.0.0",
        "@microsoft/teamsfx-react": "^2.0.0",
        "axios": "^0.21.1",
        "react": "^16.14.0",
        "react-dom": "^16.14.0",
        "react-router-dom": "^5.1.2",
        "react-scripts": "^5.0.1"

**Comment by carocao-msft** [comment]
Hi, Thanks for raising this issue, can you share more detail regarding what userid you are currently using? Are you using an ACS userid?

**Comment by AlbertoPerez8** [comment]
I've edited the issue due to posting it before finishing to type, the userid is indeed an ACS userid, and is confirmed to be a functional one.

**Comment by carocao-msft** [comment]
Thanks for clarifying! We are looking into this :)

**Comment by carocao-msft** [comment]
Hi is it possible for you to share some code samples regarding how are you using the composites and setting up the adapters? Thanks in advance!

**Comment by AlbertoPerez8** [comment]
![image](https://user-images.githubusercontent.com/36648131/215166417-b7e70999-e130-4ddc-bd15-a4dd1171ac5d.png)
Here is a static tab that would hold the Composite



![image](https://user-images.githubusercontent.com/36648131/215166699-171cc500-b7ed-4ab8-a1f5-117563a1bb42.png)
This is how some of the data is instantiated and retrieved dynamically for use. 

![image](https://user-images.githubusercontent.com/36648131/215166865-2191242e-c468-43bb-a019-3df6d8ada36a.png)
Rendering of the Composite component. The USER_ID, ENDPOINT_URL, ID (thread id), and TOKEN are currently hardcoded values but taken from the ACS API.


And here is the component code as is:
`import { AzureCommunicationTokenCredential } from '@azure/communication-common';
import {
    ChatComposite,
    useAzureCommunicationChatAdapter,
    lightTheme,
} from '@azure/communication-react';
import React, { useMemo } from 'react';

const ChatContainer = (props) => {

    const credential = useMemo(() => {
        try {
            return new AzureCommunicationTokenCredential(props.userToken);
        } catch {
            console.error('Failed to construct token credential');
            return undefined;
        }
    }, [props.userToken]);


    const chatAdapterArgs = useMemo(
        () => ({
            endpoint: props.endpoint,
            userId: props.userId,
            displayName: props.displayName,
            credential,
            threadId: props.threadId
        }),
        [props.endpoint, props.userId, props.displayName, credential, props.threadId]
    );

    const chatAdapter = useAzureCommunicationChatAdapter(chatAdapterArgs);


    if (chatAdapter) {
        chatAdapter.loadPreviousChatMessages(20);
        return (
            <div style={{ display: 'flex' }}>
                <div style={containerStyle}>
                    <ChatComposite
                        adapter={chatAdapter}
                        fluentTheme={lightTheme}
                        options={{ autoFocus: 'sendBoxTextField' }} />
                </div>
            </div>
        );
    }
    if (credential === undefined) {
        return <h3>Failed to construct credential. Provided token is malformed.</h3>;
    }
    return <h3>Initializing...</h3>;
}

const containerStyle = {
    margin: '0.5rem',
    width: '55vw'
};


export default ChatContainer;`

**Comment by carocao-msft** [comment]
Hi, for user id did you convert it to a CommunicationUserIdentifier using the following code? 
const userId = useMemo(
    () => fromFlatCommunicationIdentifier(userid) as CommunicationUserIdentifier,
    [userid]
  );

**Comment by AlbertoPerez8** [comment]
I haven't but my code base runs on javascript, not typescript. Also as it stands the userID is stored as a string constant.

**Comment by AlbertoPerez8** [comment]
![image](https://user-images.githubusercontent.com/36648131/215184125-2bcb1472-882f-4400-b308-8e819552ece7.png)
So I've changed the snippet a little to avoid getting an error in VS code, after recieving the user id I check to see if after the useMemo the user id registers as a CommunicationUserIdentifier. It prints as true and  I'm no longer getting the invalid userID error, but there is no chat being rendered now.

**Comment by carocao-msft** [comment]
Are you getting any console errors? And is your chatAdapter successfully initialized?

**Comment by carocao-msft** [comment]
You can also try using this function to check if the adapter is being constructed correctly 

const adapterAfterCreate = useCallback(
    async (adapter: ChatAdapter): Promise<ChatAdapter> => {
      // print out adapter
      return adapter;
    },
    []
  );
  const adapter = useAzureCommunicationChatAdapter(adapterArgs, adapterAfterCreate);
 You can see an example of this in chatscreen file in communication service web chat hero https://github.com/Azure-Samples/communication-services-web-chat-hero

**Comment by mgamis-msft** [comment]
@AlbertoPerez8 just to be sure, could you check your DOM tree in the browser developer tools if the ChatComposite is there? The div wrapping the composite might not have a height and width.

**Comment by AlbertoPerez8** [comment]
The problem was resolved, the userId was formatted correctly as a CommunicationUserIdentifier id, and the empty render was fixed removing some stylings and root div tags holding the composite component. Thanks a lot for the help.
