### ISSUE TITLE
Add Functionality for Background Blur and Custom Backgrounds for Calling

### ISSUE THREAD

**Issue by grathore1999** [Azure/communication-ui-library#2746]
**What feature are you requesting?**

**What would be the benefit of adding this feature?**

**What solution would be ideal for you?**

**What alternatives have you considered?**

**Is there any additional information for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by grathore1999** [comment]
Refer to this blog :- https://techcommunity.microsoft.com/t5/azure-communication-services/azure-communication-services-february-2023-feature-updates/ba-p/3737486

**Comment by alkwa-msft** [comment]
@grathore1999  we are currently in development for this feature. It will be slated for public preview sometime after March.

I am curious are there any specific features or use cases around this feature you would like to share with us? We often like to hear about how customers want to use or plan to use upcoming features we can ensure that what we are building can work for those use cases as well.

**Comment by grathore1999** [comment]
Thanks @alkwa-msft  It was helpful to have this information shared with us. Currently, we want the same functionality as I mentioned above, and our new feature request is to be able to share files between ACS Call and Microsoft Teams.

**Comment by alkwa-msft** [comment]
@grathore1999 Sharing files between an ACS Call and Microsoft Teams are also in active development at this time.

**Comment by alkwa-msft** [comment]
(response on blur backgrounds on mobile web platforms)
https://github.com/Azure/communication-ui-library/issues/3033#issuecomment-1538484810

**Comment by mgamis-msft** [comment]
Closing this issue because Background Blur and Custom Backgrounds is now supported in [1.8.0-beta.1] https://www.npmjs.com/package/@azure/communication-react/v/1.8.0-beta.1 and [1.8.0](https://www.npmjs.com/package/@azure/communication-react/v/1.8.0). To learn more reference our storybook documents [here](https://azure.github.io/communication-ui-library/?path=/docs/videoeffects--page)
