### ISSUE TITLE
on "chatMessageReceived" event listener values

### ISSUE THREAD

**Issue by luke-guider** [Azure/communication-ui-library#2782]
**Describe the bug; what happened?**
- When creating a StatefulChatClient using createStatefulChatClient, and setting a "chatMessageReceived" event the returned listener values for recipient and sender are the same. The values are being set to the userid being used to create the StatefulChatClient.

**What behavior did you expect?**
- recipient and sender to be different when receiving a message.

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version: [1.5.0]

**Comment by edwardlee-msft** [comment]
Thank you for submitting your issue. We will look into it soon and get back to you shortly after :).

**Comment by jimchou-dev** [comment]
Hi @luke-guider, without more details here is a bit more detail on how "chatMessageReceived" works. Let's say there is 2 users in the same chat thread, eg. UserA (userId_A, token_A) and UserB(userId_B, token_B). They both use createStatefulChatClient with associated user id and token credential to create StatefulChatClient and listen for "chatMessageReceived" event.When UserA sends a message (content as "Hello") using chatThreadClient (from StatefulChatClient for UserA), the event "chatMessageReceived" for the message "Hello" will be received by both UserA and UserB.- UserA will receive the message with sender being UserA (themsvelves)- UserB will receive the message with sender being UserAIf this does not answer your question, can you please provide more detail on the scenario?
