### ISSUE TITLE
Local Video Stream goes Off when a new user join the call

### ISSUE THREAD

**Issue by durjanh** [Azure/communication-ui-library#2797]
**Describe the bug; what happened?**

When a new user joins an existing call and the Organiser teams video is on.
Other user local video stream goes off and comes up with the error message on the console I shared.
Remember Teams Organiser still can see the user. It's just on a client video stream that disappeared. 

If the Teams Organiser video is off then it works fine with no errors.

**What are the steps to reproduce the issue?**
Start the call with the teams user and 2nd user join the call. Make sure the Teams user's video is ON.

**What behavior did you expect?**
The local video stream should not go off

**If applicable, provide screenshots:**
![Local videoDisposed](https://user-images.githubusercontent.com/7289173/222788747-084c2617-2d0d-4739-a994-30366ee8e153.PNG)

**In what environ
Test

ment did you see the issue?**

- `@azure/communication-react` npm package version 1.3.1
- `@azure/communication-calling` npm package version 1.4.4
- `@azure/communication-chat` npm package version 1.2.0

- OS & Device: Windows
- Browser: Google Chrome,
- Browser Version: 110.0.5481.178

**Is there any additional information?**
![image](https://user-images.githubusercontent.com/7289173/222789947-5d003130-bac2-420d-9e52-cf919fc4ed40.png)

![image](https://user-images.githubusercontent.com/7289173/222789532-93b326cf-1544-4c0d-9985-88438174e25a.png)

**Comment by edwardlee-msft** [comment]
HI @durjanh,

Thank you for filing this issue.
This was fixed with version 1.4.1 in PR https://github.com/Azure/communication-ui-library/pull/2558. 
We recommend you use communication-react version 1.4.1 or greater

**Comment by durjanh** [comment]
Hi @edwardlee-msft ,

Hoo cool, thanks @edwardlee-msft . I will try and let you know.

**Comment by edwardlee-msft** [comment]
Have you gotten to try out a version > 1.4.1 @durjanh?
