### ISSUE TITLE
Failing to connect to camera with 1.5.1-beta.1

### ISSUE THREAD

**Issue by koren-qualifico** [Azure/communication-ui-library#2801]
I have implemented this example: https://azure.github.io/communication-ui-library/?path=/docs/communicationasteamsuser--page
And trying to connect to a Teams meeting with a Teams user. It seams as if the client fails to connect to the camera, even though permissions are granted. The video UI remains disabled. 
Console repeatedly outputs the following:
ECS - Config fetch complete
​ ECS - Delaying User config fetch until we have a valid SkypeToken
​ ECS - Config fetch complete

**Comment by mgamis-msft** [comment]
Hi @koren-qualifico, thank you for filing this issue. I will see if I can reproduce this issue.

**Comment by koren-qualifico** [comment]
> Hi @koren-qualifico, thank you for filing this issue. I will see if I can reproduce this issue.

Did you manage to repro? I am using the Graph api to generate a teams meeting link. The browser is Chrome, but I also got the same result in Edge. 
I should also note that I think camera should not be mandatory for a meeting. A meeting could just have a mic activated.

**Comment by mgamis-msft** [comment]
Hi @koren-qualifico, yes I was able to reproduce what you are seeing. My camera light is turning on and off so it seems there is some kind permission request loop going on. I will ask my colleague who worked on this code. Sorry for the delay.

**Comment by mgamis-msft** [comment]
Hi @koren-qualifico, our sample code was not working as intended and will be updated in https://azure.github.io/communication-ui-library/?path=/docs/communicationasteamsuser--page.
The fix is essentially to change the code in the snippet from:
```
  const adapter = useTeamsCallAdapter(
    {
      userId: props.userId,
      credential,
      locator: props.meetingUrl
        ? {
            meetingLink: props.meetingUrl
          }
        : undefined,
      options
    },
    undefined,
    leaveCall
  );
  ```
  to
  ```
    const teamsCallAdapterArgs = useMemo(
    () => ({
      userId: props.userId,
      credential,
      locator: props.meetingUrl
        ? {
            meetingLink: props.meetingUrl
          }
        : undefined,
      options
    }),
    [props.userId, credential]
  );

  const adapter = useTeamsCallAdapter(teamsCallAdapterArgs, undefined, leaveCall);
  ```
  Thank you for bringing this to our attention. I hope it helps.
