### ISSUE TITLE
Uploading files from MS Teams

### ISSUE THREAD

**Issue by bluemeanie76** [Azure/communication-ui-library#2809]
**Describe the bug; what happened?**
When uploading a file in MS Teams the ChatClient contains no information.

**What are the steps to reproduce the issue?**
Connect to a chat via MS teams and send a file.

**What behavior did you expect?**
To see a link to download a  file.

**If applicable, provide screenshots:**

File uploaded via Teams:
![image](https://user-images.githubusercontent.com/6150311/224304870-cc3c1cd6-e06b-4961-964c-cb664ba75c79.png)

Result in chat:
![image](https://user-images.githubusercontent.com/6150311/224305011-bec9e711-2645-43d1-9d7e-2d673c832d12.png)

Chat Data
![image](https://user-images.githubusercontent.com/6150311/224306577-8ccc15cd-29a8-4631-ad15-3bd5ec72f4bb.png)

**In what environment did you see the issue?**
-    "@azure/communication-calling": "^1.4.4",
-    "@azure/communication-chat": "^1.2.0",
-    "@azure/communication-common": "^2.0.0",
-    "@azure/communication-react": "^1.4.1",

**Is there any additional information?**

**Comment by JoshuaLai** [comment]
Thanks @bluemeanie76 for the feedback. I have created a git issue on the underlying chatsdk to investigate how to expose functionality to expose the url. 
You can follow the git issue here:  https://github.com/Azure/azure-sdk-for-js/issues/25210

**Comment by JoshuaLai** [comment]
@bluemeanie76 Just a quick update the changes needed on the SDK side has just been completed. We will let you know when the changes are propagated up to the UI library side.

**Comment by vhuseinova-msft** [comment]
Hello @bluemeanie76!
We have released [1.7.0-beta.1](https://github.com/Azure/communication-ui-library/blob/main/packages/communication-react/CHANGELOG.beta.md#170-beta1) to address this enhancement request. Therefore, we are closing this issue. Please check out the release and[ File Sharing storybook](https://azure.github.io/communication-ui-library/?path=/docs/examples-teamsinterop-filesharing--file-sharing) page for more details, and let us know if you have any questions.
