### ISSUE TITLE
CallComposite locator missing RoomId parameter

### ISSUE THREAD

**Issue by rdemace** [Azure/communication-ui-library#2811]
Hi,

following the given documentation i cannot properly understand the concept behind the CallComposite component which requires an adapter->locator (CallAdapterLocator) that needs a meetingLink or a groupId.

Both of this parameter I don't even know where i should get those.

I'm using a backend api in .NET 7 and a frontend in React.

Thank you in advance.

**Comment by mgamis-msft** [comment]
Hi @rdemace ,
The CallAdapter is provided to the CallComposite to handle the backend functionality of a call. The CallAdapter is created using the [createAzureCommunicationCallAdapter function](https://azure.github.io/communication-ui-library/?path=/docs/composite-adapters--page#createazurecommunicationcalladapter). One of the arguments for this function is the locator which can be a groupId or meetingLink in our stable version [1.5.0](https://www.npmjs.com/package/@azure/communication-react/v/1.5.0). The beta version can also have other types of locator which includes roomId (https://www.npmjs.com/package/@azure/communication-react/v/1.5.1-beta.1) but is missing from our documentation. Thank you for letting us know.
The groupId is any uuid and the meetingLink is obtained from Teams call invite link. For a room id you will need to use the Rooms Client. Here is link to a quickstart of Rooms Client: https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/rooms/get-started-rooms?tabs=windows&pivots=programming-language-javascript.
Hopefully that helps :)

**Comment by rdemace** [comment]
Thank you very much, that was very helpful.
That actually makes sense because the version of nuget package for rooms is also in beta.
Thank you again.
