### ISSUE TITLE
Intermittent issue when joining a Teams meeting using CallWithChat 

### ISSUE THREAD

**Issue by rsavioli** [Azure/communication-ui-library#2852]
**Describe the bug; what happened?**
It is an intermittent issue when I try to join an existing teams meeting.
After the configuration screen, when clicking on join the meeting, it drops.

**What are the steps to reproduce the issue?**
Sometimes, on the first attempt to enter a meeting, the error is displayed, but sometimes it takes time for it to happen again.
If the organizer leaves the meeting, the error is no longer displayed.

**What behavior did you expect?**

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/1143033/228362240-a089eb94-9ba0-40de-a663-f45acfbdef19.png)

**In what environment did you see the issue?**

- `@azure/communication-react` 1.5.0
- `@azure/communication-calling` 1.11.1
- `@azure/communication-chat` 1.2.0

- OS & Device: Windows on PC
- Browser: Microsoft Edge
- Browser Version: 111.0.1661.54 (Official build) (64-bit)

**Is there any additional information?**

**Comment by dmceachernmsft** [comment]
Hi! thanks for filing the issue with us @rsavioli! I will take a look into this. for clarity, if the organizer leaves the meeting the user is then able to join the meeting and land in the lobby screen? or just the error goes away in the console?

**Comment by rsavioli** [comment]
Hi @dmceachernmsft, Thanks for the quick availability.

If the organizer leaves, it is possible to enter the lobby and the console error disappears.

Adapter code snippet:

    const CallScreen = (props: CallScreenProps): JSX.Element => {
      const localize = props.t;
      const {
          token,
          userId,
          displayName,
          endpoint,
          locator,
      } = props;

      const callIdRef = useRef<string>();
      const { currentTheme, currentRtl } = useSwitchableFluentTheme();
      const isMobileSession = useIsMobile();
      const credential = useMemo(
          () => createAutoRefreshingCredential(toFlatCommunicationIdentifier(userId), token),
          [userId, token]
      );

      const afterAdapterCreate = useCallback(
          async (adapter: CallWithChatAdapter): Promise<CallWithChatAdapter> => {
              adapter.on('callError', (e) => {
                  // Error is already acted upon by the Call composite, but the surrounding application could
                  // add top-level error handling logic here (e.g. reporting telemetry).
                  console.log('Adapter error event:', e);
              });
              adapter.on('chatError', (e) => {
                  // Error is already acted upon by the Chat composite, but the surrounding application could
                  // add top-level error handling logic here (e.g. reporting telemetry).
                  console.log('Adapter error event:', e);
              });
              adapter.on('callEnded', (e: CallAdapterCallEndedEvent) => {
                  props.callEnded();
              });
              adapter.on('callParticipantsLeft', (e) => {
                  var adapterState = adapter.getState();
  
                  if (_.isEmpty(adapterState?.call?.remoteParticipants)) {
                      adapter.leaveCall();
                      props.callEnded();
                  } 
              })
              adapter.onStateChange(async (state: CallWithChatAdapterState) => {
                  const currentState = convertPageStateToString(state);
  
                  if (currentState == "call" && state?.call?.state == "Connected") {
                      props.callStarted();
                  }
  
                  if (state?.call?.id && callIdRef.current !== state?.call?.id) {
                      callIdRef.current = state?.call?.id;
                      console.log(`Call Id: ${callIdRef.current}`);
                  }
              });
              return adapter;
          },
          [callIdRef]
      );
  
      const adapter = useAzureCommunicationCallWithChatAdapter(
          {
              userId,
              displayName,
              credential,
              endpoint,
              locator,
          },
          afterAdapterCreate
      );
  
      // Dispose of the adapter in the window's before unload event.
      // This ensures the service knows the user intentionally left the call if the user
      // closed the browser tab during an active call.
      useEffect(() => {
          const disposeAdapter = (): void => adapter?.dispose();
          window.addEventListener('beforeunload', disposeAdapter);
          return () => window.removeEventListener('beforeunload', disposeAdapter);
      }, [adapter]);
  
      if (!adapter) {
          return (
              <div className="loader">
                  <Loader size="small" label={localize("Loading")} />
              </div>
          );
      }
  
      const compositeOptions: CallWithChatCompositeOptions = {
          callControls: {
              chatButton: true,
              peopleButton: false,
              displayType: "compact"
          }
      }
  
      return (
          <CallWithChatComposite
              adapter={adapter}
              fluentTheme={currentTheme.theme}
              rtl={currentRtl}
              joinInvitationURL={window.location.href}
              formFactor={isMobileSession? 'mobile' : 'desktop'}
              options={compositeOptions}
          />
      )};

**Comment by dmceachernmsft** [comment]
Excellent! thanks for the snippet. I will do a little digging and provide a update to you shortly!

**Comment by dmceachernmsft** [comment]
Hi @rsavioli I am unable to repro on my side with the same versions. could you please if possible send along a call-id or two when this happens? the error that you are seeing seems to have something to do with our services and will check in with them about what is going on!

**Comment by rsavioli** [comment]
@dmceachernmsft as requested, follow the call-id with error:

22633f68-75b4-4f48-857e-a6aa7d06556d
6cd70d41-3409-4a0d-ae91-154e2b624054

**Comment by dmceachernmsft** [comment]
Excellent thanks for the new information! is it still intermittent or is it completely blocking?

**Comment by rsavioli** [comment]
@dmceachernmsft intermittent, i got an error just now

Call-Id: f2750d21-8496-4ddb-b6ae-3298f4c7f7ba
communicationUserId: 8:acs:14e860d3-1b9e-44f9-8149-584a4c00ce4f_00000017-d379-f71d-b4f1-9c3a0d00021f

**Comment by rsavioli** [comment]
@dmceachernmsft Contributing.. 
When I'm trying to enter the lobby, analyzing the requests I see a specific error in this call:

`https://latm-noam.flightproxy.teams.microsoft.com/api/v2/ep/broker-brso-05.broker.skype.com/api/v1/subscribe/54dd9a0b-e3eb-4b3a-a6e8-f3237a45d47e/0?i=5`

![image](https://user-images.githubusercontent.com/1143033/228922749-c92ba528-30e9-43c0-be0b-5db3ceef0735.png)

**Comment by dmceachernmsft** [comment]
Thanks for the extra info! will update when we know something. 😊

**Comment by dmceachernmsft** [comment]
@rsavioli a update for you. the issue on our service side has been found. we should see a fix deployed next week. was a misconfiguration somewhere so it is intermittent because sometimes you are connecting to the misconfigured server. I will continue to monitor the issue filed on our service and close this issue when the fix is deployed. 

Thanks for all the information to help track this one down!

**Comment by rsavioli** [comment]
@dmceachernmsft any update?

thanks in advance.

**Comment by alkwa-msft** [comment]
@rsavioli  we have rolled out a backend change which should address the issue. Thank you for patience.  Please reach out or feel free to re-open the issue should you see it again.
