### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [Azure/communication-ui-library#2903]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by JamesBurnside** [comment]
@igibek thank you for both finding the vulnerability and aiming to disclose privately. We have enabled the `Private vulnerability reporting` and will listen out for your report - I will keep this issue open until then.

**Comment by emlynmac** [comment]
@igibek Just wanting to follow up here. I'll be closing off this ticket if there's no response, but leaving the private reporting open.
