### ISSUE TITLE
Migrate Fluent UI Dependencies to @fluentui/react-components (v9)

### ISSUE THREAD

**Issue by vhuseinova-msft** [Azure/communication-ui-library#2924]
**What feature are you requesting?**
Currently, @azure/communication-react depends on 2 different Fluent UI packages:

1. @fluentui/react (v8)
2. @fluentui/react-northstar

@fluentui/react-components (v9) is the new component library from FluentUI that should be used in the future. This issue will track migration to the new dependency.

**What would be the benefit of adding this feature?**

- Ability to receive latest updates/enhancements from FluentUI components
- Fixes for some issues existed in @fluentui/react-northstar

**Comment by emlynmac** [comment]
Internally we have removed fluent NorthStar components and are mostly using fluent 8. We have some fluent 9 components where they are not available as fluent 8.
 
Our current API contains direct dependencies on fluent 8 structures and moving to fluent 9 would require breaking the API.
It is highly likely that in subsequent versions of the the UI library, we will not pass-through underlying dependencies so as to avoid the necessity of breaking changes.
 
Fluent 9 can be used freely with the current version of the library and the removal of Fluent NorthStar has reduced the bundle size.
