### ISSUE TITLE
Sharing button freezes frame

### ISSUE THREAD

**Issue by koren-qualifico** [Azure/communication-ui-library#2927]
In the 1.5.1-beta.1 version, when clicking on "Share screen" button and then canceling sharing, the other buttons in the tool bar freeze.

Is it possible to hide the "Share" button? 
When is a new stable version expected?

**Comment by alkwa-msft** [comment]
You can show,hide, and disable buttons in the callControl bars through our CallComposite options

options = { 
	callControls: { screenShareButton: false }
}

![image](https://user-images.githubusercontent.com/79329532/231826944-d379cdb5-eee7-4bab-bc87-273d45e29014.png)

The team is looking to make a stable release end of May.
