### ISSUE TITLE
In the Azure/communication-ui-library, Can background blur be enabled on mobile devices? If so, when and how?

### ISSUE THREAD

**Issue by grathore1999** [Azure/communication-ui-library#3033]
**What feature are you requesting?**

**What would be the benefit of adding this feature?**

**What solution would be ideal for you?**

**What alternatives have you considered?**

**Is there any additional information for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by alkwa-msft** [comment]
@grathore1999 my apologies if we hadn't responded on the other issue where this was raised.

We are currently revisiting when we can support blur background  for android (chrome ) and iOS (safari). At this time it is currently slated early CY24. If you have any scenarios where having this feature sooner, feel free to share and we can see if we can help prioritize this feature.

**Comment by grathore1999** [comment]
Dear  Alkwa,

Thank you for your email update on the status of the blur background feature for Android (Chrome) and iOS (Safari). I appreciate the effort your team is putting into revisiting the timeline for this feature.

While I understand that the feature is currently slated for early CY24, I would like to inquire if there is any possibility of an earlier release. As a [insert your profession or reason for using the feature], I believe that having this feature sooner would significantly improve my productivity and enhance my user experience.

I would greatly appreciate it if you could share any information on the possibility of an earlier release or if there are any scenarios that would help prioritize this feature. Please let me know if you need any further details from my end.

Thank you for your attention to this matter.

Best regards,
Gagan Rathore
________________________________

**Comment by alkwa-msft** [comment]
Sorry just found I didn't respond to this one while going through our Github issue cleanup.

The functionality at this time is based on a dependency team right now that is responsible for the background blur feature.

**Comment by mgamis-msft** [comment]
Closing this issue due to staleness. Please file another issue if this still persists with the appropriate details and version
