### ISSUE TITLE
Stateful Client Components from demo not initiating correctly 

### ISSUE THREAD

**Issue by jorgecolon413** [Azure/communication-ui-library#3037]
I currently have a ReactJS app that uses a CallComponent, which uses an ID to make a call to an ACS user (client on port 3000 in the examples). Additionally, I have another ReactJS app that uses stateful clients to receive incoming calls (client on port 3001 in the examples). The problem is that when I answer the call, the stateful client doesn't seem to correctly instantiate the components for the call itself. These code snippets were written following the examples provided in the UI Library Storybook.

Here are  some examples of how the interaction looks:

![f71218e4-abd9-4591-af70-e35dc31ba05b](https://github.com/Azure/communication-ui-library/assets/58268872/3550b5be-d0d6-456d-9e71-08e0534b69ed)

![2db1382a-3177-4bc1-8e30-2cc368963bcc](https://github.com/Azure/communication-ui-library/assets/58268872/fd78e3c2-5457-4031-939d-f0e4d859cd3f)

Here is the component that I use to make the call:
```
import {
  AzureCommunicationTokenCredential,
  CommunicationUserIdentifier,
} from '@azure/communication-common';
import {
  CallComposite,
  fromFlatCommunicationIdentifier,
  useAzureCommunicationCallAdapter,
} from '@azure/communication-react';
import React, { useMemo } from 'react';


type CallMultipleProps = {
  userId: string;
  userToken: string;
  displayName: string;
};

const ACS_USER_IDS = [
  '<ACS User Id>',
];

export const CallMultiple = (props: CallMultipleProps): JSX.Element => {
  const { userId, userToken, displayName } = props;

  // Memoize arguments to `useAzureCommunicationCallAdapter` so that
  // a new adapter is only created when an argument changes.
  const callAdapterArgs = useMemo(
    () => ({
      userId: fromFlatCommunicationIdentifier(userId) as CommunicationUserIdentifier,
     displayName,
      credential: new AzureCommunicationTokenCredential(userToken),
      locator: { participantIds: ACS_USER_IDS },
    }),
    [userId, userToken, displayName]
  );

  const callAdapter = useAzureCommunicationCallAdapter(callAdapterArgs);

  return (
    <div style={{ height: '100vh', display: 'flex' }}>
      {callAdapter ? (
        <CallComposite adapter={callAdapter} />
      ) : (
        <h3>Initializing...</h3>
      )}
    </div>
  );
};
```
Here is the code of the stateful clients that receive the incoming call:
```
import React, { useEffect, useMemo, useState } from 'react';
import {
  Call,
  CallAgent,
  GroupCallLocator,
  IncomingCall,
  IncomingCallEvent
} from '@azure/communication-calling';
import { AzureCommunicationTokenCredential } from '@azure/communication-common';
import {
  DEFAULT_COMPONENT_ICONS,
  createStatefulCallClient,
  StatefulCallClient,
  FluentThemeProvider,
  CallAgentProvider,
  CallClientProvider,
  CallProvider
} from '@azure/communication-react';
import { initializeIcons, registerIcons } from '@fluentui/react';
import CallingComponents from './Components/CallComponentsStateful';
import { IncomingCallToast } from './Components/IncomingCallToast';

initializeIcons();
registerIcons({ icons: DEFAULT_COMPONENT_ICONS });

function App(): JSX.Element {
  // User access token and ID
  const userAccessToken = '<ACS User Token>';
  const userId = '<ACS User Id>';

  // Initial group state
  const initGroup = { groupId: '' } as GroupCallLocator;
  const displayName = '<ACS User Name>';

  // State hooks
  const [statefulCallClient, setStatefulCallClient] = useState<StatefulCallClient>();
  const [callAgent, setCallAgent] = useState<CallAgent>();
  const [call, setCall] = useState<Call>();
  const [incomingCall, setIncomingCall] = useState<IncomingCall>();
  const [group, setGroup] = useState(initGroup);

  // Token credential for Azure Communication Services
  const tokenCredential = useMemo(() => {
    return new AzureCommunicationTokenCredential(userAccessToken);
  }, [userAccessToken]);

  // Fetch user token and initialize call client
  useEffect(() => {
    setStatefulCallClient(
      createStatefulCallClient({
        userId: { communicationUserId: userId }
      })
    );
  }, [userId]);

  // Create call agent once the call client is initialized
  useEffect(() => {
    if (callAgent === undefined && statefulCallClient) {
      const createUserAgent = async (): Promise<void> => {
        setCallAgent(await statefulCallClient.createCallAgent(tokenCredential, { displayName: displayName }));
      };
      createUserAgent();
    }
  }, [callAgent, statefulCallClient, tokenCredential, displayName, group]);

  // Join the call when call agent and group ID are available
  useEffect(() => {
    if (callAgent !== undefined && group.groupId) {
      setCall(callAgent.join(group));
    }
  }, [callAgent, group]);

  // Listen for incoming calls
  useEffect(() => {
    const incomingCallListener: IncomingCallEvent = ({ incomingCall }) => {
      setIncomingCall(incomingCall);
    };
    if (callAgent) {
      callAgent.on('incomingCall', incomingCallListener);
      return () => {
        callAgent.off('incomingCall', incomingCallListener);
      };
    }
  }, [callAgent]);

  // Set the group ID for the call
  const setGroupId = (group: string) => {
    setGroup(current => {
      return {
        groupId: group
      };
    });
  };

  // Reject the incoming call
  const onRejectCall = (): void => {
    if (incomingCall) {
      incomingCall.reject();
    }
    setIncomingCall(undefined);
  };

  // Accept the incoming call
  const onAcceptCall = async (): Promise<void> => {
    if (incomingCall) {
      const call = await incomingCall.accept();
      console.log(call);
      setGroupId(call.id);
    }
    setIncomingCall(undefined);
  };

  return (
    <>
      <FluentThemeProvider>
        {statefulCallClient && (
          <CallClientProvider callClient={statefulCallClient}>
            {callAgent && (
              <CallAgentProvider callAgent={callAgent}>
                {incomingCall && (
                  <IncomingCallToast
                    callerName={incomingCall.callerInfo.displayName}
                    onClickAccept={onAcceptCall}
                    onClickReject={onRejectCall}
                  />
                )}
                {call && (
                  <CallProvider call={call}>
                    {callAgent && <CallingComponents />}
                  </CallProvider>
                )}
              </CallAgentProvider>
            )}
          </CallClientProvider>
        )}
      </FluentThemeProvider>
    </>
  );
}

export default App;
```

and this is the CallComponent from the stateful client:

```
import {
  usePropsFor,
  VideoGallery,
  ControlBar,
  CameraButton,
  MicrophoneButton,
  ScreenShareButton,
  EndCallButton,
  ParticipantsButton,
} from '@azure/communication-react';
import { mergeStyles, Stack } from '@fluentui/react';
import React, { useCallback, useState } from 'react';

function CallingComponents(): JSX.Element {
  // Extracting props for communication components
  const participantsButtonProps = usePropsFor(ParticipantsButton);
  const videoGalleryProps = usePropsFor(VideoGallery);
  const cameraProps = usePropsFor(CameraButton);
  const microphoneProps = usePropsFor(MicrophoneButton);
  const screenShareProps = usePropsFor(ScreenShareButton);
  const endCallProps = usePropsFor(EndCallButton);
  

  const [callEnded, setCallEnded] = useState(false);

  // Handler for ending the call
  const onHangup = useCallback(async (): Promise<void> => {
    await endCallProps.onHangUp();
    setCallEnded(true);
  }, [endCallProps]);

  // Render "CallEnded" component if the call has ended
  if (callEnded) {
    return <CallEnded />;
  }

  // Render the calling components
  return (
    <Stack className={mergeStyles({ height: '100%' })}>
      <div style={{ width: '100vw', height: '100vh' }}>
        {videoGalleryProps && <VideoGallery {...videoGalleryProps} />}
      </div>

      <ControlBar layout="floatingBottom">
        {cameraProps && <CameraButton {...cameraProps} />}
        {microphoneProps && <MicrophoneButton {...microphoneProps} />}
        {screenShareProps && <ScreenShareButton {...screenShareProps} />}
        {participantsButtonProps && <ParticipantsButton {...participantsButtonProps} />}
        {endCallProps && <EndCallButton {...endCallProps} onHangUp={onHangup} />}
      </ControlBar>
    </Stack>
  );
}

// Component for displaying call ended message
function CallEnded(): JSX.Element {
  return <h1>You ended the call.</h1>;
}

export default CallingComponents;
```

This is the package.json from the statuful client app:
```
{
  "name": "acs-stateful",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@azure/communication-calling": "^1.4.4",
    "@azure/communication-chat": "^1.2.0",
    "@azure/communication-react": "^1.5.0",
    "@fluentui/react-icons": "^2.0.201",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react-hooks": "^3.4.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.49",
    "@types/react": "^16.9.49",
    "@types/react-dom": "^16.9.8",
    "react": "~16.14.0",
    "react-dom": "16.13.1",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^5.0.1",
    "react-test-renderer": "^16.14.0",
    "reactstrap": "^8.4.1",
    "typescript": "^4.7.4",
    "uuid": "^9.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

Also, some other questions that we have at the moment:

1. We did not create an event grid in the current tenant, yet the stateful client can still listen to the events of the incoming call. Is this because of the ACS SDK managing these events, or are we missing something in how these events are being handled?
2. When making a call in this manner where the composite is using the ID of a user to initiate the call, is the group ID automatically generated? If so, which property of this incoming call should I use to initiate the call component?
3. Is there a way to capture the necessary props to initiate a CallComposite using these stateful components? For example, subscribing to the event for the incoming call but using the call composite instead of using the individual components for the call.

If there is something else missing from this post that may help understand the problem a bit more, please let me know.

References:
https://azure.github.io/communication-ui-library/?path=/docs/examples-incomingcallalerts-incomingcalltoast--incoming-call-toast

https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-1ton--page

https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-statefulcallclient--page

**Comment by jorgecolon413** [comment]
This is the package.json from the statuful client app: 
```
{
  "name": "acs-stateful",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@azure/communication-calling": "^1.4.4",
    "@azure/communication-chat": "^1.2.0",
    "@azure/communication-react": "^1.5.0",
    "@fluentui/react-icons": "^2.0.201",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react-hooks": "^3.4.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.49",
    "@types/react": "^16.9.49",
    "@types/react-dom": "^16.9.8",
    "react": "~16.14.0",
    "react-dom": "16.13.1",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^5.0.1",
    "react-test-renderer": "^16.14.0",
    "reactstrap": "^8.4.1",
    "typescript": "^4.7.4",
    "uuid": "^9.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by alkwa-msft** [comment]
the stateful client is really a wrapper around the calling sdk
which in addition to making calls through the calling sdk will
store the responses in a structured (json) format. It is purely javascript and does not generate any UI (react) components. It is used to help drive communication experiences with UI Library by acting as a data source to power our UI components and composites.
https://azure.github.io/communication-ui-library/?path=/docs/overview--page

1. You do not need to create an event grid, when you set up 
the client you are initializing that user. The stateful client
will handle registering to all events and so if you call this user
the incoming call event will be recieved

2. The group id is a guid which anyone on that acs resource can use
to meet in the same "call". You do no recieve an incoming call event
because no one starts the call to you. Everyone has to join the call.

https://learn.microsoft.com/en-us/azure/communication-services/how-tos/calling-sdk/manage-calls?pivots=platform-web#join-a-group-call

3.The CallComposite is most likely what you want to use. The adapter
property in the composite takes in an adapter concept (the brains).
The AzureCommunicationCallAdapter under the hood uses the stateful client
so you will be able to initiate a group call with the composite by
running through this sample.

https://azure.github.io/communication-ui-library/iframe.html?viewMode=docs&id=composites-call-basicexample--basic-example#basic-usage

It would be helpful to know what scenario you are trying to do here.
From the questions it sounds like you want to work with group calls but
it looks like from the documentation you are looking into voip 1:1/pstn
calling?

**Comment by fpereiramapfrepr** [comment]
Thanks for the quick response!

Taking into consideration points 1 and 2, can I create a client using the stateful clients and manage call notifications with the toast example, but only use the CallComposite for the calling UI? For example, subscribing to events using the stateful clients but passing the necessary props from the stateful clients to the CallComposite?

Our scenario primarily involves 1:1 video conferencing and chat communication. Additionally, we want to implement file sharing, and we have conducted some tests and have a few questions on that topic as well.

**Comment by jorgecolon413** [comment]
Thanks for the quick response!

Taking into consideration points 1 and 2, can I create a client using the stateful clients and manage call notifications with the toast example, but only use the CallComposite for the calling UI? For example, subscribing to events using the stateful clients but passing the necessary props from the stateful clients to the CallComposite?

Our scenario primarily involves 1:1 video conferencing and chat communication. Additionally, we want to implement file sharing, and we have conducted some tests and have a few questions on that topic as well.

**Comment by jorgecolon413** [comment]
Thanks for the quick response!

Taking into consideration points 1 and 2, can I create a client using the stateful clients and manage call notifications with the toast example, but only use the CallComposite for the calling UI? For example, subscribing to events using the stateful clients but passing the necessary props from the stateful clients to the CallComposite?

**Comment by jorgecolon413** [comment]
I think this [example](https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-statefulclient--page) could help to understand how to use the stateful clients. I notice that the stateful client and CallComposite can not co-exists since both instantiate clients and a client can only be instantiated once at a time. Our desired goal is to have a CallComposite manage the call client object and handle the incoming call for that one Acs user receiving the call.

**Comment by dmceachernmsft** [comment]
Hi @jorgecolon413 so I read through your snippet on setting up the stateful client and you are doing everything correctly, for the most part. There is one small issue here: 
![image](https://github.com/Azure/communication-ui-library/assets/94866715/a56f8832-0d77-41bb-b772-88d327af79b1)
In your incomingCall handler you are taking the call ID for the accepted call and setting it as a groupId. In this instance this is incorrect. When you accept a incomingCall, with our stateful client, you are to use the call that is returned and set it in the `CallProvider`. Something like this:
```
  // Accept the incoming call
  const onAcceptCall = async (): Promise<void> => {
    if (incomingCall) {
      const call = await incomingCall.accept();
      console.log(call);
      setCall(call);
    }
    setIncomingCall(undefined);
  };
```
This will then have the CallComponents you made switch over to track this call. Let me know if you have any other questions about this!

**Comment by jorgecolon413** [comment]
Hey @dmceachernmsft your suggestion worked! Thanks for the feedback and your time. 
![git](https://github.com/Azure/communication-ui-library/assets/58268872/c1f98527-f8cb-4422-b064-4d2cc2c3a412)



I was reviewing the documentation in search of other options for handling these events, but it appears that the CallComposite adapter does not provide this kind of event listening functionality. Is there a specific reason for this limitation?

**Comment by dmceachernmsft** [comment]
@jorgecolon413 yes for now we stopped at the stateful client layer. We are working on how we want to provide the best incoming call behaviours for our composite so we didn't stick the logic into the adapter just yet. the decision was made to leave it at the components/stateful client for now to let developers implement their own toast notifications and call waiting experience.

Glad we got you going though! Did you have any other questions on incoming calls and the UI library right now?

**Comment by dmceachernmsft** [comment]
@jorgecolon413 sorry for the late reply! 

For the mean time yes. we are looking to support it in the composites as well but right now only the components are supported at this time. If you were to create the clients and build the adapter from them (we have a little function `createAzureCommunicationCallAdapterFromClient()` that does allow this, you can subscribe to the incoming call events like before. the problem though is the adapter does not currently know when new calls are updated and how to process them to make sure the composite is reflecting the right call.

**Comment by dmceachernmsft** [comment]
Seems the questions are resolved for now! Please reopen the issue if you need any further advice!
