### ISSUE TITLE
Add Adaptive Cards support to MessageThread component (composite would get it for free?)

### ISSUE THREAD

**Issue by managedcoder** [Azure/communication-ui-library#3039]
**What feature are you requesting?**
I'd love to see [Adaptive Cards](https://adaptivecards.io/) support added to the MessageThread component where ChatMessage would have a new MessageContentType called "card" (adding to the existing "text", "html", "richtext/html", "unknown") and the ChatMessage.content property could hold the JSON string defining the Adaptive Card and introduce an optional new property called ChatMessage.data that would hold a data object as a JSON string that, along with ChatMessage.content, would be passed to the Adaptive Card rendering method of the Adpative Card SDK for web (and mobile Adaptive Card SDKs for the mobile UI Library versions which could come in a later release).
 
**What would be the benefit of adding this feature?**
Cards are a must in chat experiences these days and PVA and Teams already support them which are two very important platforms I want to be able to use this library to connect to.  The WebChat control is nice, and it can be customized to an extent, but I've had lots of occasions where there weren't enough knobs to allow for the changes I was being asked to make.  This library gives my full control over the chat experience, but I will be connecting it to things that can speak in cards (PVA and Teams for sure but there will be others) so if a card flows to my chat or my chat wants to send a card, I stuck without this card support.  I am working on a project right now and I am using this library to build a fully customized and branded experience interfacing with GPT-based bots which I expect to push what is possible in a chat experience and I don't want to have to bust out the Adaptive Card SDK and roll that myself.

**What solution would be ideal for you?**
Add Adaptive Card support for at least the web

**What alternatives have you considered?**
Hacking a solution myself and wedging it on top of ChatMessage... lot's of work and potentially an unnatural fit I have to force

**Is there any additional information for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by Leah-Xia-Microsoft** [comment]
@managedcoder Thanks for raising this issue. We are currently looking into it and will be sharing a response after discussing with the team.

**Comment by vhuseinova-msft** [comment]
Hello @managedcoder! Thank you for your feedback!
To help us understand how you use Chat UI Library right now, could you please help to clarify the following:
1. Do you use UI Components or ChatComposite?
2. Do you use Chat UI SDK for ACS chat, Teams Interop Chat or some other scenarios?

**Comment by JoshuaLai** [comment]
@managedcoder Just wanted to follow up on this request.

**Comment by managedcoder** [comment]
@JoshuaLai and @vhuseinova-msft, I am using UI Components in my scenario since I need that level of control but I would hope that if you solve it for UI Components then the Composits would get it for free.

I've used both the Composits and Components in different apps for different purposes.  Recently, I used the UI Components recently to implement T[eams Engagement Hub for Powe Virtual Agents](https://github.com/managedcoder/TeamsEngagementHub) (hence the need for a chat control) and I am using UI Components to build a chat control to front-end calls to Open AI's LLM for a ChatGPT-like experience you can embed in any web app.

By the way, I was slow in responding here because I don't get alerts that there has been a response from GitHub when there is a response to an issue unless I am @mentioned.  I wish GitHub issues worked like StackOverflow where you could opt into email notifications when there is activity on the thread.

Please @mention me in any response to any issue we are working on together!!!

**Comment by JoshuaLai** [comment]
@managedcoder We do have adaptive cards tracked in our backlog but don't have clear idea of when the work will be completed. If you would like a quick sample of how you can use adaptive cards we have be able to provide some guidance. But otherwise you may need to wait for us to formally support it.

**Comment by vhuseinova-msft** [comment]
@managedcoder, thank you for sharing the details!

We appreciate your request and, as @JoshuaLai mentioned, we will carefully consider it.

Currently, the recommended approach is to use `onRenderMessage` callback for [MessageThread UI component](https://azure.github.io/communication-ui-library/iframe.html?viewMode=docs&id=ui-components-messagethread--message-thread#props) with a check for adaptive cards data. Please see [this GitHub discussion](https://github.com/Azure/communication-ui-library/discussions/3130) for more details.

We value your feedback, and customer input plays a crucial role in shaping our roadmap. We appreciate your understanding and patience as we work towards improving the product!
