### ISSUE TITLE
Eliminate border around SendBox

### ISSUE THREAD

**Issue by managedcoder** [Azure/communication-ui-library#3044]
**What feature are you requesting?**
I need to be able to get rid the border around SendBox but I can't get access to that style.  No matter what I tried, I could not get rid of that 1-pixel black boarder.  I looked through all the styles in SendBoxStylesProps and none controlled that 1-pixle black box around the control.  Using the F12 tools in the browser, I was able to find the style that contains the boarder and I was able to toggle it off but it's a generated style so not sure how I can change the style.

**What would be the benefit of adding this feature?**
I could control more of the look and feel.  I don't want a border around the SandBox so I can set the SendBox to one solid color with rounded corners and no border.  Chaining the corner radius of a div that has a border causes it to drop the corner portion and it looks strange.

**What solution would be ideal for you?**

**What alternatives have you considered?**

**Is there any additional information for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by Leah-Xia-Microsoft** [comment]
@managedcoder Thanks for raising this issue. We are currently looking into it and will be sharing a response after discussing with the team.

**Comment by JoshuaLai** [comment]
Hi @managedcoder this sounds like a great suggestion! If you would like to help share your suggestion here: https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858 we can create a feature request and prioritize it in our back log!

**Comment by JoshuaLai** [comment]
Hi @managedcoder, hopefully you will got a chance to post your feature suggestion. I will be closing this git issue, but if you feel like you need to raise the priority of this or want to provide us with more context feel free to re-open this git issue and continue the discussion in this thread.

**Comment by managedcoder** [comment]
Thanks @Leah-Xia-Microsoft and @JoshuaLai for your responses but as I've thought about it, I think a better option would be to clone the repo and customizing the MessageThread and SendBox.  I've cloned the repo but had trouble running the chat sample since the dev server with the dependent API didn't start for some reason.  I will open an issue on that separately.

**Comment by JoshuaLai** [comment]
@managedcoder it sounds like you didn't set up the `appsettings.json`
Under `samples/server` you will find this file and you will need to put in `ResourceConnectionString` `EndpointUrl` `AdminUserId`
You can follow some steps here: https://github.com/Azure/communication-ui-library/blob/main/docs/contributing-guide/3.%20running-a-sample-or-storybook.md#running-one-of-the-sample-apps

**Comment by managedcoder** [comment]
@JoshuaLai, just wanted to follow up here for future readers who might be reading this thread.  You are correct, my issue was that I didn't set all the required properties in appsetting.json and we talked about which ones need setting and where to get the values in [issue #3064](https://github.com/Azure/communication-ui-library/issues/3064#issuecomment-1551411235)
