### ISSUE TITLE
Call End Reason Codes and Sub Codes missing from documentation

### ISSUE THREAD

**Issue by rdo-mgowland** [Azure/communication-ui-library#3046]
I can find zero documentation on call end reason codes and subcodes. Other than that the main code is a http code - but this doesnt give much insight. Do you have a list of the codes and sub codes and description please. Thanks.

**Comment by alkwa-msft** [comment]
https://learn.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#calling-sdk-error-codes

Yes we build the UI Library on top of the existing azure communication services calling sdk.
So this is good feedback we can probably link back to some of the troubleshooting guides of the underlying dependencies.
