### ISSUE TITLE
Add ability to use native windows teams client for call control

### ISSUE THREAD

**Issue by rdo-mgowland** [Azure/communication-ui-library#3054]
Add ability to handle calls using the native windows teams app, so you can use the API to access/control calls to the native teams app.

Currently, the API allows you to create a separate teams agent which then allows you to answer inbound calls, make calls, and control those calls. However, if the user makes/receives calls from the real teams app then the API has no visibility/access/control to these calls.  So if you are building a custom call workflow for teams users, then they have to use your browser based app, and if they handle the call in the native app then the custom app cant be used.

Please add in functionality so you can subscribe the app to use the native windows teams app as the "teams call agent" instead of having a new instance.  This would mean the calls are actually processed and handled by the teams app, but the API can then control that teams app.  EG, you register the custom app to use the teams native app, and then the user can answer/make calls in the custom app but the call is actually answered/initiated by the teams app, and then the custom app can control the teams call, eg the user can then use the custom app to transfer calls, end the call, make new calls etc. This means the user can get all the functionality of the custom app whether the user makes/answers the call with the custom app OR the native windows teams app.

Currently when a call comes in for the user, both the Teams App AND the custom app ring allowing them to answer the call from ONE of these inbound answer points. If they answer on the teams app then they cant get the functionality of the custom app. If they answer on the custom app then they cant just use teams to handle the call (eg hangup or transfer the call) using the Teams app.

In the cisco world, this works very well using Cisco Finesse, in that the user can use cisco finnese OR cisco jabber OR cisco desk phone to handle the call, but then they still have all the functionality of Finesse (including custom apps).

I would propose that when your custom app starts that they can select a "Teams Calling Agent" to be one of their teams apps they are already signed into, instead of instantiating a new "teamsCallAgent". So with the API, there should be the option to get a list of currently active teams app sessions for the user that they can attach the custom app to. Then the API works exactly as it does but the TeamsCallAgent is actually a proxy for the selected Teams App session.

**Comment by alkwa-msft** [comment]
@rdo-mgowland Thanks for sharing this issue. 

It does sound like it provides a fair amount of flexibility in using Cisco, however at this time it does not look like we will be able to provide this type of functionality based on the current direction of the Teams product and how they want to integrate with their ecosystem. **The UI Library project will not be supporting this feature ask at this time.**
