### ISSUE TITLE
call to :3000/createThread:1 fails with 504 (Gateway Timeout) in Chat sample

### ISSUE THREAD

**Issue by managedcoder** [Azure/communication-ui-library#3064]
**Describe the bug; what happened?**
I followed the[ instructions for getting started and building samples and packages](https://github.com/Azure/communication-ui-library/blob/main/docs/contributing-guide/3.%20running-a-sample-or-storybook.md) but when I ran the` rushx start` command from the samples\chat folder, the page launches and when I click the blue Start Chat button the page hangs and when I look at the console in the F12 tools I see an error that says,, "Failed to load resource: the server responded with a status of 504 (Gateway Timeout)" while calling :3000/createThread:1 (see screengrab below)

<img width="1244" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/5aa4b640-e97b-4300-8385-79a8c0ab79d4">

**What are the steps to reproduce the issue?**
I got this error after cloning the repo and the only change I made was to set the connection string in the appsettings.json in the Server folder. So to repo, follow the steps in the doc found [here ](https://github.com/Azure/communication-ui-library/blob/main/docs/contributing-guide/3.%20running-a-sample-or-storybook.md)to clone, build, and run the Chat sample

**What behavior did you expect?**
I expected the Chat sample to run

**If applicable, provide screenshots:**
<img width="1244" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/5aa4b640-e97b-4300-8385-79a8c0ab79d4">

**In what environment did you see the issue?**
node.js version: v16.20.0

Got the following from the packages.json file in the samples/Chat folder:
    "@azure/communication-chat": "1.3.2-beta.1 || >=1.2.0",
    "@azure/communication-common": "2.2.0",
    "@azure/communication-identity": "~1.1.0",
    "@azure/communication-react": "1.5.1-beta.4",

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
Windows 11
- Browser: [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
Edge browser
- Browser Version: [e.g. 1.8.0]
Edge Version 113.0.1774.42 (Official build) (64-bit)

**Is there any additional information?**

**Comment by JoshuaLai** [comment]
Hi @managedcoder I think I dropped a response in your other git issue, but lets continue the conversation here. 
For the chat sample, the appsettings.json needs   `ResourceConnectionString` `endpoint`
and  `AdminUserId` just wanted to verify you provided all three. I will take a look on our backend and see if I can collect more information on what else can cause a potential 504

**Comment by JoshuaLai** [comment]
Revisiting the contribution guide it looks like it only mentions updating `ResourceConnectionString` which assumes developers are only running the calling sample. Apologies for the confusion, for the chat sample all three properties are required. I did just run the sample myself and it worked as expected. Let me know if these steps still don't work for you. In the mean time I will create an update to the contribution guide to fill this gap.

**Comment by managedcoder** [comment]
@JoshuaLai, I set the `AdminUserId` by going to the Azure Portal and drilled into the ACS resource and into the **_Identities & User Access Tokens_** blade and then chose _**Chat**_ and generated an Indentity and used that for the `AdminUserId` setting.  Is that what I was supposed to do?

What do I set `endpoint` to?

**Comment by JoshuaLai** [comment]
Yes that is correct. 
So in the Azure Portal under `Settings` `Keys` 
![image](https://github.com/Azure/communication-ui-library/assets/9044372/06038e10-7ddc-4273-bcf5-e181760ead0c)

You will see at the top your endpoint url is there just above the primary key.
![image](https://github.com/Azure/communication-ui-library/assets/9044372/27b16d51-93dc-47c7-8744-f0e2d7562d64)

**Comment by managedcoder** [comment]
@JoshuaLai, your guidance regarding setting `ResourceConnectionString`, `EndpointUrl`, and `AdminUserId` fixed my issue and the sample now runs.  THANK YOU!!

Two things I'll mention having traveled this misguided path:
1) The ACS connection string has the endpoint in it.  Just curious, why not extract it from the connection string setting and remove EndpointUrl` from appsettings.json.  Less for dev to do and to have to understand, less to document.
2) In hindsight, apart from missing doc that you've now address (thank you), part of my confusion I think stemmed from the fact that the appsettings.json file has what I think is a misleading default value for the `EndPointUrl `setting.  It's set to "localhost:8080" which I assumed was related to the dev server that's in the server folder since it starts on 8080 so I sort of thought this app setting was good to go.

Adding an explanation of those app settings and most importantly, where to get the values for them would be very helpful for the uninitiated who come behind us.

-Russ

**Comment by JoshuaLai** [comment]
Great news! Happy to hear you are unblocked. 
> The ACS connection string has the endpoint in it. Just curious, why not extract it from the connection string setting and remove EndpointUrl` from appsettings.json. Less for dev to do and to have to understand, less to document.
I think in terms of this I can say this was a conscious design decision we decided to make. The goal was to instead of making developers do extra steps or do some incorrect / hacky solution in stripping the endpoint from the connection string. This promoted more clearer simpler approach. 
> In hindsight, apart from missing doc that you've now address (thank you), part of my confusion I think stemmed from the fact that the appsettings.json file has what I think is a misleading default value for the EndPointUrl setting. It's set to "localhost:8080" which I assumed was related to the dev server that's in the server folder since it starts on 8080 so I sort of thought this app setting was good to go.
I think this is definitely a good call out, I can bring this back to the team and hear their thoughts about it as well.

Since it sounds like you are unblocked I will be closing this issue.

**Comment by managedcoder** [comment]
@JoshuaLai, agree, you can close this out.  Regarding the endpoint point I was making and your response about specifically choosing an approach that does not make dev do extra steps or hacking solutions... I hope I didn't confuse things... what I was suggesting is that you guys just take a connection string, remove the endpoint setting and then in you code, you guys extract the endpoint from the connection string whose format is not going to change and its something I would think you could count on not changing in the sense that the endpoint will someday be removed from the connection string (kind of the whole point of that connection string really).  So, if you did that, it would not be hacky, I'd say it was more elegant from a dev's point of view and certainly less work for the dev.  Anyway, just putting that out there.

**Comment by jpeng-ms** [comment]
Great suggestions Russ @managedcoder , I will create a backlog item for this. Feel free to let us know what other things we can do to make things better.

John
