### ISSUE TITLE
Seeking Guidance for Chat Scenario

### ISSUE THREAD

**Issue by managedcoder** [Azure/communication-ui-library#3073]
ChatGPT has animated every industry imaginable!  I've used the UI Library for other projects, but the focus of my current project is to create an experience to host a ChatGPT-powered chatbot experience in a web app and here is where your UI Library shines.  Normally, when one builds a chatbot you'd use a commercial platform like Power Virtual Agents, Lex, Dialogflow, etc. and all of those come with their own chat controls that are bound to their specific platform.  Not so I don't think with OpenAI's LLM.  I am not aware of any such chat controls for OpenAI LLM so you needs to be created and the UI Components are perfect for this.  Initially, I think MessageThread and SendBox are all that I'll need, but I need to customize them to deliver the custom experience I have planned.  So, my question is, what's the best way to get those two components to cleanly plug into my app?  Seems like I'd only need the @azure/communication-chat package if I just stick to those two components since they are pure UI, no ACS concepts or dependencies.  Thoughts?

-Russ

**Comment by JoshuaLai** [comment]
@managedcoder Just to understand your use case it sounds like you don't want to use ACS backend?
Are you looking to use our chat components without Azure Communication Services and instead with a custom backend powered by ChatGPT? Or are you interested in integrating ChatGPT into Azure Communication Services Chat. This will help us provide the right support. 

If you are interested in just sing UI components we have samples and documentation here: https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-uicomponents--page#chat-ui-components

If you want to integrate ChatGPT into the Azure Communication Services Chat service, then lets discuss further. We can recommend you look at Azure Cognitive Services for that type of functionality: [Azure Cognitive Services documentation | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cognitive-services/)

**Comment by managedcoder** [comment]
@JoshuaLai , for the initial scenario I am working on I am trying to use the UI Library without ACS backend simply because the task is to frontend an NLP, OpenAI's GPT-4, in this case that has its own predetermined API I need to use to integrate with it.  

Maybe I was over emphasizing the overall pattern at play in my scenario but the point I was trying to make was that chat platforms all have chat controls that are built specifically for them, but as far as I could tell, OpenAI has not created their own chat control in an SDK form that you could just drop in a web app and go.  I was also making the point that other chatbot platforms do have chatbot controls, but even in those cases, you often want/need full control over that chat UX and in both these cases, OpenAI's lack of a control and these other platforms UX-challenged control, the component UI Library is a fantastic solution since MessageThread and SendBox are chat-agnostic.  The UI Library's Composits are not chat-agnostic, they are ACS-based and that's just fine but not what I need in this particuar scenario.

So, the guidance I am seeking is, what's the best way to get those two components to cleanly plugged into an app? I want to lift them into an app without tearing them out of the UI Library.  Seems like I'd only need the @azure/communication-chat package if I just stick to using those two components since they are pure UI, no ACS concepts or dependencies.  Can you see any issues with just building the @azure/communication-chat package and installing it in an application if I am just using MessageThread and SendBox.  I would guess that some things in @azure/communication-chat do have dependencies on ACS and other packages, but if I am just using those two components, would I be able to build that package and install just @azure/communication-chat into an app without issues?

Also, I think I saw some doc on how to build these packages so they could be customized and use locally but if you have a link handy that describes how I would create a version of @azure/communication-chat package that I customized so I could cleanly install it in an app, that would be great.

By the way, it isn't that I don't want to use ACS, it's just that the communication between chat client and NLP backend is via an already established APIs.  It would be an awesome world if chatbot vendors decided to generalize on ACS threads for their communication, but that's not the case so I can't use ACS to talk to GPT-4.  

It would be very interesting if someone were to create a GPT-3.5 and GPT-4 "channel" (and later other LLM channels) so that the UI Library could be used, in all it's glory, to talk to any of those LLMs, without being UX-limited by potentially less capable chatbot clients.  I can tell you this, almost all the conversational AI projects I've worked on over the last 6 years have had scenarios that required a chatbot UX that was either very challenging to deliver, or impossible, due to the limitations of the Chat control provided by the platform vendor.  Adaptive Cards is a great example.  Lovely idea... generalize a rendering format so that components can be safely composed onto a 1st party page like Teams, Facebook, etc.  The cost of that generality is in the complexity of the card language and still, I've had cases with Adaptive Cards where I wanted/needed more control over styling and behavior that I could get.

One last point about my initial lack of ACS requirement. I can definitely see a near term need in my scenario for ACS where I could augment the UX with screen sharing, human agent support, and more, but I have to get this first rudimentary scenario going and then build on it.

So that was a very long-winded way of saying that MessageThread and SendBox allow me to do two interesting things:

1. Create a chatbox UX for an NLP platform that does not have one yet
2. Step away from platform-specific chatbox control that don't offer enough knobs to produce the UX I need and instead roll my own UX without having to reinvent the wheel with respect to basic chatbox primitives and because it's open source, I have absolute control over every aspect of UX if I need to customize it. 

-Russ

**Comment by managedcoder** [comment]
Now that I've looked into this more, the guidance I was looking for is completely provided [here ](https://github.com/Azure/communication-ui-library/blob/main/docs/contributing-guide/4.%20testing-your-changes.md#testing-changes-in-your-app) which covers the steps for cloning, building, modifying, testing, re-packaging, and installing the customized UI Library into my app.

**Comment by JoshuaLai** [comment]
Thats great! It seems like you figured out a path on your own. I will be closing this issue. We look forward to seeing what you build!
