### ISSUE TITLE
Can't use usePropsFor() in spread operator in app that integrates customized UI Library packages

### ISSUE THREAD

**Issue by managedcoder** [Azure/communication-ui-library#3122]
I've cloned the UI Library and customized the reactComponents package and installed the customized package along with its dependencies in my app and I am trying to use the usePropsFor() to initialize the SendBox properly but I've run into an issue that I describe below.

I've tried to replicate the pattern of usage for usePropsFor() that I saw in the ComponentExamples but for some reason VS Code's static code analysis says the variable is null and when I run the app it gives this error:
<img width="520" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/ffeef23e-4fe5-438f-81b7-318565c32205">

I have the component that calls usePropsFor() wrapped like this:
<img width="474" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/d5e25207-72c3-4a2e-9987-6f6877df8fc4">

Here's my dependencies:
<img width="538" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/1e4884b2-250d-4a0b-9e5d-89f4e8bc4da4">

What might be going on here?

-Russ

**Comment by managedcoder** [comment]
I should have included this screengrab in my last post... Here is the code for SendBox:
<img width="405" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/cec21cb6-fe44-4e29-bbae-60b11ddf5013">

and here is the static code analysis error for the red squiggly:
<img width="462" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/c3ed7e3f-1465-4d67-ba30-63a5c87ed37a">

-Russ

**Comment by JoshuaLai** [comment]
Hi @managedcoder I need a little more information on how you are creating the `sendBoxProps`. 

We have an example of how you can use our method https://azure.github.io/communication-ui-library/?path=/docs/statefulclient-reacthooks-useselector--page#write-your-own-handler-function

**Comment by managedcoder** [comment]
Here's that snippet.  I will confess, I don't understand the selector concept as explained in that doc but I think I understand generally what usePropsFor() and I tried to follow the pattern I saw in the sample app:

<img width="790" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/b79e7d36-33be-49cc-9e16-f34d6822cf9c">

**Comment by managedcoder** [comment]
Ok, sorry for the confusion here but I think I had the initialization of the sendPropsBox commented out when I grabbed the initial runtime error screen and this may be a much bigger hint at what is happening.  It looks like it selector related... what is that selector code supposed to look like?

<img width="1062" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/d43a054d-e924-4b15-b0f5-dc774eaa9667">

**Comment by managedcoder** [comment]
Here is the full listing of the source code that produced that above error:

import './MyChat.css';

import {
    usePropsFor
} from '@azure/communication-react';

import {
    SystemMessage,
    CustomMessage,
    ChatMessage,
    MessageThread,
    MessageProps,
    MessageRenderer,
    SendBox,
} from '@internal/react-components-custom'

import React, { useEffect, useMemo, useState, useContext, useRef } from 'react';
import { Divider } from '@fluentui/react-components';
import { askGPT } from '../services/gptAnswers'

export type ChatContainerProps = {
    width: number,
    height: number
};

type ChatMessages = (SystemMessage | CustomMessage | ChatMessage)[];

// Renders custom messages like a Divider.
const onRenderMessage = (messageProps: MessageProps, defaultOnRender?: MessageRenderer): JSX.Element => {
    if (messageProps.message.messageType === 'custom') {
        return <Divider>{messageProps.message.content}$</Divider>
    }

    return defaultOnRender ? defaultOnRender(messageProps) : <></>;
};

export const MyChat = (props: ChatContainerProps): JSX.Element => {
    const msgsRef = useRef([] as ChatMessages);
    const [msgs, setMsgs] = useState([] as ChatMessages);
    const [userId, setUserId] = useState("1");
    const [data, setData] = useState([]);
    const [data2, setData2] = useState("default");

    // Add message to the array of messages that MessageThread uses to render it's canvas.
    const addMessage = (msg: SystemMessage | CustomMessage | ChatMessage): (SystemMessage | CustomMessage | ChatMessage)[] => {
        // Append new msg to msgsRef which is a React global variable
        msgsRef.current = [...msgsRef.current, msg];
        setMsgs(msgsRef.current);

        return msgs;
    };

    const sendBoxProps = usePropsFor(SendBox);
    const messageThreadProps = usePropsFor(MessageThread);
    
    return (
        <>
            <div style={{
                textAlign: 'left',
                paddingTop: '10px',
                paddingLeft: '15px',
                color: 'white',
                borderRadius: '15px 15px 0px 0px',
                background: '#0363AD',
                boxShadow: '-3px 6px 17px #D2D2D2, 3px 6px 10px #D2D2D2',
                width: '500px', height: '40px', marginLeft: '20px', marginRight: '10px', marginBottom: '-10px', marginTop: '10px'
            }}>
                Title
            </div>

            <div style={{ boxShadow: '0px 8px 15px 5px #D2D2D2', width: '500px', height: '600px', marginTop: '10px', marginRight: '10px', marginBottom: '0px', marginLeft: '20px' }}>
                <MessageThread
                    messages={msgs}
                    userId={userId}
                    showMessageDate={true}
                    showMessageStatus={true}
                    onRenderMessage={onRenderMessage} />
            </div>

            <div style={{ width: '508px', marginTop: '0px', marginRight: '10px', marginBottom: '10px', marginLeft: '16px' }}>
                <div style={{ border: '0px !important', height: '3px', backgroundColor: '#0085EF', width: '98%', marginTop: '0px', marginRight: '0px', marginBottom: '-6px', marginLeft: '4px' }} />
                <SendBox
                    {...sendBoxProps}
                    styles={{
                        textField: {
                            // textAlign: 'left',
                            borderRadius: '0px 0px 15px 15px',
                            border: '0px solid transparent',
                            background: '#F2F2F2',
                            boxShadow: '-3px 6px 17px #D2D2D2, 3px 6px 10px #D2D2D2'
                        }
                    }}
                    onSendMessage={async (content: string) => {
                        let x;
                        //let answer = await askGPT(content);

                        addMessage({
                            messageType: "chat",
                            senderId: "guestId",
                            senderDisplayName: "me",
                            messageId: "msgId",
                            content: content,
                            createdOn: new Date(),
                            mine: true,
                            attached: false,
                            contentType: "text",
                        });

                        let answer = await askGPT(content);

                        addMessage({
                            messageType: "chat",
                            senderId: "botId",
                            senderDisplayName: "bot",
                            messageId: "msgId",
                            content: answer,
                            createdOn: new Date(),
                            mine: false,
                            attached: false,
                            contentType: "text",
                        });

                        return;
                    }}
                    onTyping={async () => {
                        return;
                    }}
                    // onRenderIcon={() => <Icon iconName="AirplaneSolid" />}
                />
            </div>
        </>
    );
};

export default MyChat;

**Comment by JoshuaLai** [comment]
@managedcoder Looking at your imports it looks like you are not importing our version of `SendBox`. Our `usePropsFor` is context aware, and returns it in the context of our components. And it looks you are using your own copy of `SendBox` which maybe leading to your issue. 

There are a few things I can recommend, the first is to use our version of `SendBox` as a parameter of `usePropsFor`. Something you can try:
```ts
import { usePropsFor,  SendBox } from '@azure/communication-react'
```
And you can update the name of your custom one as `CustomSendBox` and just pass in our props into it. 
```ts
const sendBoxProps = usePropsFor(SendBox);

<CustomSendBox {...sendBoxProps} />
```

Or since you are writing your own components we have documentation here: [Stateful Client / React Hooks / UseSelector - Page ⋅ Storybook (azure.github.io)](https://azure.github.io/communication-ui-library/?path=/docs/statefulclient-reacthooks-useselector--page#basic-example) on how you can create your own selectors.

Hope this helps!

**Comment by palatter** [comment]
@managedcoder I hope this solution worked for you. I will close this but feel free to reopen if you still need help.

**Comment by managedcoder** [comment]
Ah!  Missed you by a few hours!!!! I just got back to this... returning after being reprioritized but now I am back now trying to dig back in and get this going.  Something strange is going on and I am getting a slightly different error but with the shipping release only!  The error still happens on the usePropsFor() calls (so perhaps my customization was not a factor in this issue right from the get go... not sure).  I have included my source and my package.json below.  

You'll notice that I totally commented out my customized SendBox and MessageThread and I am just using straight shipping code that should presumably work provided I haven't made some rookie mistake (which is totally possible).  What gives?  Anything I should try?

// MyChat
import './MyChat.css';
import { Icon } from '@fluentui/react';

import {
    usePropsFor,
    SystemMessage,
    CustomMessage,
    ChatMessage,
    MessageProps,
    MessageRenderer,
    MessageThread,
    SendBox,
} from '@azure/communication-react';

// import {
//     MessageThread as MyMessageThread,
//     SendBox as MySendBox,
// } from '@internal/react-components-custom';

import React, { useEffect, useMemo, useState, useContext, useRef } from 'react';
import { Divider } from '@fluentui/react-components';
import { askGPT } from '../services/gptAnswers'

export type ChatContainerProps = {
    width: number,
    height: number
};

type ChatMessages = (SystemMessage | CustomMessage | ChatMessage)[];

// Renders custom messages like a Divider.
const onRenderMessage = (messageProps: MessageProps, defaultOnRender?: MessageRenderer): JSX.Element => {
    if (messageProps.message.messageType === 'custom') {
        return <Divider>{messageProps.message.content}$</Divider>
    }

    return defaultOnRender ? defaultOnRender(messageProps) : <></>;
};

export const MyChat = (props: ChatContainerProps): JSX.Element => {
    const msgsRef = useRef([] as ChatMessages);
    const [msgs, setMsgs] = useState([] as ChatMessages);
    const [userId, setUserId] = useState("1");
    const [data, setData] = useState([]);
    const [data2, setData2] = useState("default");

    
    // Add message to the array of messages that MessageThread uses to render it's canvas.
    const addMessage = (msg: SystemMessage | CustomMessage | ChatMessage): (SystemMessage | CustomMessage | ChatMessage)[] => {
        // Append new msg to msgsRef which is a React global variable
        msgsRef.current = [...msgsRef.current, msg];
        setMsgs(msgsRef.current);

        return msgs;
    };
    
    const sendBoxProps = usePropsFor(SendBox);
    const messageThreadProps = usePropsFor(MessageThread);

    return (
        <>
            <div style={{
                textAlign: 'left',
                paddingTop: '10px',
                paddingLeft: '15px',
                color: 'white',
                borderRadius: '15px 15px 0px 0px',
                background: '#0363AD',
                boxShadow: '-3px 6px 17px #D2D2D2, 3px 6px 10px #D2D2D2',
                width: '500px', height: '40px', marginLeft: '20px', marginRight: '10px', marginBottom: '-10px', marginTop: '10px'
            }}>
                Title
            </div>

            <div style={{ boxShadow: '0px 8px 15px 5px #D2D2D2', width: '500px', height: '600px', marginTop: '10px', marginRight: '10px', marginBottom: '0px', marginLeft: '20px' }}>
                <MessageThread
                    //{...messageThreadProps}
                    messages={msgs}
                    userId={userId}
                    showMessageDate={true}
                    showMessageStatus={true}
                    //onRenderMessage={onRenderMessage}
                />
            </div>

            <div style={{ width: '508px', marginTop: '0px', marginRight: '10px', marginBottom: '10px', marginLeft: '16px' }}>
                <div style={{ border: '0px !important', height: '3px', backgroundColor: '#0085EF', width: '98%', marginTop: '0px', marginRight: '0px', marginBottom: '-6px', marginLeft: '4px' }} />
                <SendBox
                    //{...sendBoxProps}
                    styles={{
                        textField: {
                            // textAlign: 'left',
                            borderRadius: '0px 0px 15px 15px',
                            border: '0px solid transparent',
                            background: '#F2F2F2',
                            boxShadow: '-3px 6px 17px #D2D2D2, 3px 6px 10px #D2D2D2'
                        }
                    }}
                    onSendMessage={async (content: string) => {
                        let x;
                        //let answer = await askGPT(content);

                        addMessage({
                            messageType: "chat",
                            senderId: "guestId",
                            senderDisplayName: "me",
                            messageId: "msgId",
                            content: content,
                            createdOn: new Date(),
                            mine: true,
                            attached: false,
                            contentType: "text",
                        });

                        let answer = await askGPT(content);

                        addMessage({
                            messageType: "chat",
                            senderId: "botId",
                            senderDisplayName: "bot",
                            messageId: "msgId",
                            content: answer,
                            createdOn: new Date(),
                            mine: false,
                            attached: false,
                            contentType: "text",
                        });

                        return;
                    }}
                    onTyping={async () => {
                        return;
                    }}
                    //onRenderIcon={() => <Icon styles={{root: {color: 'red'}}} iconName="AirplaneSolid" />}
                />
            </div>
        </>
    );
};

export default MyChat;

///////////////////////////////////////////

package.json:

{
  "name": "royal-chat",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@azure/communication-calling": "^1.13.1",
    "@azure/communication-chat": "^1.2.0",
    "@azure/communication-react": "^1.5.0",
    "@fluentui/react": "^8.109.3",
    "@fluentui/react-components": "^9.15.5",
    "@internal/acs-ui-common": "file:internal-acs-ui-common-1.5.1-beta.4.tgz",
    "@internal/northstar-wrapper": "file:internal-northstar-wrapper-1.5.1-beta.4.tgz",
    "@internal/react-components-custom": "file:internal-react-components-1.5.1-beta.4.tgz",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react-hooks": "^3.4.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.49",
    "@types/react": "^16.9.49",
    "@types/react-dom": "^16.9.8",
    "react": "~16.14.0",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^5.0.1",
    "react-test-renderer": "^16.14.0",
    "reactstrap": "^8.4.1",
    "scheduler": "^0.20.2",
    "typescript": "^4.7.4",
    "uuid": "^9.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/uuid": "^8.3.4"
  }
}

**Comment by managedcoder** [comment]
@JoshuaLai and @palatter can we reopen this?  I think I am still having problems with this and my previous post above describes what I am seeing.

**Comment by palatter** [comment]
@managedcoder just reopened this. Let me take a look at the code above and I will investigate and respond later today.

**Comment by managedcoder** [comment]
@palatter , I am happy to share the entire app with you if that would help.

**Comment by palatter** [comment]
@managedcoder, Yes would you be able to send the app? This would be helpful in tracking down your runtime error. Thanks!

**Comment by palatter** [comment]
@managedcoder 

You will need to set it up and set the stateful chat client and chatThreadClient into the provider, wrap the component under those providers.

https://azure.github.io/communication-ui-library/iframe.html?viewMode=docs&id=statefulclient-reacthooks-setup--page#chat

https://github.com/Azure/communication-ui-library/tree/main/samples/ComponentExamples/src

The 2nd example above should show the method to do so.

**Comment by managedcoder** [comment]
I have set those up in App.tsx (see screen grab) but here's the thing... I am trying to use SendBox and MessageThread independently of ACS since I am not using an ACS chat thread to send messages.  Instead, SendBox is sending messages directly to OpenAI using its APIs so there isn't a need for a chatClient or chatThreadClient so they get passed to the providers as null in the screengrab below and perhaps that's why I am getting that error?

In the scenario I just described, should I be trying to use usePropsFor()?  Honestly, I was just trying to get the send icon to show up since it is missing for me and I thought that usePropsFor() would set that.  What capabilities in my scenario would I be missing if I skipped usePropsFor()?  I tried to manually configure the send icon property without any luck but maybe that's what I need to shift to and also set any other properties that might be necessary for those components to work correctly. 

<img width="474" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/a7dcde18-4635-49ad-a2c4-222bbf80bbc9">

**Comment by palatter** [comment]
@managedcoder 

You will have to create your own props for both SendBox and MessageThread. UsePropsFor() relies on having a chatClient/chatThreadClient. Without these, you will need to provide your own implementations of any nonoptional or needed parts of the interface.

Ex. 

![image](https://github.com/Azure/communication-ui-library/assets/73612854/4b17c7e5-db80-43b8-8ce9-a3d1f66a1c01)

**Comment by palatter** [comment]
@managedcoder I hope this solution worked for you. I will close this but feel free to reopen if you still need help.
