### ISSUE TITLE
Question - How can I change the size and justification of elements in MessageThread's items?

### ISSUE THREAD

**Issue by managedcoder** [Azure/communication-ui-library#3123]
I was able to left justiify the text of the MessageThread items but I'd like to change the size of the item's containiner to 80% of the MessageThread's width since they are too narrow (see red dashed box in the screengrab below).  Also, I'd like to right justify the date/time of message.  How would I do that?

<img width="324" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/0b188a4b-ebdf-47ea-9d2d-e33d2b770539">

Here is how I coded the MessageThread component:

<img width="372" alt="image" src="https://github.com/Azure/communication-ui-library/assets/17769186/ae944293-0ef1-472e-971c-323a56534d62">

**Comment by JoshuaLai** [comment]
Hi @managedcoder we have done some investigation on our side and our message components should automatically align and span the width with some small margin. You can look at how we didn't need to change any stylings of width in our code samples here: [UI Components / Message Thread - Message Thread ⋅ Storybook (azure.github.io)](https://azure.github.io/communication-ui-library/?path=/docs/ui-components-messagethread--message-thread) 

You may need to investigate to see if there is another parent style that is overriding it?

**Comment by managedcoder** [comment]
My bad! There was a parent that was causing the problem!  Arrrrgggg!  Sorry for the distraction.  You can close this issue

**Comment by JoshuaLai** [comment]
Thats fine. We are glad it is working as expected for you! 
I will be closing off this issue sine your issue has been resolved.
