### ISSUE TITLE
Question - How to set a custom image for the send icon of SendBox?

### ISSUE THREAD

**Issue by managedcoder** [Azure/communication-ui-library#3133]
I see that I can set styles for the send icon of a SendBox, but what if I wanted to use my own .png image for the send icon?  Can I do that?

**Comment by JoshuaLai** [comment]
Yes you can change the image within the send box. 
Documentation found here: https://azure.github.io/communication-ui-library/?path=/docs/ui-components-sendbox--send-box#customize-send-icon
