### ISSUE TITLE
How to fix issue related to teams user token. I am getting errors to start teams meeting and chat thread using team user token (Getting error 403)in CallWithChatComposite

### ISSUE THREAD

**Issue by tayloramitverma** [Azure/communication-ui-library#3175]
I am facing an issue with the communication service. I am using it for integrating teams' calls and chats for a team user. I am using this (https://github.com/Azure-Samples/communication-services-authentication-hero-nodejs) demo, this demo is based on react & node js.

I am using the `@azure/communication-react` dependency and `CallWithChatComposite` component.

In this component passing props adapter and generating `createAzureCommunicationCallWithChatAdapter`.

I am trying to log in as a team user and using the below-required tokens.

- AAD Access Token
- AAD Token for a Teams user (with Teams.ManageCalls and Teams.ManageChats permissions)
Communication Token
- After adding the meeting link, we are facing the below errors.

Internal request in which we are facing an issue for a chat.

`Request URL:
https://edge.skype.com/registrar/prod/v3/registrations
Request Method:
POST
Status Code:
403
Remote Address:
13.107.3.128:443
Referrer Policy:
strict-origin-when-cross-origin`

Request Payload

`{"clientDescription":{"appId":"AcsWeb","aesKey":"","languageId":"en-US","platform":"SPOOL","templateKey":"AcsWeb_Chat_1.2","platformUIVersion":"0.0.0"},"registrationId":"f65080a4-00c0-48bd-9f0e-72242d95ee3d","nodeId":"","transports":{"TROUTER":[{"context":"","path":"https://trouter-azsc-asse-0-b.trouter.skype.com:3443/v4/f/29mkP0iHw0eRXboLtc0vZw/","ttl":7200}]}}`

Response

`{     
	"message": "Request from CustomTeamsEndpoint contains templateKey 		AcsWeb_Chat_1.2 that is not in the list of allowed templateKeys",     "code": 40305 
}`

We are good in call but this issue is related to chat.

Apart from it, we are facing an issue to display the name of the team's user.

Thanks in advance.

**Comment by jimchou-dev** [comment]
Hi @tayloramitverma, thanks for raising this issue. Currently in `@azure/communication-react`, CTE (as a Teams User using AAD token) is only supported in the Calling scenario and does not support Chat. Unfortunately, that means `createAzureCommunicationCallWithChatAdapter` would not be able to use the Chat part of the functionality. Also, CTE functionality is a feature in public preview and is not recommended for production use, [more info](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/). We appreciate your feedback and will update our documentation to be more clear, indicating CTE only supports Calling at this time through `CallAdapter` (`createTeamsCallAdapter`) with `CallComposite`.

As for your issue with the display name for the Team's user, please have a look at `TeamsAdapterOptions` to specify the `onFetchProfile`.

**Comment by tayloramitverma** [comment]
hi @jimchou-dev , We are using facing issue with display name using Team user.

We are following same react dependencies and your demo code as shared on above.

Some code sample:

`
import {
  createAzureCommunicationCallAdapter,
} from "@azure/communication-react";

createAzureCommunicationCallAdapter({
        userId: { communicationUserId: acsID },
        //displayName: accounts[0].name,
        credential: new AzureCommunicationTokenCredential({
          refreshProactively: true,
          token: acsToken,
          tokenRefresher: async () => {
            const refreshedToken = await getCommunicationTokenForTeamsUser();
            return refreshedToken.acsToken;
          },
        }),
        endpoint: endpoint,
        locator: { meetingLink: meetingLink },
      })
`

Above code is not taking displayName and throw error if we add displayName property:

![image](https://github.com/Azure/communication-ui-library/assets/40193144/a8834ced-87d4-4fd6-a67f-557874abb4b3)


Without passing display name, we are not getting name in remote participants list using SDK.

![image](https://github.com/Azure/communication-ui-library/assets/40193144/141bf1a5-d864-479f-8777-3e7e4d9920d1)

In above you can see both participants are joined using our web version and here display name is missing.

Can you please review and share your views. Thanks
