### ISSUE TITLE
How can share file to remote participants without enable browser permission? 

### ISSUE THREAD

**Issue by tayloramitverma** [Azure/communication-ui-library#3237]
We are integrating Teams Web using Azure SDK and React dependencies for team calls.

Right now, we are stuck with an internal file viewer for remote participants.

Below list of dependencies we are using in our project.

`
  "dependencies": {
    "@azure/communication-calling": "^1.13.1",
    "@azure/communication-calling-effects": "^1.0.1",
    "@azure/communication-chat": "^1.3.1",
    "@azure/communication-common": "^2.2.0",
    "@azure/communication-react": "^1.5.1-beta.5",
    "@azure/msal-browser": "^2.37.0",
    "@azure/msal-react": "^1.5.7",
    "@fluentui/react": "^8.110.2",
    "@fluentui/react-icons": "^2.0.203",
    "axios": "^1.4.0",
    "bootstrap": "^4.5.3",
    "react": "^17.0.1",
    "react-bootstrap": "^1.3.0",
    "react-dom": "^17.0.0"
  }
`

Please review the attached screenshot for your reference.

![image](https://github.com/Azure/communication-ui-library/assets/40193144/dcc41508-faab-4e15-af0c-074803ca63f7)

![image](https://github.com/Azure/communication-ui-library/assets/40193144/b59c0169-1b89-4b08-b212-ca16ee2da97b)

Please review and share your views.

**Comment by alkwa-msft** [comment]
@tayloramitverma can you describe in detail your e2e scenario?
"How can share file to remote participants without enable browser permission?"

The browser permission is used in order to ensure you are set up with your A/V devices for a call.

Sharing a file with remote participants in a call could be done in several ways and understanding more about what you are trying to achieve with your scenario can help us provide a better response.

**Comment by tayloramitverma** [comment]
@alkwa-msft I am trying to present file view to remote users, Like teams has a feature to show files view using browser upload  & One Drive, etc.

I am using communication services with React js for calling and chatting, and want to share screens to present file view.

The default, screenshot required browser permissions to show the Browser tab, Window, and Entire screen but I want to skip this step and only want to present the current team's screen to remote users.

So, Is there any way to skip it like we are showing file view using browser upload or any altered way? please help me.

**Comment by alkwa-msft** [comment]
We use the Chromium API to share the screen and we cannot skip that dialog.

As for seeing a file view if you are referring to how LiveShare works in teams. This is something we do not support today through the Calling SDK and so we don't offer that in the UI Library as well.

**Comment by tayloramitverma** [comment]
Thanks for your valuable support.
