### ISSUE TITLE
Cannot start local video on call join using videoOptions

### ISSUE THREAD

**Issue by sayayinR** [Azure/communication-ui-library#3264]
**Describe the bug; what happened?**
I would like to give user the option to turn on video before the call starts. According to the documentation I believe that can be achieved by providing a local stream in videoOptions on call.join(). I am using the LocalVideoStream class from communication-calling package to create a localStream. My code is almost identical to what you have in your communication-react package yet the code errors out on new LocalVideoStream(videoDeviceInfo) 

![image](https://github.com/Azure/communication-ui-library/assets/11239820/c60f2be4-e4fb-4568-832b-88e4bfff5147)

I can see the videoDeviceInfo has the correct type. 

**What are the steps to reproduce the issue?**
On useEffect of the component create a local stream and provide that to videoOptions on call.join()

**What behavior did you expect?**
I would expect the call to start with video stream on.

**If applicable, provide screenshots:**
Code to create local stream:

![image](https://github.com/Azure/communication-ui-library/assets/11239820/6c5ca8bd-944e-4a9c-b680-8a3e782da562)

Error:
line 142 throws the exception
![image](https://github.com/Azure/communication-ui-library/assets/11239820/b66952dd-7c32-4d04-bcf0-207785fb0f03)

Video device info being passed to LocalVideoStream:

![image](https://github.com/Azure/communication-ui-library/assets/11239820/0c4656a6-eb2b-42aa-b86d-686080c11eca)

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): "^1.5.0"
- `@azure/communication-calling` npm package version (if applicable):  "^1.10.1"
- `@azure/communication-chat` npm package version (if applicable): "1.2.0"

- OS & Device: Windows 10 on PC
- Browser: Chrome 
- Browser Version: Version 114.0.5735.134 (

**Is there any additional information?**

**Comment by prabhjot-msft** [comment]
@sayayinR thanks for filing the issue. We are currently looking into the issue, will update you here with more information regarding the status.

**Comment by sayayinR** [comment]
Thank you!

**Comment by sayayinR** [comment]
Hi! I'm closing this issue.. I believe this issue might just be happening for me. I was creating a package of the app and then reusing it in another project, It might be a build issue related to communication-calling. Atleast that's what I am thinking right now. So I will close this for now and if anything changes I will open it again.
Thank you!
