### ISSUE TITLE
position of the floatinglocalvideo to top right?

### ISSUE THREAD

**Issue by alkwa-msft** [Azure/communication-ui-library#3342]
### Discussed in https://github.com/Azure/communication-ui-library/discussions/3328

<div type='discussions-op-text'>

<sup>Originally posted by **tj36** July 11, 2023</sup>
Hello,

I would like to know how can I change the position of the floatinglocalvideo to top right when using video gallery. Also, I don't see any styles property to set the dimensions(height and width) for the floating local video. Please let me know if there is any property that can be used. Thanks.

```
<VideoGallery
{...videoGalleryProps}
localVideoViewOptions={{ scalingMode: 'Fit' }}
remoteVideoViewOptions={{ scalingMode: 'Fit' }}
layout="floatingLocalVideo"
>
```</div>

**Comment by carocao-msft** [comment]
Hi, I'm looking into this, thanks for raising this issue!

**Comment by carocao-msft** [comment]
Hi, we currently don't support changing the local video tile position in the overflow gallery. However for changing the size of local video tile, you can use onRenderLocalVideoTile to create your own local video tile and pass it back to the video gallery component. Let me know if this resolves your question. Thanks!

**Comment by tj36** [comment]
Hello,
Thanks for responding. Do you know if there is any proposed update for changing the position?
Also, can you please share an example on how to change the size of the video tile?

Thank you :)

**Comment by mgamis-msft** [comment]
Hi @tj36, we currently don't support changing the size of the local video tile. That is something the VideoGallery changes based on its width and height. You can change what is rendered within the local video tile using `onRenderLocalVideoTile ` property but it cannot handle rendering a fixed size element this simple example:
```
export const FloatingLocalVideoExample: () => JSX.Element = () => {
  const containerStyle = { height: '50vh' };
  return (
    <Stack style={containerStyle}>
      <VideoGallery
        layout="floatingLocalVideo"
        localParticipant={MockLocalParticipant}
        remoteParticipants={MockRemoteParticipants}
        onRenderLocalVideoTile={() => <div style={{ backgroundColor: 'red', height: '50px', width: '50px' }} />}
      />
    </Stack>
  );
};
```
which results in this:
![image](https://github.com/Azure/communication-ui-library/assets/79475487/8732026d-cc21-451f-9c5b-aa1e842b962f)

Let me know if you would to request a feature to change the local video size and I will put it in our backlog for our PM to spec. Do keep in mind that for this feature you would need to handle the size of the local video tile when the VideoGallery changes size.

**Comment by tj36** [comment]
@mgamis-msft Thanks for explaining it with an example. I would really appreciate it if you could create a feature request. I am looking forward for a version which has the changes for resizing and positioning of the local video tile. 

Thank you. :)

**Comment by mgamis-msft** [comment]
@tj36 I have discussed this feature request for changing the size and position of video tile with my team and we can't plan this feature for foreseeable future due to many features we already have planned.
Sorry for the inconvenience. An alternative solution would be to build your own video gallery with [VideoTile](https://azure.github.io/communication-ui-library/?path=/docs/ui-components-videotile--video-tile) while still using the same `videoGalleryProps` so you still have remote participant info.

**Comment by JamesBurnside** [comment]
Closing this issue as stale. Please comment or create a new issue and reference this if this is still a blocking issue.
