### ISSUE TITLE
What are the best practices for synchronizing Identity Service and StatefulChatClient?

### ISSUE THREAD

**Issue by alkwa-msft** [Azure/communication-ui-library#3343]
### Discussed in https://github.com/Azure/communication-ui-library/discussions/3326

<div type='discussions-op-text'>

<sup>Originally posted by **BrianUribe6** July 10, 2023</sup>
Hi, I have a requirement that involves maintaining a mapping between each user and the chat threads they belong to. I know this information is already provided by the ChatClient and the ChatThreadClient, but because this data will be queried very often, I have persisted this on a service that will store and format it according to business requirements. 

The challenge, however, is keeping ACS state and this "Identity Service" in sync and I was wondering on what are the best practices for something like this?  I know a naive approach is listening to every event on the client ("threadCreated", "participantAdded", etc) and updating the Identity Service accordingly, but since the events are coming directly from the client this is unreliable.

How would I reliably keep ACS and my locally persisted data in sync?</div>

**Comment by jimchou-dev** [comment]
Hi @baanders, thanks for sharing this question regarding user/thread management. I may require some additional information on how you are working with the chat threads. But briefly explaining the concept of a chat thread is of the following:

Threads Management
- An user identity (userId/token) can create a chat thread (they will be included in that chat thread themselves)
- Any user in a chat thread can delete a chat thread

User Management
- Only an user that is in an existing chat thread can invite/add another user (by userId) to that existing chat thread
- Other user cannot just `Join` a chat thread themselves, they need to be added by someone already in the chat thread
- An user can remove anyone in the chat thread or they can remove themselves from the chat thread they are in
- Without being removed by someone or leaving a chat thread or chat thread being deleted, a user will remain in a chat thread but may have a expired token and can simply renew the token for that userId (except for Teams Interops, see next point)
- In a Teams Interops scenario (CallWithChat) the ACS user is added to the chat thread when admitted into the meeting, and removed from the chat thread when leave/removed from the meeting call

If you need to know all the mappings between chat thread and users accurately, we recommend to have ALL thread management (create/delete thread) and ALL user thread events (add user to thread, remove user from thread) to be done on your server side, so when you make a call to ChatSDK you can also update in your mapping records.

For more information please have a look https://learn.microsoft.com/en-us/azure/communication-services/concepts/chat/concepts to better understand chat.

**Comment by BrianUribe6** [comment]
@jimchou-dev Thanks for the detailed response. It answers all my initial concerns :)
