### ISSUE TITLE
Paperclip Button for File Attachments Not Displaying in ChatComposite

### ISSUE THREAD

**Issue by bogdanmartinescu** [Azure/communication-ui-library#3386]
I am using the ChatComposite component from the @azure/communication-react package (version 1.6.0) to implement a chat feature in my Framework7 mobile app. However, I am facing an issue where the paperclip button for file attachments is not displaying within the ChatComposite.

I have configured the fileSharing option in the ChatComposite with proper uploadHandler and downloadHandler functions for file sharing. Despite the upgrade to version 1.6.0, the button is still not visible.

**Steps to Reproduce:**
- Install @azure/communication-react version 1.6.0.
- Implement the ChatComposite component with the file sharing options and appropriate handlers (uploadHandler and downloadHandler).
- Authenticate the user and open the ChatComposite view.

**Expected Result:**
The ChatComposite should display a paperclip button for file attachments, allowing users to upload and download files.

**Actual Result:**
The paperclip button for file attachments is missing from the ChatComposite view, and users are unable to perform file sharing actions.

**Additional Information:**
I have tried testing the application in multiple environments (development, staging, production), but the issue persists.
There are no console errors or warnings related to the ChatComposite or file sharing functionality.
No custom CSS styles have been applied to the ChatComposite that could hide the button.

**Environment:**
@azure/communication-react: v1.6.0
React: 18.2.0
Browser: Google Chrome
Operating System: MacOS

Any assistance or insights into resolving this issue would be greatly appreciated. Thank you!

**Comment by jpeng-ms** [comment]
Hi @bogdanmartinescu,

Thanks for your patience, the file sharing feature is currently in public preview and isn't available in `1.6.0`. I was able reproduce this issue and the attachment icon ("paperclip button") is indeed not available in this version.

To leverage this feature, please consider to use the beta version of the UI library. Furthermore, you can take a look of [this documentation](https://learn.microsoft.com/en-us/azure/communication-services/tutorials/file-sharing-tutorial) or check out the [sample project](https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-filesharing-chat-composite)

Please let me know if you have any more questions.

Thanks,
John

**Comment by bogdanmartinescu** [comment]
Hello @jpeng-ms ,

Thanks for pointing that out, managed to display the paperclip button in the end.

Thanks for your help!

**Comment by jpeng-ms** [comment]
No problem! Glad to know you got it working. I will go ahead and close this issue. Feel free to let me know if you run into any issues. Thanks!
