### ISSUE TITLE
Support for Call Recording, Take Control and Chat Download features

### ISSUE THREAD

**Issue by ajeetkumar142022** [Azure/communication-ui-library#3405]
We have used this repo for understand Azure communication service and implement it. we are stuck on 
* "Call recording feature", 
* "Take control"
* "Chat Download".

please guide us for implement above features

- "@azure/communication-calling": "1.15.1-beta.1 || >=1.14.1",
- "@azure/communication-chat": "1.3.2-beta.3 || >=1.2.0",
- "@azure/communication-react": "1.7.0-beta.1",
OS & Device: Web

**Comment by mgamis-msft** [comment]
Hi @ajeetkumar142022, thanks for filing this issue. We currently don't support "Call recording feature", "Take control" because the @azure/communication-calling, the package we depend on, does not support this feature yet.

**Comment by jpeng-ms** [comment]
Hi @ajeetkumar142022 this is John. I was wondering what do you mean by getting stuck on Chat Download? Would you mind to clarify the type of Chat experience are you building? Is it an ACS chat or Teams interoperability Chat? Also would you mind to let us know what exactly are you stuck on?

**Comment by JamesBurnside** [comment]
For call recording, you check out this quickstart: https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/02e958ee8cec2a5efa1d42cefec7bb8d4f13a73a/ui-library-add-call-recording.

Please note this quickstart was developed when the call recording feature was in public preview and hence uses `beta` packages. You can find the general availability documentation for call recording here as the APIs may have changed slightly: https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-call-recording?pivots=programming-language-javascript. The custom button injection used in this sample is still in public preview and not recommended for production sites.

**Comment by jpeng-ms** [comment]
Hi @ajeetkumar142022 I will be closing off this issue for now since we haven't heard back from you in a while. Please feel free to reach out back to us if you have any more questions.
