### ISSUE TITLE
Type Definition Issue with SendBoxProps for SendBox Component

### ISSUE THREAD

**Issue by jessihamel** [Azure/communication-ui-library#3428]
**Describe the bug; what happened?**

According to the prop types for the SendBox Component we should be able to pass a callback that registers after a message is sent.

From the [documentation](https://learn.microsoft.com/en-us/javascript/api/%40azure/communication-react/sendboxprops?view=azure-node-latest):

onSendMessage | Optional callback called when message is sent | onSendMessage?: (content: string) => Promise<void>

However, when an empty promise is passed, the message in the send box is never sent.

```jsx
<SendBox
    {...sendBoxProps}
    onSendMessage={(content) =>
        new Promise((resolve) => {
            // Message is never sent
        })
    }
/>
```

**What behavior did you expect?**

From the documentation, I expected this prop to be a way to fire side effects "when the message is sent", but passing any function here seems to break message sending from the ChatBox component.

**In what environment did you see the issue?**

-  "@azure/communication-react": "1.6.0",
- "@azure/communication-chat": "1.3.1",

- OS & Device: MacOS
- Browser: Mozilla FireFox
- Browser Version: 115.0.2

**Comment by JoshuaLai** [comment]
@jessihamel thanks for raising the issue, I will investigate and provide updates

**Comment by JoshuaLai** [comment]
Hi @jessihamel I think this is mistake in documentation on our side. The documentation seems to imply that this is a callback but instead its an override. 
https://azure.github.io/communication-ui-library/?path=/docs/statefulclient-reacthooks-useselector--page#write-your-own-handler-function

**Comment by JoshuaLai** [comment]
Updating docs with a quick PR: https://github.com/Azure/communication-ui-library/pull/3433

**Comment by JoshuaLai** [comment]
Sorry for the confusion, I have updated the documentation to make it a bit more clear. Please let me know if there are any more questions.

**Comment by jessihamel** [comment]
This makes sense now. Thank you for the update.
