### ISSUE TITLE
Screen Sharing fails, Unsupported Streams on mobile version of browsers.

### ISSUE THREAD

**Issue by jorgecolon413** [Azure/communication-ui-library#3488]
**Describe the bug; what happened?**
^^When trying to do a Screen Share from a mobile device (Google Chrome, Safari), it throws the UnsupportedStream Error. Every other functionality of the azure communication ui library and sdk works fine in my react.js ts app. It works as intended when doing the same test on a desktop browser. 

**What are the steps to reproduce the issue?**
Make a call to the another user and press the share screen button on a mobile device's browser. 

**What behavior did you expect?**
To be able to share the screen, the same way as in a desktop browser client.

**If applicable, provide screenshots:**
![chrome-capture-2023-7-21 (3)](https://github.com/Azure/communication-ui-library/assets/58268872/ee21d915-5a54-496d-9756-20e7424c4bea)

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): 1.7.0-beta.2
- `@azure/communication-calling` npm package version (if applicable) :1.15.1-beta.1
- `@azure/communication-chat` npm package version (if applicable): ^1.2.0

- OS & Device:  iOS, Windows on iPhone 13, PC, Pixel 7 pro]
- Browser: Google Chrome, Apple Safari 
- Browser Version: 115.0.5790.173

**Is there any additional information?**
This is my callling component with all the components for the call ux:
```
import {
  usePropsFor,
  VideoGallery,
  ControlBar,
  CameraButton,
  MicrophoneButton,
  ScreenShareButton,
  EndCallButton,
  ParticipantsButton,
  VideoStreamOptions
} from '@azure/communication-react';
import React, { useCallback } from 'react';

export type CallingComponentsProps = {
  endingCall: () => void;  
}



function CallingComponents(props: CallingComponentsProps): JSX.Element {
  // Extracting props for communication components
  const participantsButtonProps = usePropsFor(ParticipantsButton);
  const videoGalleryProps = usePropsFor(VideoGallery);
  const cameraProps = usePropsFor(CameraButton);
  const microphoneProps = usePropsFor(MicrophoneButton);
  const screenShareProps = usePropsFor(ScreenShareButton);
  const endCallProps = usePropsFor(EndCallButton);


  // Handler for ending the call
  const onHangup = useCallback(async (): Promise<void> => {    
    await endCallProps.onHangUp(true);    
    props.endingCall();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [endCallProps]);

  const localVideoViewOption: VideoStreamOptions = {
    scalingMode: 'Crop',
    isMirrored: true,
    
  };

  const remoteVideoViewOption: VideoStreamOptions = {
    scalingMode: 'Crop',
    isMirrored: true,
    
  };

  // Render the calling components
  return (
    // <Stack style={{ backgroundColor: "#f5f5f5"}}/*className={mergeStyles({ height: '100%' })}*/> 74vw
  <div style={{ width: '100%', height: '70vh', backgroundColor: "#f5f5f5" }}>{/*80vh*/}
      <div style={{height: '100%'}}>
        {videoGalleryProps &&
          <VideoGallery  layout='floatingLocalVideo' 
            localVideoViewOptions={localVideoViewOption}
            remoteVideoViewOptions={remoteVideoViewOption}
            {...videoGalleryProps} />}
      </div>

      <div style={{ alignContent: "end" }}>
        <ControlBar layout="floatingBottom">
          {cameraProps && <CameraButton {...cameraProps} />}
          {microphoneProps && <MicrophoneButton {...microphoneProps} />}
          {screenShareProps && <ScreenShareButton {...screenShareProps} />}
          {participantsButtonProps && <ParticipantsButton {...participantsButtonProps} />}
          {endCallProps && <EndCallButton {...endCallProps} onHangUp={onHangup} />}
        </ControlBar>
      </div>
    </div>
    // </Stack> 
  );
}

export default CallingComponents;
```

This is how a make the call :
```
//Make a call
    useEffect(() => {
        if (participantId && callAgent && callOption && !call) {
            console.log(`Making call to ${participantId}`);
            const makeCall = async () => {
                try {
                    deviceManager?.askDevicePermission({ video: true, audio: true });
                    //const videoOptions = isMobile ? await createLocalVideoStreamAsVideoOption() : undefined;  start with camera on                  
                    setCall(callAgent.startCall([{ communicationUserId: participantId }])); //], { videoOptions }                                     
                    // Additional call handling can be done here
                } catch (error) {
                    setCall(undefined);
                    console.error(`Error making the call: ${error}`);
                }
            }
            makeCall();
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [participantId, callAgent, callOption]);
```
Console Log with the error:
[teamsroomsmpr.azurewebsites.net-1692639165870.log](https://github.com/Azure/communication-ui-library/files/12399146/teamsroomsmpr.azurewebsites.net-1692639165870.log)

If there's more info needed to see this issue, pls let us know. Thanks in advanced!

**Comment by dmceachernmsft** [comment]
Hi @jorgecolon413! Thanks for filing the issue! At a first glance you are doing everything correctly for your components. However according to the MDN docs the screen capture API's are not supported on any mobile browser. 

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture 

Given this we also make the decision in our composites when they are in the `mobile` formfactor we also disable screen share for phone users. We unfortunately won't be able to support this scenario until the web API's catch up to what we want to do here.

Hope this information is helpful!
