### ISSUE TITLE
Integrating file sharing with ChatStatefulClient

### ISSUE THREAD

**Issue by alkwa-msft** [Azure/communication-ui-library#3505]
### Discussed in https://github.com/Azure/communication-ui-library/discussions/3463

<div type='discussions-op-text'>

<sup>Originally posted by **AlbertoPerez8** August 16, 2023</sup>
Is there any documentation or outlined steps on adding file sharing functionality to a chat app that runs with Chat Clients Provider components? Or is is better to implement a custom message case and use the communications SDK and sending the message independently from the chat client provider component?</div>

**Comment by jimchou-dev** [comment]
Hi @AlbertoPerez8, thank you for the question regarding file sharing.

There is no direct documentation for adding file sharing functionality for ChatClientProvider components, but there is some sample code that will be useful as a reference if you are planning to use Azure Storage for file sharing. Please have the quickstart for [ui-library-filesharing-ui-components](https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-filesharing-ui-components), specifically the `ChatComponents.tsx` file will help you understand how uploading/downloading works with Azure Storage.

In addition please check out the storybook page for related for component file sharing. But keep in mind this file sharing does not work in TeamsInterops scenario (teams user will not able to see the attachments)
file upload: https://azure.github.io/communication-ui-library/?path=/docs/ui-components-messagethread--message-thread#display-file-attachments-with-messages
file download: https://azure.github.io/communication-ui-library/?path=/docs/ui-components-messagethread--message-thread#display-file-attachments-with-messages
