### ISSUE TITLE
CallWithChatComposite doesn't work well with next js

### ISSUE THREAD

**Issue by AbhishekRauthan-09** [Azure/communication-ui-library#3517]
the issue exists when i use azure active communication ui library components in next js. when some error occured in the adapter like sometimes it gives error that call already exists with this acs token it get freezed and did not go further and cut the previous call and make new one. but in react it does it cut the old call and create a new one and did not throw any error and website runs well

```[tasklist]
### Tasks
```

**Comment by carocao-msft** [comment]
Hi, thanks for raising this issue, we are looking into this!

**Comment by carocao-msft** [comment]
Hi, Do you mind sharing the ui library version you are currently using and the next js version you have? Thanks!

**Comment by JamesBurnside** [comment]
@AbhishekRauthan-09 could you also confirm if next js is running react strict mode and if disabling strict mode helps the issue

**Comment by Leah-Xia-Microsoft** [comment]
We are closing this issue since we haven’t heard back from you for 10 days. Feel free to reopen this issue if you have any questions.
