### ISSUE TITLE
An error is displayed when entering a room with Background Effect set

### ISSUE THREAD

**Issue by nasu38yen** [Azure/communication-ui-library#3555]
I would like to be able to set the background of LocalVideo! Since there are many requests for this, we are verifying the version upgrade of UILibrary.
I installed @azure/communication-react@1.8.0-beta.1.
On the screen before entering the room, turn on the camera, click the effect icon to set the background, and enter the room.
An error appears when a video with background effects appears briefly and then turns off.
Cannot read properties of null(reading 'setBackground')
at @azure/communication-calling-effects
So it may not be a problem with UILibrary, but
Similarly, when running Samples in UILibrary, the video will be turned off once after entering the room, but no error will be displayed.
My CallScreen.tsx code is almost the same as that of Samples, so I don't know why an error is displayed only here.
The error just appears and then the video with background turns back on and there are no other issues.
Is there a way to prevent the error from being displayed?
![image](https://github.com/Azure/communication-ui-library/assets/4310058/c3b04c2b-cb52-430c-9fe1-54051d48af15)

**Comment by JamesBurnside** [comment]
@nasu38yen thanks for reporting this issue! To help you further, could you provide a code snippet for how you are creating the azure communication callwithchat adapter and how this is being passed into the callwithchatcomposite?

**Comment by nasu38yen** [comment]
from myproject's package.json
`  "dependencies": {
    "@azure/communication-calling": "1.16.3-beta.1",
    "@azure/communication-chat": "1.4.0-beta.1",
    "@azure/communication-common": "^3.0.0-beta.1",
    "@azure/communication-identity": "1.2.0",
    "@azure/communication-react": "^1.8.0-beta.1",`

And My Whole code in CallScreen.tsx
`// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// import { GroupCallLocator, TeamsMeetingLinkLocator } from '@azure/communication-calling';
import { CommunicationUserIdentifier } from '@azure/communication-common';
import {
  // CallAdapter,
  // CallAdapterState,
  // CallComposite,
  // createAzureCommunicationCallAdapter,

  CallAndChatLocator,
  CallWithChatAdapter,
  CallWithChatAdapterState,
  CallWithChatComposite,
  useAzureCommunicationCallWithChatAdapter, 
  toFlatCommunicationIdentifier,
  COMPOSITE_LOCALE_JA_JP,
  CallWithChatCompositeOptions
} from '@azure/communication-react';

import { onResolveVideoEffectDependencyLazy, AzureCommunicationCallAdapterOptions } from '@azure/communication-react';
//import { onResolveVideoEffectDependency, AzureCommunicationCallAdapterOptions } from '@azure/communication-react';

import { Stack, Spinner } from '@fluentui/react';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useSwitchableFluentTheme } from '../theming/SwitchableFluentThemeProvider';
import { createAutoRefreshingCredential } from '../utils/credential';
import MobileDetect from 'mobile-detect';

import {containerStyle } from '../styles/CallScreen.styles';

import { Header } from './Header';

const detectMobileSession = (): boolean => !!new MobileDetect(window.navigator.userAgent).mobile();
const isIpad = (): boolean => {
  const ua = window.navigator.userAgent;
  if (ua.indexOf('iPad') > -1) {
      return true;
  }

  if (ua.indexOf('Macintosh') > -1) {
      try {
          document.createEvent("TouchEvent");
          return true;
      } catch (e) {}
  }
  return false; 
};

export interface CallScreenProps {
  token: string;
  userId: CommunicationUserIdentifier;
  // callLocator: GroupCallLocator | TeamsMeetingLinkLocator;
  callLocator: CallAndChatLocator;
  displayName: string;
  roomName: string;
  endpointUrl: string;
  webAppTitle: string;
  onCallEnded: () => void;
}

export const CallScreen = (props: CallScreenProps): JSX.Element => {
  const { token, userId, callLocator, displayName, roomName, endpointUrl, webAppTitle, onCallEnded } = props;
  
  // const [adapter, setAdapter] = useState<CallAdapter>();
  // const adapterRef = useRef<CallAdapter>();
  // 2023.8.30 createAdapter→useAdapterに変更
  //const [adapter, setAdapter] = useState<CallWithChatAdapter>();
  //const adapterRef = useRef<CallWithChatAdapter>();

  // 2023.8.29 背景効果を有効にする 
  /* @conditional-compile-remove(video-background-effects) */
  const callAdapterOptions: AzureCommunicationCallAdapterOptions = useMemo(() => {
    const videoBackgroundImages = [
      {
        key: 'ab1',
        url: '/backgrounds/contoso.png',
        tooltipText: 'Custom Background'
      },
      {
        key: 'ab2',
        url: '/backgrounds/abstract2.jpg',
        tooltipText: 'Custom Background'
      },
      {
        key: 'ab3',
        url: '/backgrounds/abstract3.jpg',
        tooltipText: 'Custom Background'
      },
      {
        key: 'ab4',
        url: '/backgrounds/room1.jpg',
        tooltipText: 'Custom Background'
      },
      {
        key: 'ab5',
        url: '/backgrounds/room2.jpg',
        tooltipText: 'Custom Background'
      },
      {
        key: 'ab6',
        url: '/backgrounds/room3.jpg',
        tooltipText: 'Custom Background'
      },
      {
        key: 'ab7',
        url: '/backgrounds/room4.jpg',
        tooltipText: 'Custom Background'
      }
    ];
    return {
      videoBackgroundOptions: {
        videoBackgroundImages,
        /* @conditional-compile-remove(video-background-effects) */
        onResolveDependency: onResolveVideoEffectDependencyLazy
        //onResolveDependency: onResolveVideoEffectDependency
      }
    };
  }, []);
  
  // 2023.8.25
  // localVieoTileとは関係なかったTT
  const callWithChatCompositeOptions : CallWithChatCompositeOptions = useMemo(
    () => ({
      galleryOptions: { layout: 'default' },
    }),
    []
  );

  // Whenever the sample is changed from desktop -> mobile using the emulator, make sure we update the formFactor.
  useEffect(() => {
    COMPOSITE_LOCALE_JA_JP.component.strings.microphoneButton.offLabel = 'マイクをオンにする';
    COMPOSITE_LOCALE_JA_JP.component.strings.microphoneButton.tooltipOffContent = 'マイクをオンにする';
    COMPOSITE_LOCALE_JA_JP.component.strings.microphoneButton.onLabel = 'マイクをオフにする';
    COMPOSITE_LOCALE_JA_JP.component.strings.microphoneButton.tooltipOnContent = 'マイクをオフにする';
    COMPOSITE_LOCALE_JA_JP.component.strings.cameraButton.offLabel = 'カメラをオンにする';
    COMPOSITE_LOCALE_JA_JP.component.strings.cameraButton.tooltipOffContent = 'カメラをオンにする';
    COMPOSITE_LOCALE_JA_JP.component.strings.cameraButton.onLabel = 'カメラをオフにする';
    COMPOSITE_LOCALE_JA_JP.component.strings.cameraButton.tooltipOnContent = 'カメラをオフにする';
    COMPOSITE_LOCALE_JA_JP.component.strings.screenShareButton.offLabel = '画面を共有する';
    COMPOSITE_LOCALE_JA_JP.component.strings.screenShareButton.tooltipOffContent = '画面を共有する';
    COMPOSITE_LOCALE_JA_JP.component.strings.screenShareButton.onLabel = '画面共有を停止する';
    COMPOSITE_LOCALE_JA_JP.component.strings.screenShareButton.tooltipOnContent = '画面共有を停止する';
    COMPOSITE_LOCALE_JA_JP.component.strings.endCallButton.tooltipContent = '退出';
    COMPOSITE_LOCALE_JA_JP.strings.callWithChat.peopleButtonLabel = '参加者';

    const updateIsMobile = (): void => setIsMobileSession(detectMobileSession() || isIpad());
    window.addEventListener('resize', updateIsMobile);
    document.body.style.overflow = 'hidden';
    return () => { 
      window.removeEventListener('resize', updateIsMobile);
      document.body.style.overflow = 'null';
    }
  }, []); 

  const callIdRef = useRef<string>();
  const { currentTheme, currentRtl } = useSwitchableFluentTheme();
  const [isMobileSession, setIsMobileSession] = useState<boolean>(detectMobileSession() || isIpad());

  const credential = useMemo(
    () => createAutoRefreshingCredential(toFlatCommunicationIdentifier(userId), token),
    [userId, token]
  );

  const afterAdapterCreate = useCallback(
    async (adapter: CallWithChatAdapter): Promise<CallWithChatAdapter> => {
      adapter.on('callEnded', () => {
        onCallEnded();
      });
      adapter.on('callError', (e) => {
        // Error is already acted upon by the Call composite, but the surrounding application could
        // add top-level error handling logic here (e.g. reporting telemetry).
        console.log('Adapter error event:', e);
      });
      adapter.on('chatError', (e) => {
        // Error is already acted upon by the Chat composite, but the surrounding application could
        // add top-level error handling logic here (e.g. reporting telemetry).
        console.log('Adapter error event:', e);
      });
      adapter.onStateChange((state: CallWithChatAdapterState) => {
        const pageTitle = convertPageStateToString(state);
        document.title = `${pageTitle} - ${webAppTitle}`;

        if (state?.call?.id && callIdRef.current !== state?.call?.id) {
          callIdRef.current = state?.call?.id;
          console.log(`Call Id: ${callIdRef.current}`);
        }
      });
      return adapter;
    },
    [callIdRef]
  );
  
  const adapter = useAzureCommunicationCallWithChatAdapter(
    {
      userId,
      displayName,
      credential,
      endpoint: endpointUrl,
      locator: callLocator,
      callAdapterOptions
    },
    afterAdapterCreate
  );

  // Dispose of the adapter in the window's before unload event.
  // This ensures the service knows the user intentionally left the call if the user
  // closed the browser tab during an active call.
  useEffect(() => {
    const disposeAdapter = (): void => adapter?.dispose();
    window.addEventListener('beforeunload', disposeAdapter);
    return () => window.removeEventListener('beforeunload', disposeAdapter);
  }, [adapter]);

  if (!adapter) {
    return <Spinner label={'Creating adapter'} ariaLive="assertive" labelPosition="top" />;
  }

  return (
      <Stack className={containerStyle}>
        <Header roomName={roomName} />
        <CallWithChatComposite
          adapter={adapter}
          fluentTheme={currentTheme.theme}
          rtl={currentRtl}
          // callInvitationUrl={window.location.href}
          formFactor={isMobileSession ? 'mobile' : 'desktop'}
          locale={COMPOSITE_LOCALE_JA_JP}

          // 23/8/25 1.7.1で追加
          options={callWithChatCompositeOptions}
        />
      </Stack>
  );
};

const convertPageStateToString = (state: CallWithChatAdapterState): string => {
  switch (state.page) {
    case 'accessDeniedTeamsMeeting':
      return 'error';
    case 'leftCall':
      return 'end call';
    case 'removedFromCall':
      return 'end call';
    default:
      return `${state.page}`;
  }
};`

**Comment by JamesBurnside** [comment]
Hi @nasu38yen, your code looks good, trying it locally I can see the effects correctly apply:

| config screen | call screen |
| -- | -- |
| ![image](https://github.com/Azure/communication-ui-library/assets/2684369/519783ad-fe15-433f-86fa-505f22252880) | ![image](https://github.com/Azure/communication-ui-library/assets/2684369/e0ba5ba4-0561-4c86-a118-7f31ed24e1ab) |

We'll take this issue to the owners of the `@azure/communication-calling-effects` package. To do so, could you share a `callId` that contains a repro of the scenario? You can find the callId under `adapter?.getState().call?.id;` as well as the full error stack (and any other notable errors in the console)

**Comment by nasu38yen** [comment]
Thanks for your reply.

config screen
![screen1](https://github.com/Azure/communication-ui-library/assets/4310058/eaa4ec8e-1105-4a5e-a91f-6fbaef1ca85f)

calling screen
![screen2](https://github.com/Azure/communication-ui-library/assets/4310058/b13f0590-dfbf-403b-b550-ac28e0f721f1)

error displayed
![screen3](https://github.com/Azure/communication-ui-library/assets/4310058/87025236-e9e6-49a0-95c0-e90ea5114b73)

close error overlay
![screen4](https://github.com/Azure/communication-ui-library/assets/4310058/255ad771-fce0-4ea1-910f-96b37739b723)

on the fourth screen F12 console log
I think the callid is Call Id: 23a8eed9-11fa-4665-a0a5-125753a9f5d1


```
[webpack-dev-server] Server started: Hot Module Replacement enabled, Live Reloading enabled, Progress disabled, Overlay enabled.
log.js:39 [HMR] Waiting for update signal from WDS...
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
App.tsx:32 Net4U Meeting app. Last Updated 2023/9/13 13:55:49 Using @azure/communication-calling:1.16.3-beta.1
2sdk.bundle.js:196 ECS - Config fetch complete
sdk.bundle.js:196 ECS - Delaying User config fetch until we have a valid SkypeToken
sdk.bundle.js:196 ECS - Config fetch complete
sdk.bundle.js:196 config updated callback
CallScreen.tsx:187 Call Id: 23a8eed9-11fa-4665-a0a5-125753a9f5d1
sdk.bundle.js:196 config updated callback
sdk.bundle.js:5 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setBackground')
    at t.eval (sdk.bundle.js:5:3033051)
    at eval (sdk.bundle.js:5:3032452)
    at Object.eval [as next] (sdk.bundle.js:5:3032572)
    at i (sdk.bundle.js:5:3031196)
```

**Comment by JamesBurnside** [comment]
Thank you for sharing these details, we've forwarded to the owners of the `@azure/communication-calling-effects` package and will keep this thread updated.

**Comment by nasu38yen** [comment]
After updating the reference package to the latest version and trying again, this problem seems to be resolved.
Thanks but another problem. I start the CallWithChat sample, enter the room, click the Present button on the control bar, and cancel in the dialog that appears, an error will be displayed.
![image](https://github.com/Azure/communication-ui-library/assets/4310058/444671ee-3edf-4ad7-b57b-39e0ed305411)

**Comment by dmceachernmsft** [comment]
Hi @nasu38yen! this is a known issue with the calling SDK and how windows handles cancelling a screen share. this error will not be visible in production and you will be able to screenshare in the future after seeing this error.

Apologies for the late reply! we encourage filing new issues for different problems to increase the visibility to us and to other members of the community. Glad to hear your original issue was fixed! 😊

**Comment by nasu38yen** [comment]
Thank you for your reply.
Sorry for adding another issue.
Please close this matter.

**Comment by dmceachernmsft** [comment]
Closing as issue resolved, please re-open if the original issue persists
