### ISSUE TITLE
localVideoTile property is missing from CallWithChatCompositeProps

### ISSUE THREAD

**Issue by nasu38yen** [Azure/communication-ui-library#3556]
Although it is in CallCompositeOptions and I can stop floating,
I don't understand why I can't do that with CallWithChatComposite.
There are many requests for this, so please don't forget to add it in the next version.

**Comment by JamesBurnside** [comment]
Thanks for reporting this, we'll discuss this and report back as soon as possible if we will add this to callwithchatcomposite.
