### ISSUE TITLE
Screen sharing blocked after close the chat component in CallWithChatComposite

### ISSUE THREAD

**Issue by davidegemma** [Azure/communication-ui-library#3804]
**Describe the bug; what happened?**

In CallWithChatComposite component, if screen sharing is enabled, when i close the chat component, sharing is blocked until i click another button.

**What are the steps to reproduce the issue?**

1. Start the videocall
2. share your screen on the other end of the video call
3. Open the chat component
4. Wait a few seconds
5. Close the chat component

**What behavior did you expect?**

I expect screen sharing to continue to work

**If applicable, provide screenshots:**

<img width="1438" alt="Screenshot 2023-11-16 at 17 32 12" src="https://github.com/Azure/communication-ui-library/assets/44259628/104fabfa-4b57-4310-8702-1df6683665fd">

**In what environment did you see the issue?**

I inserted the component CallWithChatComponent into a react web application

- `@azure/communication-react` npm package version (if applicable):  1.8.0
- `@azure/communication-calling` npm package version (if applicable): 1.18.1
- `@azure/communication-chat` npm package version (if applicable): 1.3.2

- OS & Device: MacOS M2, iOS on iPhone 13
- Browser: Chrome and Safari
- Browser Version: Chrome 119.0.6045.123, Safari for iOS: last version for iOS 17

**Comment by prabhjot-msft** [comment]
Thanks @davidegemma for raising the issue, we are looking into it, will keep you posted with the updates!

**Comment by JamesBurnside** [comment]
Closing this GitHub issue as a fix was pushed, please open a new issue if you are still seeing the problem
