### ISSUE TITLE
Intermittent message in MessageThread

### ISSUE THREAD

**Issue by petru-guider** [Azure/communication-ui-library#3829]
**Describe the bug; what happened?**

`MessageThreadProps.messages` (returned by `usePropsFor(MessageThread)`) contains intermittent message while sending message. After message is delivered, the intermittent message is removed from `messages`.

**What are the steps to reproduce the issue?**

1. In browser's DevTools, set network to Slow 3G
2. Send a message through `SendBox` component
3. `MessageThreadProps.messages` contains intermittent message while sending message

**What behavior did you expect?**

Only delivered message to displayed (be part of the `MessageThreadProps.messages`)

**If applicable, provide screenshots:**

https://github.com/Azure/communication-ui-library/assets/145334899/df175577-eded-49bd-8f99-e19e3e1084f8

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version: 1.10.0
- OS & Device: macOS Ventura 13.4 on MacBook Pro Apple M2
- Browser: Google Chrome
- Browser Version: 118

**Is there any additional information?**

**Comment by jpeng-ms** [comment]
Hi @petru-guider thanks for raising this issue. please allow me to check with our team and I will get you back shortly.

**Comment by jpeng-ms** [comment]
Thanks @petru-guider this is a known issue and we are currently working on it. I will post an update here once it's addressed.

**Comment by jpeng-ms** [comment]
#3378161

**Comment by jpeng-ms** [comment]
Hi @petru-guider we have fixed this issue in https://github.com/Azure/communication-ui-library/pull/3809/files, however, it hasn't been released yet.

I have tested our latest main branch and I can confirm that with network conditioner set to 3G, there's no more duplicated message being shown during sending state. 

We are planning to release new versions in early next year and we welcome you to try it out and let us know if you have any other questions.


I will go ahead and close this issue now, but feel free to reopen it if you have more questions!
