### ISSUE TITLE
Date format on chat messages in MessageThread component does not reflect browser's local settings for Edge browser

### ISSUE THREAD

**Issue by Raveen-Maldeni** [Azure/communication-ui-library#3830]
**Describe the bug; what happened?**
Date format displayed on chat messages in the MessageThread component does not reflect the browser's locale settings for Microsoft Edge (works fine for Chrome/Safari).

When Edge language is set to English (United States), date is still formatted as dd/mm/yyyy.

**What are the steps to reproduce the issue?**
Consume MessageThread component with a chat message in a React app and view in Microsoft Edge.

**What behavior did you expect?**
The date format to be in line with the browser's locale settings e.g. English (United States) to be mm/dd/yyyy.

**If applicable, provide screenshots:**
![image](https://github.com/Azure/communication-ui-library/assets/101307305/8442bea4-d744-4a0a-a2a9-beed84d1bcdb)
![image](https://github.com/Azure/communication-ui-library/assets/101307305/62278ad1-df87-4da3-abbd-f7b8d002786b)

- `@azure/communication-react` npm package version (if applicable): 1.10.0
- `@azure/communication-chat` npm package version (if applicable): 1.3.2

- OS & Device: Windows on PC
- Browser: Microsoft Edge
- Browser Version: 119.0.2151.72

**Comment by jpeng-ms** [comment]
Hi @Raveen-Maldeni , thanks for raising this issue. Please allow me to check with our team and get back to you. Thanks

**Comment by palatter** [comment]
@Raveen-Maldeni Can you please send us sample of your code?

**Comment by Raveen-Maldeni** [comment]
Here's a code snippet:

`import React from "react";
import { MessageThread, SendBox, DEFAULT_COMPONENT_ICONS, ChatMessage, FluentThemeProvider, MessageProps, MessageRenderer } from "@azure/communication-react";
import { initializeIcons, registerIcons, Persona, PersonaSize } from "@fluentui/react";

function mapToChatMessage(message, allUsers: User[], currentUser: User): ChatMessage {
    return {
        senderDisplayName: getUserName(message.createdByUserId, allUsers ?? []),
        senderId: message.createdByUserId,
        editedOn: message.createdOn.valueOf() === message.lastModified.valueOf() ? undefined : message.lastModified,
        content: message.text,
        createdOn: message.createdOn,
        contentType: "richtext/html",
        messageType: "chat",
        messageId: message.id,
        mine: message.createdByUserId === currentUser.id,
        status: "delivered" //This can be set to delivered if the message has been saved to cosmosdb successfully if we want to utilise the retry behaviour of the chat component.
    };
}

function updateMessageToRender(messageProps: MessageProps, defaultMessageRenderer: MessageRenderer): JSX.Element {
    const MessageElement = () => {
        // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
        const chatMessage = messageProps.message as ChatMessage;
        return (
            <div>
                {chatMessage.mine ? (
                    //Current User's icon
                    <Persona
                        text={chatMessage.senderDisplayName}
                        size={PersonaSize.size32}
                        initialsColor={...}
                        initialsTextColor={...}
                        onRenderPrimaryText={() => <></>}
                    />
                ) : (
                    //Other User's icon
                    <Persona
                        text={chatMessage.senderDisplayName}
                        size={PersonaSize.size32}
                        initialsColor={...}
                        initialsTextColor={...}
                        onRenderPrimaryText={() => <></>}
                    />
                )}
                {defaultMessageRenderer({ ...messageProps })}
            </div>
        );
    };
    return MessageElement();
}



export function CommentsContainer(props) {
    ...

    return (
        <div className="Chat">
            <FluentThemeProvider>
                    <div id="message-box">
                        {
                            <MessageThread
                                userId={currentUser.id}
                                messages={hitComments?.map((message) => mapToChatMessage(message, allUsers, currentUser)) ?? []}
                                onDeleteMessage={async (messageId: string) => {
                                    dispatch(
                                        ...
                                    );
                                }}
                                onUpdateMessage={async (messageId: string, content: string) => {
                                    dispatch(
                                        ...
                                    );
                                }}
                                showMessageDate={true}
                                onRenderMessage={(props: MessageProps, defaultOnRender) => {
                                    if (!defaultOnRender) {
                                        throw new Error("defaultOnRender is undefined");
                                    }
                                    return updateMessageToRender(props, defaultOnRender);
                                }}
                            />
                        }
                    </div>
            </FluentThemeProvider>
        </div>
    );
}
`

**Comment by palatter** [comment]
I'll have an update for you on this today.

**Comment by palatter** [comment]
We have a feature currently in the beta version [PublicPreview 1.11.0-beta.1](https://github.com/Azure/communication-ui-library/releases/tag/PublicPreview%2F1.11.0-beta.1) of the library that does support custom timestamps.

Either through the [ChatComposite here](https://azure.github.io/communication-ui-library/?path=/docs/composites-chat-customdatetimeformatexample--custom-date-time-format-example)

Or through components using the [MessageThread here](https://azure.github.io/communication-ui-library/?path=/docs/composites-chat-customdatetimeformatexample--custom-date-time-format-example)

**Comment by Raveen-Maldeni** [comment]
Yes the ideal behavior works in the beta but we didn't want to release to our production environment with the beta package. Is there any known timeline for when that will reach a regular release?

**Comment by palatter** [comment]
We are using Javascript's `toLocaleDateString()` method for formatting the date time string. I have linked our code below.

https://github.com/Azure/communication-ui-library/blob/fb1a6d4e87548215f9d5654f5b60a0a114912c0d/packages/react-components/src/components/utils/Datetime.ts#L17

After some initial investigation Javascript's `toLocaleDateString()` does seem to have differing behaviour depending on the system and browser. 

I am going further look into this and will update you with what I find.

**Comment by palatter** [comment]
What is the locale and timezone settings for your system? do they differ from what you have set in the browser?

**Comment by Raveen-Maldeni** [comment]
Yes they do. My system is set to Auckland, NZ datetime but my browser is set to English US. Was wanting to confirm this was a browser related issue and not due to the implementation. I've noticed on Chrome with the same system and browser settings it respects the browser settings for formatting the date.

Now that you've clarified its using toLocaleDateString I think we can close this since it seems to be due to Edge rather than the package.

Thanks for looking into this.
