### ISSUE TITLE
Is it possible to use the MessageThread component without ChatClientProvider and ChatThreadClientProvider

### ISSUE THREAD

**Issue by GillesTourreau** [Azure/communication-ui-library#3924]
We try to reuse the `MessageThread` component without using a `ChatClientProvider` and `ChatThreadClientProvider` to add or remove messages in a thread.

I used the following code (based on the example [Default MessageThread](https://azure.github.io/communication-ui-library/?path=/docs/ui-components-messagethread--message-thread#default-messagethread)) example:

```tsx
import { ChatMessage, FluentThemeProvider, MessageStatus, MessageThread } from '@azure/communication-react';
import { useState } from 'react';
import { GetHistoryChatMessages } from './placeholdermessages';

export const DefaultMessageThreadExample: () => JSX.Element = () => {
  const [messages, setMessages] = useState<ChatMessage[]>(GetHistoryChatMessages());

  function loadCustomMessages(m: number): Promise<boolean> {

    // Deletes the first message.
    messages.splice(0, 1);

    // Add a new message.
    messages.push({
      messageType: 'chat',
      senderId: 'user1',
      senderDisplayName: 'Gilles TOURREAU',
      messageId: Math.random().toString(),
      content: 'My custom message',
      createdOn: new Date('2019-04-13T00:00:00.000+08:10'),
      mine: true,
      attached: false,
      status: 'seen' as MessageStatus,
      contentType: 'html'
    });

    console.log(messages);
    
    setMessages(messages);

    return Promise.resolve(true);
  }

  return (
    <FluentThemeProvider>
      <MessageThread
        userId={'1'}
        messages={messages}
        onLoadPreviousChatMessages={loadCustomMessages}
      />
    </FluentThemeProvider>
  );
};
```

This exemple try during the `onLoadPreviousChatMessages` process to add `messages` in props of the `MessageThread` component, but it does not work.

If I use `usePropsFor(MessageThread)` to create props object for the `MessageThread` component, I receive the following error:
`Could not find props for this component, ensure the component is wrapped by appropriate providers.`. Of course, this error occurs because I am not using the `ChatClientProvider` and `ChatThreadClientProvider` providers.

Is it possible to use the `MessageThread` component without the `ChatClientProvider` and `ChatThreadClientProvider` providers?

**Comment by vhuseinova-msft** [comment]
Hello @GillesTourreau!

`Is it possible to use the MessageThread component without the ChatClientProvider and ChatThreadClientProvider providers?`
Sure, `MessageThread` can be used separately but, in this case, the props should be provided for the `MessageThread`

`This exemple try during the onLoadPreviousChatMessages process to add messages in props of the MessageThread component, but it does not work.`
I've tested the provided code and it looks like `onLoadPreviousChatMessages` is called as expected (it's called 1 time as it returns a promise with `true` value). I've changed a couple of things in the provided example, so the added message will be shown before the other messages. Please see the code that I've used for more details:

```
import {
  ChatMessage,
  FluentThemeProvider,
  MessageStatus,
  MessageThread,
} from "@azure/communication-react";
import { useState } from "react";

const App: () => JSX.Element = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "0",
      createdOn: new Date("2019-04-12T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    },
    {
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "1",
      createdOn: new Date("2019-04-12T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    },
    {
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "2",
      createdOn: new Date("2019-04-12T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    },
    {
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "3",
      createdOn: new Date("2019-04-12T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    },
    {
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "4",
      createdOn: new Date("2019-04-12T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    },
    {
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "5",
      createdOn: new Date("2019-04-12T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    },
    {
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "6",
      createdOn: new Date("2019-04-12T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    },
    {
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "7",
      createdOn: new Date("2019-04-12T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    },
  ]);

  function loadCustomMessages(m: number): Promise<boolean> {
    console.log("messages before", messages);
    const updatedMessages = messages;

    // Add a new message at the beggining of the messages array
    updatedMessages.unshift({
      messageType: "chat",
      senderId: "user1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "My custom message",
      createdOn: new Date("2019-04-13T00:00:00.000+08:10"),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    });

    console.log("messages after", updatedMessages);

    setMessages(updatedMessages);

    return Promise.resolve(true);
  }

  return (
    <FluentThemeProvider>
      <MessageThread
        userId={"user1"}
        messages={messages}
        onLoadPreviousChatMessages={loadCustomMessages}
      />
    </FluentThemeProvider>
  );
};

export default App;
```
The result:
![image](https://github.com/Azure/communication-ui-library/assets/98852890/3b04e39f-566f-4cdd-8201-d24244edd711)


Please let me know if the provided code works for you.

**Comment by GillesTourreau** [comment]
Hello @vhuseinova-msft!

Thanks for your answer!
I've noticed that my problem is that we're unable to update the message at the end of the array; we can only do so before that point...
From what I gather, we're limited to inserting messages at the beginning of the messages array (which makes sense for a chat application fetching historical messages).
However, I'm curious about why the `onLoadPreviousChatMessages` function is indefinitely called to retrieve all historical messages when the component is loaded?

Normally the `MessageThread` should trigger the `onLoadPreviousChatMessages` function only when the user scrolls up, requesting more message to display, but without to download all the history!

I have the following example to reproduce the issue:
- I generate 200 messages in the `database` global variable (which represent an external source like a database).
- The `messageCursor` represents a cursor to the next message to retrieve (starting from the end of the `database` array).
- Within the `loadCustomMessages()` we fetch the specified number of messages indicated in the argument of the `onLoadPreviousChatMessages` handler and decrement the cursor.

When running the application, the `loadCustomMessages()` function (linked to the `onLoadPreviousChatMessages` handler) is being triggered multiple times until all the messages in the `database` array are retrieved! (Check the log to see the progress). And also, only the first 5 messages are displayed instead of the full 200...

This is the full and simple example of the issue:
```jsx
import { ChatMessage, FluentThemeProvider, MessageStatus, MessageThread } from '@azure/communication-react';
import { useState } from 'react';

const database = CreateDatabase();          // Represents message stored in database.
var messageCursor = database.length - 1;    // Cursor of the next message to retrieve.

// Function to initialize the "database" variable.
function CreateDatabase(): ChatMessage[] {
  var dt = new Date('2019-01-01T00:00:00.000+08:10');
  const dbMessages: ChatMessage[] = [];

  for(var i=0; i<200; i++) {
    dbMessages.push({
      messageType: 'chat',
      senderId: 'user1',
      senderDisplayName: 'Gilles TOURREAU',
      messageId: Math.random().toString(),
      content: 'My custom message' + i,
      createdOn: new Date(dt.getTime() + (1000 * 60 * 60 * 24 * i)),
      mine: true,
      attached: false,
      status: 'seen' as MessageStatus,
      contentType: 'html'
    });
  }

  return dbMessages;
}

export const DefaultMessageThreadExample: () => JSX.Element = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);

  function loadCustomMessages(numberOfMessagesToLoad: number): Promise<boolean> {
    console.log(`Load ${numberOfMessagesToLoad} messages (MessageCursor: ${messageCursor})`);

    // Retrieves the "numberOfMessagesToLoad" from the "database" messages
    // and decrementing the message cursor.
    for(var i=0; i<numberOfMessagesToLoad && messageCursor >= 0; i++, messageCursor--) {
      messages.unshift(database[i]);
    }

    setMessages(messages);

    if (messageCursor <= 0)
    {
      console.log("no more messages to retrieve, stop it!");
      return Promise.resolve(true);
    }

    console.log("more message to retrieve...");
    return Promise.resolve(false);
  }

  return (
    <FluentThemeProvider>
      <div style={{height: "500px"}}>
        <MessageThread
          userId={'1'}
          messages={messages}
          onLoadPreviousChatMessages={loadCustomMessages}
        />
      </div>
    </FluentThemeProvider>
  );
};
```

Is it an issue of the `MessageThread` component?

**Comment by vhuseinova-msft** [comment]
@GillesTourreau thanks for sharing another example!
I've just tested the example you provided and found an issue that  the `messages` array wasn't updated properly (by `useEffect` hook usage)

The main problem in the provided example is how new items are added to the array. As we work with the React components and arrays, it's mandatory to create a new array when working with states instead of modifing the existing one. Please see [this link in the ReactJS documentation for more details](https://react.dev/learn/updating-arrays-in-state#adding-to-an-array). As we used `push` and `unshift` functions in the examples previously, the array was modified instead of creating a new array. (Sorry for misleading you in the first example!)

So, the working example would be (becuse a new array is created `return [...newMessages, ...prev];`):

```
import {
  ChatMessage,
  FluentThemeProvider,
  MessageStatus,
  MessageThread,
} from "@azure/communication-react";
import { useCallback, useEffect, useState } from "react";
const database = CreateDatabase(); // Represents message stored in database.
var messageCursor = database.length - 1; // Cursor of the next message to retrieve.

// Function to initialize the "database" variable.
function CreateDatabase(): ChatMessage[] {
  var dt = new Date("2019-01-01T00:00:00.000+08:10");
  const dbMessages: ChatMessage[] = [];

  for (var i = 0; i < 200; i++) {
    dbMessages.push({
      messageType: "chat",
      senderId: "1",
      senderDisplayName: "Gilles TOURREAU",
      messageId: Math.random().toString(),
      content: "My custom message" + i,
      createdOn: new Date(dt.getTime() + 1000 * 60 * 60 * 24 * i),
      mine: true,
      attached: false,
      status: "seen" as MessageStatus,
      contentType: "html",
    });
  }

  return dbMessages;
}

export const DefaultMessageThreadExample = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  function loadCustomMessages(
    numberOfMessagesToLoad: number
  ): Promise<boolean> {
    if (messageCursor <= 0) {
      console.log("no more messages to retrieve, stop it!");
      return Promise.resolve(true);
    }
    setMessages((prev) => {
      let newMessages: ChatMessage[] = [];
      for (var i = numberOfMessagesToLoad; i > 0; i--, messageCursor--) {
        newMessages.push(database[database.length - prev.length - i]);
      }
      return [...newMessages, ...prev];
    });

    console.log("more message to retrieve...");
    return Promise.resolve(false);
  }

  useEffect(() => {
    console.log("messages", messages);
  }, [messages]);

  return (
    <FluentThemeProvider>
      <div style={{ height: "500px" }}>
        <MessageThread
          userId={"1"}
          messages={messages}
          onLoadPreviousChatMessages={loadCustomMessages}
        />
      </div>
    </FluentThemeProvider>
  );
};

```

`Normally the MessageThread should trigger the onLoadPreviousChatMessages function only when the user scrolls up, requesting more message to display, but without to download all the history!`

Because of the issue with the updating array, `MessageThread` was always in state when it's scrolled all the way up (there were messages to load but they weren't shown and scrolling wasn't available). This isn't true anymore for the example provided in this message above (because a new array is returned and used in `setMessages`).
Just another thing, I would also recommend to use another approach instead of a global variable for a real app as it can cause issues when using in async funcs.

**Comment by GillesTourreau** [comment]
@vhuseinova-msft really thanks to fix my code!
I understand more better the way to updates the messages from the state (Thanks also for the link for mutable array issues with the components state!).

However, I tried to embedded the React component in Blazor component and I still have the infinite scroll.
You can check my public [repository](https://github.com/GillesTourreau/communication-ui-library-blazor) with a very minimalist Blazor application with the `MessageThread` component.

Just open the solution at the root of the repository and run the `Demo` application. You will see that the messages are retrieved from .NET code using JS Interop. 

This sample work almost perfectly, but the `onLoadPreviousChatMessages()` JS function is infinitely triggered and the history is automatically scroll to the top... 😫 (In the following gif video I did not scroll with my mouse, it is just when I load the page in my sample project...):
![InfiniteScroll](https://github.com/Azure/communication-ui-library/assets/29240370/24dba739-5d0a-432d-93b7-f9cdb34ced28)

In my sample application I used a [Demo.Client/wwwroot/communication-react.js](https://github.com/GillesTourreau/communication-ui-library-blazor/blob/main/Demo.Client/wwwroot/communication-react.js) file which is a bundle of [communication-ui-library](https://github.com/Azure/communication-ui-library) library using parcel and simply exporting required components for my Blazor component. It contains React `createElement`, `useState`, and `createRoot` and `MessageThread` components only. I just used the following source code to export the required components:

```javascript
import React from 'react'

export let createElement = React.createElement;
export let useState = React.useState;
export { createRoot } from 'react-dom/client';
export { MessageThread } from '@azure/communication-react';
```

I tested this bundle with a simple HTML page with raw JS only and using the source code in your previous comment. It is work perfectly (The `onLoadPreviousChatMessages()` function is triggered, when we scroll up the chat history and "on-demand"). So this bundle file should work perfectly.

The source code of the HTML page used to test this bundle file is located in the following file: [test-with-raw-js.html](https://github.com/GillesTourreau/communication-ui-library-blazor/blob/main/Demo.Client/wwwroot/test-with-raw-js.html).
It can be accessible from the `https://localhost:7131/test-with-raw-js.html` when the Blazor app is running (it is just a simple static HTML file download, no Blazor code is executed when accessing to this URL...).

I really do not know why I have this infinite scroll occurring when the component is loaded in a Blazor application (and not with React or raw JS application). I removed all the CSS in the Visual Studio projects to have a "pure blank page", to be sure it is not a related to a `<div>` or CSS style...

Any idea about this issue?

**Comment by vhuseinova-msft** [comment]
@GillesTourreau  thanks for sharing the update that the solution worked for you for ReactJS and raw JS applications!

As of now, we are only supporting ReactJS for the Web UI library. For integration with Blazor powered applications, please refer to the official [Blazor documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-7.0), [guides](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0) and [ASP.NET GitHub repository](https://github.com/dotnet/aspnetcore).

**Comment by vhuseinova-msft** [comment]
Since the remaining issue is related to the integration between JS applications and Blazor, and not related to the Web UI Library, I'll close the issue.
