### ISSUE TITLE
Infinite scrolling with the MessageThread component when using the "<!DOCTYPE html>" directive.

### ISSUE THREAD

**Issue by GillesTourreau** [Azure/communication-ui-library#3939]
Hello,

When we have an app (React or HTML with raw JS) with no `<!DOCTYPE html>` directive in the bottom of the page, when the `MessageThread` is loaded, the message are automatically scrolled to the top infinitely until the `onLoadPreviousChatMessages` handler return `true`.

I reproduced this issue with a simple React application in my [communication-ui-library-doctype-issue](https://github.com/GillesTourreau/communication-ui-library-doctype-issue) repository:
- Clone the repository
- Run `npm install` and `npm start`
- Open the browser with the following URL: `http://localhost:3000`

👉 You will see that the component automatically scroll up and all the 200 fakes messages are displayed (The `onLoadPreviousChatMessages()` hander is called until it return `true`.).
![InfiniteScroll](https://github.com/Azure/communication-ui-library/assets/29240370/e8fbcf87-a2c4-4cf0-8d34-0ff8121caa15)

Now, go to the `public\index.html` page.
Remove the `<!DOCTYPE html>` directive on the top of the file.
And refresh the page.
![InfiniteScroll2](https://github.com/Azure/communication-ui-library/assets/29240370/46681c56-5a4b-4781-a78a-7e458fa04e1c)

👉 You will see that the component do not scroll up. We just need to scroll up manually to display history of the message (in this case the `onLoadPreviousChatMessages` handler is triggered when a new "page" of message have to be display to the user).

I am not too much an expert about the HTML and JS, but by searching, I saw on the web when using the `<!DOCTYPE html>` the JS `scrolltop` property is obsolete and have different behavior (This property is used internally in the `MessageThread` component?).

I reproduced this issue on the `@azure/communication-react` package **1.3.0** on **Chrome** and **Edge**.

@vhuseinova-msft It is related to my previous closed issue #3924. The issue was not due to Blazor, but just because the `<!DOCTYPE html>` was specified on index.html page which raise the infinite scroll of the `MessageThread` component...

**Comment by vhuseinova-msft** [comment]
Hello @GillesTourreau!
Thanks for reaching out to us. Please allow us to look into this and we would get back to you shortly.

**Comment by vhuseinova-msft** [comment]
@GillesTourreau, I just wanted to share a quick update: 
I was able to reproduce the issue with the scroll with the shared demo application. A fix for the issue will be available in the next release.

**Comment by vhuseinova-msft** [comment]
Hello @GillesTourreau!!
The fix is released as part of [1.12.0 release](https://github.com/azure/communication-ui-library/tree/1.12.0). Please check it out and let us know if you have any questions.
