### ISSUE TITLE
Teams meetings integration

### ISSUE THREAD

**Issue by paddotk** [Azure/communication-ui-library#416]
Hi,

I have a question regarding usage of the Teams-meeting connection part of this library. In our project we specificaly need to connect with Teams meetings, and we used [https://github.com/Azure-Samples/communication-services-web-calling-hero](https://github.com/Azure-Samples/communication-services-web-calling-hero) as a starting point. I'm trying to use the 'connect to Teams' functionality from communication-ui-library but it seems it relies on several dependencies that don't exist on npm, and are somehow included locally in this repo.

Because of the changes we incorporated into our project alreayd, and due to Rush being extremely slow (> 5mins to startup the frontend), switching to a project based on this library directly isn't an option.

I have also checked the storybook but can't make much sense of the examples there, or how it relates to what this library uses.

Is there any way to use those locally used packages (without using Rush)?

**Comment by paddotk** [comment]
Nevermind, I was just told this is an actual importable library which I didn't realize. Closing.

**Comment by iMicknl** [comment]
It would be good to have up to date end to end samples, like https://github.com/Azure-Samples/communication-services-web-calling-hero/ and https://github.com/Azure-Samples/communication-services-web-calling-hero/blob/teams-interop, using communication-react.

Is there any ETA (or preview) for the updated samples? The current samples are using rush and are more suitable as an easy to access test sample for sdk development, but not for use as inspiration for actual customer examples. The current documentation is confusing around this topic. (see this issue).

**Comment by ddematheu2** [comment]
Hey @iMicknl, the team is currently working on generating samples off communication-react. We expect to have those out in the next month or so.  The direction we are taking moving forward is to align all UI samples on the UI Library to make the process for developer wanting to modify better. 

Aligned to @paddotk issue above, once we align developers should be able to to use the example code found in this repo to modify the sample apps.
