### ISSUE TITLE
updateMessage is not updating also the metadata in "@azure/communication-react": "^1.14.0-beta.1"

### ISSUE THREAD

**Issue by stefanzahar1a** [Azure/communication-ui-library#4209]
Calling adapter?.updateMessage(messageProps.messageId, messageProps.content, { 'reaction': 'LIKE' }) is not updating the metadata of the message.

**What are the steps to reproduce the issue?**

Add "@azure/communication-react": "^1.14.0-beta.1" dependency.
Call await adapter?.updateMessage(messageProps.messageId, messageProps.content, { 'reaction': 'LIKE' }) method.
Check what request is done, in network tab.
See that the request sends only changed content, but not changed metadata:
![image](https://github.com/Azure/communication-ui-library/assets/66030025/e3c2a4f0-18b9-4219-b70f-6065b5a501a6)

**What behavior did you expect?**
Metadata should also be sent according to the parameters that I pass to updateMessage method.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

"@azure/communication-react": "^1.14.0-beta.1"

**Comment by JoshuaLai** [comment]
Thanks for bringing this to our attention. I have investigated and found that we were dropping the `metadata` argument by mistake when `options` was not provided. I have created a PR and this should be resolved in the next beta release.

**Comment by JoshuaLai** [comment]
@stefanzahar1a  This issue should be resolved with the latest stable release.  I will be closing this issue, please let us know if you encounter any more errors. Feel free to re-open this issue if it has not been resolved for you.
