### ISSUE TITLE
CallAgent.join: Invalid meeting link in CallComposite

### ISSUE THREAD

**Issue by OlehMaistrenko** [Azure/communication-ui-library#4219]
When setting 
locator: {meetingLink: 'https://teams.live.com/meet/9999999999999?p=xxxxxxxxxxxxxxxx'}
got error 

CallAgent.join: Invalid meeting link
CallError: CallAgent.join: Invalid meeting link
    at toCallError (http://localhost:3000/static/js/bundle.js:116340:12)
    at Proxy.<anonymous> (http://localhost:3000/static/js/bundle.js:116326:27)
    at AzureCommunicationCallAdapter._joinCall (http://localhost:3000/static/js/bundle.js:132079:29)
    at http://localhost:3000/static/js/bundle.js:132069:25
    at AzureCommunicationCallAdapter.teeErrorToEventEmitter (http://localhost:3000/static/js/bundle.js:132568:14)
    at AzureCommunicationCallAdapter.joinCall (http://localhost:3000/static/js/bundle.js:132045:17)
    at startCallHandler (http://localhost:3000/static/js/bundle.js:131430:21)
    at http://localhost:3000/static/js/bundle.js:136608:5
    at Generator.next (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:136513:67

**Comment by dmceachernmsft** [comment]
Hi @OlehMaistrenko! Thanks for filing the issue!

Can you please provide some more information like:
- Browser
- Platform
- Version of `communication-react`
As well any snippets you are willing to share of your code trying to do this.

**Comment by OlehMaistrenko** [comment]
> Hi @OlehMaistrenko! Thanks for filing the issue!
> 
> Can you please provide some more information like:
> 
> * Browser
> * Platform
> * Version of `communication-react`
>   As well any snippets you are willing to share of your code trying to do this.

Of course.
Browser: Google Chrome Version 122.0.6261.95 (Official Build) (64-bit)
Platform: Windows
"@azure/communication-react": "^1.13.0"

Used app component from [https://github.com/microsoft/MicrosoftCloud/blob/main/samples/acs-to-teams-meeting/client/react/src/App.tsx](url) 

meetingLink from [https://teams.live.com/](url) app via "Copy meeting link" button

**Comment by dmceachernmsft** [comment]
For the Teams client @OlehMaistrenko are you using teams for life? or teams for work and school?

**Comment by OlehMaistrenko** [comment]
> For the Teams client @OlehMaistrenko are you using teams for life? or teams for work and school?

for life

**Comment by dmceachernmsft** [comment]
Hi @OlehMaistrenko so unfortunately we do not support interop with Teams For Life at the moment. I am working with our interop team to understand the reason as to why it isn't supported.

I apologize for the inconvenience here. I will have a answer for you shortly as to why.
