### ISSUE TITLE
Some UI Elements do not render as expected when 1rem = 10px

### ISSUE THREAD

**Issue by rnbroadw** [Azure/communication-ui-library#4220]
**Describe the bug; what happened?**
Some elements on the chat message thread are not rendering as expected when 1rem equals 10px. It seems like the calculations for some of the elements were done with the expectation that 1rem would always equal 16px.

**What are the steps to reproduce the issue?**
1. Set html element's font-size property to 10px:
  `html {
   font-size: 10px
  }`
2. Run a sample chat application and open a chat window.

**What behavior did you expect?**
I expect the ratio of the elements on the screen to be the same when the rem calculation is 10px vs. 16px. Some elements change size when 10px, but other elements stay the same size regardless of the font-size of the html element.

As you can see in the below screenshots, the following elements on the page do not change when the font-size is changed:
- The "Edited" tag.
- The messages about adding group chat participants as well as renaming the chat 
- The message content 

**If applicable, provide screenshots:**
Rendering correctly: 1rem = 16px:
![image](https://github.com/Azure/communication-ui-library/assets/79797447/af780608-88ff-4ccc-8ee8-de005ce8eed2)

Rendering incorrectly: 1rem = 10px:
![image](https://github.com/Azure/communication-ui-library/assets/79797447/ff1b6f9c-115d-4792-9265-7212ce6d6bcf)

**In what environment did you see the issue?**
- `@azure/communication-react` npm package version: 1.9.0-beta.1
- OS & Device: Windows 10
- Browser: Google Chrome
- Browser Version: 121.0.6167.185

**Is there any additional information?**
No

**Comment by palatter** [comment]
@rnbroadw, thank you for reaching out to us. Please allow us to look into this and we would get back to you shortly.

**Comment by palatter** [comment]
@rnbroadw We have a potential solution to this and will notify you when we know what release it will be included in.

**Comment by palatter** [comment]
@rnbroadw a update here

We are going to move everything px, so there is not a mix. Everything will stay the same size. Instead we recommend using scaling.

**Comment by palatter** [comment]
@rnbroadw Due to complications with our dependencies, at the moment, our recommendation, is to use browser scaling rather than font size for any UI size adjustments.
