### ISSUE TITLE
Do we an option to "Enable Camera by default" in the Config Page

### ISSUE THREAD

**Issue by lovedota** [Azure/communication-ui-library#4275]
Hi Team

We have an option to `hide camera` in `CallComposite` but we don't have option to set the default value for it, similar to Mic.

**Comment by alkwa-msft** [comment]
Greetings! I am acknowledging your github issue. We will take this back to the team and try to find you an answer soon!

**Comment by alkwa-msft** [comment]
https://github.com/Azure/communication-ui-library/discussions/3379

I would like to focus your attention to the middle of the doc where we talk about setting the default camera setting
![image](https://github.com/Azure/communication-ui-library/assets/79329532/323f4263-0978-498d-9339-ea34dc379ec8)

This is of course based on if there is a valid camera connected as well. Try it out and hopefully this helps? We would love to hear if this was able to solve your issue!

**Comment by lovedota** [comment]
Hi @alkwa-msft 
The api `adapter.joinCall` will skip the config screen. It is not what we want, we want to toggle the Camera On by defaut in the Config Page.

**Comment by JamesBurnside** [comment]
Hi @lovedota, to toggle the camera on, or set a different default camera, you can use the adapter interface:
```ts
// Start mic unmuted
adapter.unmute();

// Turn camera on by default
if (adapter.getState().devices.cameras.length !== 0) {
  const camera = adapter.getState().devices.selectedCamera ?? adapter.getState().devices.cameras[0];
  adapter.setCamera(camera).then(() =>
    adapter.startCamera({
      scalingMode: isMobileSession ? 'Fit' : 'Crop'
    })
  );
}
```

**Comment by lovedota** [comment]
Thanks @JamesBurnside !!!!
