### ISSUE TITLE
Copy Link should show toast or alert for users

### ISSUE THREAD

**Issue by lovedota** [Azure/communication-ui-library#4426]
Hi
In People Tab, there is a copy link button, clicking it won't fire any visualization for users to know whether it is copied or not.

![Screen Shot 2024-04-07 at 21 40 51 PM](https://github.com/Azure/communication-ui-library/assets/417914/90bda1bd-4f0d-4d60-ab7c-8c835f975126)

**Comment by mgamis-msft** [comment]
Hi @lovedota, thanks for filing this issue and giving us this very good UX feedback. Currently, our Calling composite does not have an indicator for the Copy link button. I will file this item in the backlog and follow up with our UX designer.
This is what Teams Copy link button visualization looks like:
![image](https://github.com/Azure/communication-ui-library/assets/79475487/80cc2a60-1c18-40e8-a95a-4c31a5eca85d)
Would something like this be good?

**Comment by mgamis-msft** [comment]
Working on a fix for this after confirming the above solution with our UX designer. I will update here when that fix will be available.

**Comment by mgamis-msft** [comment]
@lovedota The UX update from #4497 has now been merged into main. This should be available on npm in our 1.16.0 release next week
