### ISSUE TITLE
Chat messages suddenly limited to 6 per thread in ChatComposite

### ISSUE THREAD

**Issue by olandahl** [Azure/communication-ui-library#4625]
I'm using the ChatComposite component to display a chat thread. A backend create threads, add users and some custom messages. Everything is working fine, it's possible to add messages, edit, remove, and so on. Suddenly all threads show only the 6 latest messages, even when the page is reloaded. I can see all messages are included in the REST API /messages response (done by the ChatComposite component) but it seems the WebSocket data is limited to 6 messages.
This happens when running on localhost. In a public dev environment (using the same ACS instance) all messages are still displayed.

Is there some kind of rate limit that kicks in? We're not even close to hit the service limits for the chat (https://learn.microsoft.com/en-us/azure/communication-services/concepts/service-limits#chat)

We use beta versions to get some features that are missing in the latest offical releases:
"@azure/communication-chat": "^1.5.0-beta.1",
"@azure/communication-react": "^1.15.0-beta.2",

Running in Chrome v 124

**Comment by Leah-Xia-Microsoft** [comment]
Thanks for logging this issue. Will share with the team and get back to you on a response.

**Comment by Leah-Xia-Microsoft** [comment]
Hi @olandahl,
Does this also happen on Safari? Could you also provide more details about the websocket date you've mentioned?
It would be helpful if you can provide a sample app that this issue is reproducible. Any additional information such as reproduce steps, logs, videos, screenshots would be appreciated.

**Comment by olandahl** [comment]
Hi @Leah-Xia-Microsoft, 

When I did some debugging in dev tools I found updates to the messages state that where the number of items were limited to 6. I assumed the data came from web socket. I can't find that place in the code now but I'll let you know if I do. Hopefully I'll have time to create a sample app where the issue is reproducable.

The issue is also in Safari.

The rendered ChatComposite on the dev site, including all messages:
<img width="607" alt="chat-dev-site" src="https://github.com/Azure/communication-ui-library/assets/5770496/4f8f2f50-58e4-495c-a0fd-45c98e3f3b04">

The rendered ChatComposite on localhost, including 6 messages:
<img width="611" alt="chat-localhost" src="https://github.com/Azure/communication-ui-library/assets/5770496/07fe4bea-35a4-4464-a73e-033a7e86ebca">

The request to https://acs-onewound-dev.europe.communication.azure.com/chat/threads/19%3AXj9G4INqH_jHAGuOLVAWVqrFF0okXxSuAEUakQRgAEQ1%40thread.v2/messages?maxPageSize=50&api-version=2024-03-01-preview (made by the ChatComposite component) is identical in localhost and on the dev site. It includes all messages.
`{
    "value": [
        {
            "id": "1717058161628",
            "type": "text",
            "sequenceId": "39",
            "version": "1717058161628",
            "content": {
                "message": "backend.treatmentplan.requestexperttreatmentplan",
                "attachments": []
            },
            "senderDisplayName": "Care Giver",
            "createdOn": "2024-05-30T08:36:01Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            },
            "metadata": {
                "woundId": "60",
                "type": "requestTreatmentplan"
            }
        },
        {
            "id": "1717051866221",
            "type": "text",
            "sequenceId": "38",
            "version": "1717051866221",
            "content": {
                "message": "nytt mess",
                "attachments": []
            },
            "senderDisplayName": "Wound Team",
            "createdOn": "2024-05-30T06:51:06Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                }
            }
        },
        {
            "id": "1716965610205",
            "type": "text",
            "sequenceId": "37",
            "version": "1716965610205",
            "content": {
                "message": "backend.treatmentplan.requestexperttreatmentplan",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-29T06:53:30Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            },
            "metadata": {
                "woundId": "60",
                "type": "requestTreatmentplan"
            }
        },
        {
            "id": "1716191032577",
            "type": "text",
            "sequenceId": "36",
            "version": "1716191032577",
            "content": {
                "message": "nu skriver jag",
                "attachments": []
            },
            "senderDisplayName": "Care Giver",
            "createdOn": "2024-05-20T07:43:52Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            }
        },
        {
            "id": "1715856310551",
            "type": "text",
            "sequenceId": "35",
            "version": "1715856310551",
            "content": {
                "message": "nytt meddelande",
                "attachments": []
            },
            "senderDisplayName": "Wound Team",
            "createdOn": "2024-05-16T10:45:10Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                }
            }
        },
        {
            "id": "1715778736192",
            "type": "participantAdded",
            "sequenceId": "34",
            "version": "1715778736192",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c"
                            }
                        },
                        "displayName": "Erik Samuelsson",
                        "shareHistoryTime": "1970-01-01T00:00:00Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                    }
                }
            },
            "createdOn": "2024-05-15T13:12:16Z"
        },
        {
            "id": "1715778725648",
            "type": "participantRemoved",
            "sequenceId": "33",
            "version": "1715778725648",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c"
                            }
                        },
                        "displayName": "Erik Samuelsson",
                        "shareHistoryTime": "1970-01-01T00:00:00Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c"
                    }
                }
            },
            "createdOn": "2024-05-15T13:12:05Z"
        },
        {
            "id": "1715687731476",
            "type": "text",
            "sequenceId": "32",
            "version": "1715687731476",
            "content": {
                "message": "här igen",
                "attachments": []
            },
            "senderDisplayName": "Care Giver",
            "createdOn": "2024-05-14T11:55:31Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            }
        },
        {
            "id": "1715686856551",
            "type": "participantAdded",
            "sequenceId": "31",
            "version": "1715686856551",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                            }
                        },
                        "displayName": "Care Giver",
                        "shareHistoryTime": "2024-05-07T12:42:54Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                    }
                }
            },
            "createdOn": "2024-05-14T11:40:56Z"
        },
        {
            "id": "1715686842419",
            "type": "text",
            "sequenceId": "30",
            "version": "1715686842419",
            "content": {
                "message": "jasså du lämnade?",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-14T11:40:42Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            }
        },
        {
            "id": "1715686819754",
            "type": "participantRemoved",
            "sequenceId": "29",
            "version": "1715686819754",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                            }
                        },
                        "displayName": "Care Giver",
                        "shareHistoryTime": "1970-01-01T00:00:00Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                    }
                }
            },
            "createdOn": "2024-05-14T11:40:19Z"
        },
        {
            "id": "1715684269900",
            "type": "text",
            "sequenceId": "28",
            "version": "1715684269900",
            "content": {
                "message": "backend.wound.newwoundimage",
                "attachments": []
            },
            "senderDisplayName": "Care Giver",
            "createdOn": "2024-05-14T10:57:49Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            },
            "metadata": {
                "woundId": "60",
                "type": "newWoundImage"
            }
        },
        {
            "id": "1715679532770",
            "type": "text",
            "sequenceId": "27",
            "version": "1715679532770",
            "content": {
                "message": "backend.wound.newwoundimage",
                "attachments": []
            },
            "senderDisplayName": "",
            "createdOn": "2024-05-14T09:38:52Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            },
            "metadata": {
                "woundId": "60",
                "type": "newWoundImage"
            }
        },
        {
            "id": "1715674930735",
            "type": "text",
            "sequenceId": "26",
            "version": "1715674948544",
            "content": {
                "message": "",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-14T08:22:10Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            },
            "deletedOn": "2024-05-14T08:22:28Z"
        },
        {
            "id": "1715674825436",
            "type": "text",
            "sequenceId": "25",
            "version": "1715674825436",
            "content": {
                "message": "hej!",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-14T08:20:25Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            }
        },
        {
            "id": "1715674819371",
            "type": "text",
            "sequenceId": "24",
            "version": "1715674819371",
            "content": {
                "message": "tjena!",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-14T08:20:19Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            }
        },
        {
            "id": "1715674809982",
            "type": "text",
            "sequenceId": "23",
            "version": "1715674809982",
            "content": {
                "message": "tjena!",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-14T08:20:09Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            }
        },
        {
            "id": "1715673628689",
            "type": "text",
            "sequenceId": "22",
            "version": "1715673628689",
            "content": {
                "message": "hello!",
                "attachments": []
            },
            "senderDisplayName": "Care Giver",
            "createdOn": "2024-05-14T08:00:28Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            }
        },
        {
            "id": "1715673443853",
            "type": "text",
            "sequenceId": "21",
            "version": "1715673443853",
            "content": {
                "message": "hejsan!",
                "attachments": []
            },
            "senderDisplayName": "Care Giver",
            "createdOn": "2024-05-14T07:57:23Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            }
        },
        {
            "id": "1715673375242",
            "type": "text",
            "sequenceId": "20",
            "version": "1715673375242",
            "content": {
                "message": "hej igen!",
                "attachments": []
            },
            "senderDisplayName": "Care Giver",
            "createdOn": "2024-05-14T07:56:15Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            }
        },
        {
            "id": "1715673067202",
            "type": "text",
            "sequenceId": "19",
            "version": "1715673067202",
            "content": {
                "message": "hej!",
                "attachments": []
            },
            "senderDisplayName": "Care Giver",
            "createdOn": "2024-05-14T07:51:07Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                }
            }
        },
        {
            "id": "1715673046153",
            "type": "participantAdded",
            "sequenceId": "18",
            "version": "1715673046153",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f3e6-a1f6-a7ac-473a0d0092d8"
                            }
                        },
                        "displayName": "Care Giver",
                        "shareHistoryTime": "2024-05-07T12:42:54Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                    }
                }
            },
            "createdOn": "2024-05-14T07:50:46Z"
        },
        {
            "id": "1715668075231",
            "type": "text",
            "sequenceId": "17",
            "version": "1715668075231",
            "content": {
                "message": "en gång till",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-14T06:27:55Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            }
        },
        {
            "id": "1715667883792",
            "type": "text",
            "sequenceId": "16",
            "version": "1715667975453",
            "content": {
                "message": "",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-14T06:24:43Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            },
            "deletedOn": "2024-05-14T06:26:15Z"
        },
        {
            "id": "1715598050137",
            "type": "text",
            "sequenceId": "15",
            "version": "1715598050137",
            "content": {
                "message": "backend.wound.newwoundimage",
                "attachments": []
            },
            "senderDisplayName": "",
            "createdOn": "2024-05-13T11:00:50Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            },
            "metadata": {
                "woundId": "60",
                "type": "newWoundImage"
            }
        },
        {
            "id": "1715203204808",
            "type": "participantAdded",
            "sequenceId": "14",
            "version": "1715203204808",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                            }
                        },
                        "displayName": "Olof Landahl",
                        "shareHistoryTime": "2024-05-07T12:42:54Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                    }
                }
            },
            "createdOn": "2024-05-08T21:20:04Z"
        },
        {
            "id": "1715203201371",
            "type": "participantRemoved",
            "sequenceId": "13",
            "version": "1715203201371",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                            }
                        },
                        "displayName": "Olof Landahl",
                        "shareHistoryTime": "1970-01-01T00:00:00Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                    }
                }
            },
            "createdOn": "2024-05-08T21:20:01Z"
        },
        {
            "id": "1715107764163",
            "type": "text",
            "sequenceId": "12",
            "version": "1715107764163",
            "content": {
                "message": "detta",
                "attachments": []
            },
            "senderDisplayName": "Wound Team",
            "createdOn": "2024-05-07T18:49:24Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                }
            }
        },
        {
            "id": "1715104916412",
            "type": "text",
            "sequenceId": "11",
            "version": "1715104916412",
            "content": {
                "message": "jag är wound team",
                "attachments": []
            },
            "senderDisplayName": "Wound Team",
            "createdOn": "2024-05-07T18:01:56Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                }
            }
        },
        {
            "id": "1715087524228",
            "type": "text",
            "sequenceId": "10",
            "version": "1715087524228",
            "content": {
                "message": "backend.wound.newwoundimage",
                "attachments": []
            },
            "senderDisplayName": "",
            "createdOn": "2024-05-07T13:12:04Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            },
            "metadata": {
                "woundId": "59",
                "type": "newWoundImage"
            }
        },
        {
            "id": "1715087046638",
            "type": "text",
            "sequenceId": "9",
            "version": "1715087046638",
            "content": {
                "message": "det här då",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-07T13:04:06Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            }
        },
        {
            "id": "1715086922249",
            "type": "text",
            "sequenceId": "8",
            "version": "1715086922249",
            "content": {
                "message": "Nu är jag WoundTeam",
                "attachments": []
            },
            "senderDisplayName": "Erik Samuelsson",
            "createdOn": "2024-05-07T13:02:02Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c"
                }
            }
        },
        {
            "id": "1715086067417",
            "type": "text",
            "sequenceId": "7",
            "version": "1715086067417",
            "content": {
                "message": "detta har du inte sett Erik",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-07T12:47:47Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            }
        },
        {
            "id": "1715085942468",
            "type": "text",
            "sequenceId": "6",
            "version": "1715085942468",
            "content": {
                "message": "nu skriver jag lite",
                "attachments": []
            },
            "senderDisplayName": "Olof Landahl",
            "createdOn": "2024-05-07T12:45:42Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                }
            }
        },
        {
            "id": "1715085934304",
            "type": "text",
            "sequenceId": "5",
            "version": "1715085934304",
            "content": {
                "message": "Ser du detta så du kan se det kasnke hej?",
                "attachments": []
            },
            "senderDisplayName": "Erik Samuelsson",
            "createdOn": "2024-05-07T12:45:34Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c"
                }
            }
        },
        {
            "id": "1715085889112",
            "type": "text",
            "sequenceId": "4",
            "version": "1715085889112",
            "content": {
                "message": "Hej!",
                "attachments": []
            },
            "senderDisplayName": "Erik Samuelsson",
            "createdOn": "2024-05-07T12:44:49Z",
            "senderCommunicationIdentifier": {
                "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c",
                "communicationUser": {
                    "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c"
                }
            }
        },
        {
            "id": "1715085845573",
            "type": "participantAdded",
            "sequenceId": "3",
            "version": "1715085845573",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-f1d0-273f-874a-ad3a0d005e9c"
                            }
                        },
                        "displayName": "Erik Samuelsson",
                        "shareHistoryTime": "1970-01-01T00:00:00Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                    }
                }
            },
            "createdOn": "2024-05-07T12:44:05Z"
        },
        {
            "id": "1715085774370",
            "type": "topicUpdated",
            "sequenceId": "2",
            "version": "1715085774370",
            "content": {
                "topic": "511b3103-a211-4669-aa7e-74459346cbe2",
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                    }
                }
            },
            "createdOn": "2024-05-07T12:42:54Z"
        },
        {
            "id": "1715085774317",
            "type": "participantAdded",
            "sequenceId": "1",
            "version": "1715085774317",
            "content": {
                "participants": [
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-6c55-0e35-59fe-ad3a0d00fe25"
                            }
                        },
                        "displayName": "Wound Team",
                        "shareHistoryTime": "1970-01-01T00:00:00Z"
                    },
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                            }
                        },
                        "displayName": "Olof Landahl",
                        "shareHistoryTime": "1970-01-01T00:00:00Z"
                    },
                    {
                        "communicationIdentifier": {
                            "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-b4aa-8a47-65f0-ad3a0d003675",
                            "communicationUser": {
                                "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-b4aa-8a47-65f0-ad3a0d003675"
                            }
                        },
                        "shareHistoryTime": "1970-01-01T00:00:00Z"
                    }
                ],
                "initiatorCommunicationIdentifier": {
                    "rawId": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000",
                    "communicationUser": {
                        "id": "8:acs:4810503c-efc9-42bd-ae7d-94094bbed26a_0000001f-71e3-3253-6a49-ad3a0d004000"
                    }
                }
            },
            "createdOn": "2024-05-07T12:42:54Z"
        }
    ]
}`

**Comment by Leah-Xia-Microsoft** [comment]
Hi @olandahl,
Thanks for the additional information. We cannot reproduce the bug on our end and with the information provided, we cannot make a reasonable guess of the potential issue. It would be really helpful if you can provide a sample app when you have the time.
Much appreciated.

**Comment by AmyL219** [comment]
Close the issue right now since long time no response. Please be free to re-open the issue if you have more questions
