### ISSUE TITLE
Issue with Dialpad Component on iOS Devices

### ISSUE THREAD

**Issue by ciaoamigoschat** [Azure/communication-ui-library#4636]
I am testing the Dialpad component available at https://azure.github.io/communication-ui-library/?path=/docs/ui-components-dialpad--dialpad. When tested with Google Chrome on an iOS device, clicking on a number automatically inserts two numbers. This happens after entering the first number. How can I fix this?

**Comment by mgamis-msft** [comment]
Thanks for filing this issue @ciaoamigoschat. We will look for proper fix for this soon.

**Comment by mgamis-msft** [comment]
@ciaoamigoschat we have merged the fix into main. The `longPressTrigger` property of the `Dialpad` component needs to be set to 'touch' on mobile devices. You should see the fix reflected on storybook some time next week. Thanks again for filing this issue.
