### ISSUE TITLE
CallComposite with TeamsCallAdapter , unable to startCall

### ISSUE THREAD

**Issue by MarteenJL** [Azure/communication-ui-library#4657]
**Given a teams user token for teams user starting call ( OID "8:orgid:user-starting-call"  , callee as teams user  (OID "8:orgid:teams-user-receiving-call )  , startCall is not invoked. only joinCall**

Azure Communications UI Library -- branches: develop / jinan-ctega

** run the sample for CallComposite, make call as teams user, hardcode a token within the code ( a fresh token )**
Teams target user is running teams app.

**What behavior did you expect?**
I expected the teams target user to see "call invitation" UI from teams app. They do not get any invitations -- no teams popup for calling.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): [e.g. 1.3.0]
- `@azure/communication-calling` npm package version (if applicable): [e.g. 1.5.4-beta.1]
- `@azure/communication-chat` npm package version (if applicable): [e.g. 1.2.2]

@azure/communication-react to v1.5.1-beta.3",
            "commit": "0c6463eadb465ca4b61abf49bf10acb16ab38109"
            
- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
windows 11

- Browser: [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
MS Edge, 
- Browser Version: [e.g. 1.8.0]

**Is there any additional information?**

I pulled a copy of jinan/cte-ga , hoping that would provide a calling, wasn't able to get that working for starting ( not joining ) a calls as a teams user to another teams user.

code Sample from comm UI works fine to make a call, given the teams token:

const userCallee = { microsoftTeamsUserId: '<MICROSOFT_TEAMS_USER_ID>' };
const oneToOneCall = teamsCallAgent.startCall(userCallee);

https://learn.microsoft.com/en-us/azure/communication-services/how-tos/cte-calling-sdk/manage-calls#place-a-call

rush version:

Rush Multi-Project Build Tool 5.112.2 - https://rushjs.io

npm / node version:
  '@internal/calling': '0.0.1',
  npm: '10.2.3',
  node: '20.10.0',
  acorn: '8.10.0',
  ada: '2.7.2',
  ares: '1.20.1',
  base64: '0.5.0',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.57.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.12+quic',
  simdutf: '3.2.18',
  tz: '2023c',
  undici: '5.26.4',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.3.244.8-node.25',
  zlib: '1.2.13.1-motley'

**Comment by MarteenJL** [comment]
Hi Porter, thanks very much for your reply, I've been looking thru your branch and pull request and am very pleased and grateful to read through your code.
Yes I know its beta, basically though it works.

 I hacked my fork of your pull request, and get calling to work, sort of:

in the nodemodule for CallComposite, the callees aren't getting set.

  const callees = useSelector(getTargetCallees) as StartCallIdentifier[]; file: .....\communication-ui-library\packages\react-composites\src\composites\CallComposite\CallComposite.tsx Below screen shot shows a hacked version with the token , link, to , from , callees all set to predefined value. The actual token is cut-pasted/created from another app. [cid:4b86ec1b-5f30-488a-8302-826e627e3f73]  There's a glitch, but calling appears: [cid:470e6503-c77d-4374-bff8-6557c6f0c651]  [cid:a2c98d6c-c68c-4ab6-946f-373f34182b7b]  Have a great weekend, looking forward to the next commit/merge.
Sincerely,
Marteen Rojo
Jam-Labs
________________________________

**Comment by MarteenJL** [comment]
***@***.*** would like to recall the message, "Re: [Azure/communication-ui-library] CallComposite with TeamsCallAdapter , unable to startCall (Issue #4657)".
This EMAIL is intended for the use of the individual or entity to which it is addressed, and may contain information that is privileged, confidential or exempt from disclosure under applicable law. If you are not the intended recipient, any use, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately.

**Comment by PorterNan** [comment]
> Hi Porter, thanks very much for your reply, I've been looking thru your branch and pull request and am very pleased and grateful to read through your code. Yes I know its beta, basically though it works. I hacked my fork of your pull request, and get calling to work, sort of: in the nodemodule for CallComposite, the callees aren't getting set. const callees = useSelector(getTargetCallees) as StartCallIdentifier[]; file is : .....\communication-ui-library\packages\react-composites\src\composites\CallComposite\CallComposite.tsx Below screen shot shows a hacked version with the token , link, to , from , callees all set to predefined value. The actual token is cut-pasted/created from another app. There's a glitch, but calling appears: ![image](https://github.com/Azure/communication-ui-library/assets/167583465/8b899047-5233-49d0-b5d8-08736031cc15)

Hi Marteen! Thanks again for looking at our code base and try some hacks to make it work, it is always a pleasure to know people are reading our code and try something new there! And your code snippet and screenshot does help us boost our next step for the feature! 

For your investigation, you are in the right path, we don't currently pass callees into teamsCallAdapter, and that would be next work item for this feature we will be working on

**Comment by PorterNan** [comment]
Hi @MarteenJL, I am glad to say we just merged in the change for 1:n calls of teamsAdapter through PR #4671! Please feel free to comment if you find it working or not

**Comment by MarteenJL** [comment]
Hi , sorry for the late reply.  I'm trying the latest revisions, looks like I will have to get deeper into CallComposite.
