### ISSUE TITLE
Dialpad is launching by default for cross framework support

### ISSUE THREAD

**Issue by deshneni-akhil** [Azure/communication-ui-library#4929]
**Describe the bug; what happened?**

I am using js bundle to integrate ACS calling functionality into my application, however despite setting the following flag disableAutoShowDtmfDialer to true I am still seeing the dtmf dailer button upon the call start. 

I see that the issue has been fixed for React [https://github.com/Azure/communication-ui-library/issues/4563](url) I am using the following code to configure the flag for dtmf dailer button.

```
const callAdapter = await outboundCallComposite.loadCallComposite(
                {
                    userId: userId,  // The user's ID
                    token: token,  // The user's token
                    displayName: displayName,  // The user's display name
                    targetCallees: [  // The target callee's details
                        {
                            teamsAppId: teamsAppId,  // The Teams App ID of the callee
                            cloud: "public",  // The cloud type
                        },
                    ],
                    audioOptions: {
                        muted: false, // Set to false to start the microphone unmuted
                    },
                },
                document.getElementById(containerId), // The container for the call composite
                {
                    formFactor: isMobileDevice ? "mobile" : "desktop", // Set the form factor based on isMobileDevice
                    /* disableSurvey: true, // Disable the survey*/
                    callControls: {
                        screenShareButton: {
                            disabled: UseAuthenticationAndAuthorization // Enable/disable the screen share button
                        }
                    },
                    disableAutoShowDtmfDailer: {
                        disabled: false // Enable/disable the DTMF dialer
                    }
                }
            );
```

**In what environment did you see the issue?**

 > Installed the latest call composite bundle

- OS & Device: Windows 11 
- Browser:  Microsoft Edge, Google Chrome

TechStack: I am building web application using C# and JS.  

Am I following the right approach to disable the dtmf dailer button here, I have tried several ways and unable to figure out any insights to fix this issue is appreciated.

**Comment by dmceachernmsft** [comment]
Hi @deshneni-akhil! Thanks for filing the issue! this should be working I will do some looking here, something might be missing from our side. will update when I have an answer here!

**Comment by dmceachernmsft** [comment]
Hi @deshneni-akhil, To clarify your issue are you trying to hide the control to autoshow the dialer over the video gallery? or remove the button from the control bar? To perform the latter you need to do the following:
```ts
const callAdapter = await outboundCallComposite.loadCallComposite(
                {
                    userId: userId,  // The user's ID
                    token: token,  // The user's token
                    displayName: displayName,  // The user's display name
                    targetCallees: [  // The target callee's details
                        {
                            teamsAppId: teamsAppId,  // The Teams App ID of the callee
                            cloud: "public",  // The cloud type
                        },
                    ],
                    audioOptions: {
                        muted: false, // Set to false to start the microphone unmuted
                    },
                },
                document.getElementById(containerId), // The container for the call composite
                {
                    formFactor: isMobileDevice ? "mobile" : "desktop", // Set the form factor based on isMobileDevice
                    /* disableSurvey: true, // Disable the survey*/
                    callControls: {
                        screenShareButton: {
                            disabled: UseAuthenticationAndAuthorization // Enable/disable the screen share button
                        },
                        dtmfDialerButton: false // <- this will remove the button from the control bar
                    },
                    disableAutoShowDtmfDailer: true // <- this will stop the dialpad from showing over the gallery when the call connects
                }
            );
```

**Comment by deshneni-akhil** [comment]
Hello @dmceachernmsft thanks for suggesting on disabling the dtmfdailer button upon call start.  I have added the above code snippet and have re-run my project still the application shows dtmf dailer button upon call being started.

For your look at below screenshots thank you.

<img width="477" alt="image (1)" src="https://github.com/user-attachments/assets/31b58861-990a-4523-b60f-abb2547d017b">
<img width="956" alt="image" src="https://github.com/user-attachments/assets/6ea259c0-fa67-4a56-a1a2-12754b0a6f6b">

**Comment by dmceachernmsft** [comment]
Hi @deshneni-akhil, Thanks for the images! Can you please share the following with me:
- whether you are calling a CallQueue or a AutoAttendant?
- How old your bundle you are working with is? if you try the bundle from the public preview [1.18.0-beta.1](https://github.com/Azure/communication-ui-library/releases/download/PublicPreview%2F1.18.0-beta.1/outboundCallComposite.js) found in releases these API's should be working

**Comment by deshneni-akhil** [comment]
@dmceachernmsft  thanks for the release link I am using the outbound file using the following website [https://github.com/Azure/communication-ui-library/releases/latest/download/callComposite.js](url)

After using the above link, the Dialpad has been disabled thanks for the latest release link.

You can close this ticket have a great day

**Comment by dmceachernmsft** [comment]
Excellent glad to hear we could help!
