### ISSUE TITLE
Camera preview doesn't work in latest CallComposite

### ISSUE THREAD

**Issue by iMicknl** [Azure/communication-ui-library#497]
**Describe the bug; what happened?**

Updating @azure/communication-react from `1.0.0-alpha-20210623.9.0` to `1.0.0-alpha-20210624.13.0` broke the camera preview functionality for me, which is perhaps caused by https://github.com/Azure/communication-ui-library/pull/491.

**What are the steps to reproduce the issue?**
1. Use the calling composite sample on main (or use 1.0.0-alpha-20210624.13.0)
2. Start or join a call
3. Check if Camera field is persisted with your first choice
4. Try to press 'Turn on'
5. (won't work)
6.  Select another camera in the list
7. Switch back to your original camera
8. Press turn on (works!)

**What behavior did you expect?**
Camera will load on first try, without having to reselect.

**If applicable, provide screenshots:**

https://user-images.githubusercontent.com/1424596/123241274-4a0c9200-d4e1-11eb-8315-715d5e62563f.mp4

**In what environment did you see the issue?**

- OS & Device: Windows 10, Surface Laptop 3
- Browser: Edge Chromium
- Version: Version 91.0.864.54 (Official build) (64-bit)

**Is there any additional information?**
Happy to share my public repro site via Teams internally if that helps.

**Comment by JamesBurnside** [comment]
Thanks for the detailed bug report! (and the incredibly fast selfhosting!)
@mgamis-msft can you take a look at this today?

**Comment by iMicknl** [comment]
Thanks @JamesBurnside, and no hurry! We are not using this version in production, just faced it while updating my demo app. I have reverted to the previous version which is fine for demo purposes.

**Comment by mgamis-msft** [comment]
> Thanks for the detailed bug report! (and the incredibly fast selfhosting!)
> @mgamis-msft can you take a look at this today?

I have just merged in a fix for this. Thanks for filing this issue.
