### ISSUE TITLE
ChromeOS not supported

### ISSUE THREAD

**Issue by deshneni-akhil** [Azure/communication-ui-library#5016]
**Describe the bug; what happened?**

We have developed a web application using Blazor and integrated Call Composite through cross-framework support using JavaScript files. The application performs well across multiple platforms, including Windows, iOS, and mobile browsers. We are experiencing compatibility issues when attempting to run the application on Chrome OS which is a critical issue for us as we intend to deploy the application on kiosks running Chrome OS.

**If applicable, provide screenshots:**
![image (2)](https://github.com/user-attachments/assets/c4c1a593-cb19-4070-a6c3-8376b1d0de5c)

**In what environment did you see the issue?**

- `@azure/communication-calling`  version:

[https://github.com/Azure/communication-ui-library/releases/download/PublicPreview%2F1.18.0-beta.1/callComposite.js](url)

- OS & Device: Google Chome OS Flex Version 126.0.6478.222 (Official Build) (64-bit) 
- Browser: Google Chrome,
- Browser Version:  Version 126.0.6478.222 (Official Build) (64-bit)

**Is there any additional information?**

We are targeting deployment on kiosks running Chrome OS, and resolving this issue is critical any workaround on how to mitigate this issue is highly appreciated.

**Comment by alkwa-msft** [comment]
(Currently doing some summer Github cleaning and I realized we unfortunately left you on a cliffhanger, and you may need to sit tight for a bit longer)

@deshneni-akhil 

Thank you for reaching out and sharing your interest in ChromeOS support for Azure Communication Services. At this time, ChromeOS support is not on our immediate roadmap as we are prioritizing other key areas within Azure Communication Services.

However, we are keen to revisit this in the future and would love to gather more feedback and continue testing over the next few quarters. Your insights are invaluable to us, and we would greatly appreciate learning more about your specific customers, their use cases, and their anticipated call volumes. This information will help us better prioritize and potentially integrate ChromeOS support into our upcoming roadmap.

Thank you for your understanding and support. We look forward to hearing from you.
