### ISSUE TITLE
Capabilities banner displayed from the beginning of meeting

### ISSUE THREAD

**Issue by juanmanuelpuhl** [Azure/communication-ui-library#5021]
Hello!
Since I updated to @azure/communication-react 1.18.1 I see that the capabilities banner is displayed from the beginning of the meeting, even though we are not changing the capabilities since the creation of the onlineMeeting. So when a user joins he sees this (which doesn't make much sense to show in my opinion):

<img width="401" alt="Screenshot 2024-08-08 at 1 10 08 PM" src="https://github.com/user-attachments/assets/fdd31860-1b9f-4565-80f0-ac3d82709d0f">

Prior to this I was using the 1.15.0 version and it didn't have this issue.

**In what environment did you see the issue?**

- `@azure/communication-react` 1.18.1
- `@azure/communication-calling` 1.27.3
- `@azure/communication-chat` 1.5.2

- OS & Device: MacOS, iOS, android (I understand this is a general issue not based in the OS anyways)
- Browser: Safari, Chrome (not related to browser anyways)

**Comment by mgamis-msft** [comment]
Hi @juanmanuelpuhl, this has been recently fixed but it would be available in the next beta release 1.19.0-beta.1 which will be available some time today or tomorrow or the next stable release 1.19.0 which should available in the next two weeks.

**Comment by juanmanuelpuhl** [comment]
Hi @mgamis-msft  thanks for the quick response. Got it, I'll be waiting for that release :)

**Comment by jpeng-ms** [comment]
hi @juanmanuelpuhl we have just released 1.19.0-beta.1, free feel to give it a try and let us know if you have more questions :) 

https://www.npmjs.com/package/@azure/communication-react/v/1.19.0-beta.1
