### ISSUE TITLE
It is not possible to create a ChatComposites using a Teams user.

### ISSUE THREAD

**Issue by andre-ols** [Azure/communication-ui-library#5040]
In the documentation there are only examples demonstrating how to join a meeting as a Teams user using CallComposites. However, there is no example demonstrating how to create a ChatComposites, not even a CallWithChatComposites. A user who is authenticated as a Teams user cannot use chat?

**Comment by palatter** [comment]
Hi @andre-ols,

Currently we only support CTE for Call scenarios.

Are you part of the TAP program?

**Comment by andre-ols** [comment]
> Hi @andre-ols,
> 
> Currently we only support authenticated as a teams user for Call scenarios.
> 
> Are you part of the TAP program?

What would the TAP program be?

**Comment by seanryankeegan** [comment]
Hi @andre-ols,

I'm Sean, a Developer Evangelist on the Azure Communication Services team and I run our TAP program! 

For a bit of info on what that is:
The TAP (Technology Adoption Program) is designed to give participants early access to new features and updates. By joining, you can provide feedback directly to our team, helping shape the product to better meet your needs. It's a great way to stay ahead and contribute to the development process. Additionally, your feedback helps us collect customer signals, which is crucial for understanding the demand for functionalities like ChatComposites.

I'd be happy to chat more about this, or you can apply to join by filling out [this form](https://aka.ms/acs-tap-invite).

**Comment by jpeng-ms** [comment]
Hi @andre-ols 

it has been a while since we hear from you so I will go ahead to close off this issue for now, if you like, please reopen anytime if you have more questions for us :)
