### ISSUE TITLE
Audio Noise Suppression in 1.19.0-beta.1

### ISSUE THREAD

**Issue by realjesset** [Azure/communication-ui-library#5078]
**Describe the bug; what happened?**
I am unable to add noise suppression to the call when using call composite 
**What are the steps to reproduce the issue?**
use call composite and the audio from participants are echo-y
**What behavior did you expect?**
participants except calls to have good audio 
**In what environment did you see the issue?**

- `@azure/communication-react`: 1.19.0-beta.1
- `@azure/communication-calling`: 1.28.1-beta.3
- `@azure/communication-chat`: 1.3.2
- `@azure/communication-calling-effects`: 1.1.1-beta.1

- OS & Device: macOS
- Browser: Chrome

**Is there any additional information?**
calling-effects library has deep noise cancelation but I when I try to apply it, it doesn't seem to be working
https://learn.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling-effects/deepnoisesuppressioneffect?view=azure-communication-services-js

<img width="919" alt="Screenshot 2024-08-27 at 6 06 23 PM" src="https://github.com/user-attachments/assets/be3ac4c8-a527-422b-ad1d-7236a1ad32b5">

**Comment by mgamis-msft** [comment]
Hi @realjesse, thanks for filing an issue. I will consult whether adding deep noise suppression is possible to our latest beta.
Note: we are currently adding deep noise suppression to our adapter for an upcoming release

**Comment by realjesset** [comment]
yes I am getting the same console log as you are for the microphone

**Comment by mgamis-msft** [comment]
@realjesset I tested your code locally and found that deep noise suppression does not work and when I debugged, in the adapter code, the local audio stream effects of the call after it started. I found that deep noise suppression was not active, only browser noise suppression.
![image](https://github.com/user-attachments/assets/1c60a0eb-1bae-4dde-af69-c6ff52e140b4)
It looks like creating local audio streams from devices obtained from the adapter state does not persist in the call the call adapter subscribes.

We are currently working on adding deep noise suppression to our library.
Would it be alright if we could have deep noise suppression available as a function on our call and callwithchat adapter in our next stable version in about 2 weeks or the next beta version in about a month?
You would start deep noise suppression like so:
```
await adapter.startNoiseSuppressionEffect();
```

**Comment by mgamis-msft** [comment]
Just to give an update here, deep noise suppression will be available from the CallAdapter and CallWithChatAdapter in our next stable release targeted for Oct 11.

**Comment by mgamis-msft** [comment]
@realjesset Deep noise suppression has now been released in version [1.20.0](https://www.npmjs.com/package/@azure/communication-react/v/1.20.0). You can try it out by following the "Usage" section from our deep noise suppression storybook page [here](https://www.npmjs.com/package/@azure/communication-react/v/1.20.0). Please let us know if you have any other questions or issues with deep noise suppression.
