### ISSUE TITLE
[Feature request] Make CallComposite responsive / mobile friendly

### ISSUE THREAD

**Issue by iMicknl** [Azure/communication-ui-library#513]
**What feature are you requesting?**

It would be great if the CallComposite would have some (basic) responsive support. Currently it is mostly functional on iOS and Android, however the layout is distorted since it doesn't support small screen layouts.

Currently the CallComposite is hard to use in a mobile first / friendly scenario and thus requiring using the Stateful client with quite some modifications.

**What would be the benefit of adding this feature?**

Customers can more easily get started in a mobile scenario.

**What solution would be ideal for you?**

Basic support for small screen sizes in the CallComposite

**What alternatives have you considered?**

Use the Stateful client / UI library with custom styling

**Is there any additional information for your request?**

CallComposite is currently not used by my customer case, since we require other modifications. However, when the CallComposite would be responsive, I would imagine that some underlying components also benefit from this change. 

**Attach screenshots or images add detail to your request:**

**Comment by JamesBurnside** [comment]
We definitely have this item in our immediate backlog for both calling and chat and is important to us, perhaps @alkwa-msft @ddematheu2 can comment on a potential timeline for responsive support

**Comment by JamesBurnside** [comment]
Made small improvements to call composite here to make it actually usable on mobile https://github.com/Azure/communication-ui-library/pull/533.
However there is still a lot of polish to go to make it a premium experience that will be tackled at a future date

**Comment by iMicknl** [comment]
Thanks, @JamesBurnside this is already a great improvement! I encountered a few bugs / improvements, does it make sense to report them already or are they already tracked internally for the future premium experience?

Examples are:

- Join screen is not fully responsive yet. (tested on iPhone 11 Pro) [screenshot](https://user-images.githubusercontent.com/1424596/124932025-0480b680-e003-11eb-898f-233204c361f4.PNG)

- Pre join screen has wrong icon alignment and 'Your camera is turned off' is using a different font. (tested on iPhone 11 Pro) [IMG_9740](https://user-images.githubusercontent.com/1424596/124932229-2e39dd80-e003-11eb-80c7-744fc5368dbc.PNG)

- On iOS there are pause buttons when you touch a video area. (tested on iPhone 11 Pro)

- Perhaps the pre-join screen should take the camera orientation into account (portrait vs landscape)
(this is also something that perhaps should be possible in all video views, since currently you cannot do 'zoom to fit' like with Teams).

**Comment by JamesBurnside** [comment]
Definitely report them so they can't be missed ♥ Hopefully it won't be too long before we get round to tackling them, we have some known issues being tracked explicitly as bugs that might be duplicates but I'd rather have them in two places than no places. I've mentioned this issue on our work item to make the composites fully responsive to ensure anything reported here is addressed (https://skype.visualstudio.com/SPOOL/_backlogs/backlog/Web%20UI/Features/?workitem=2492702).

**Comment by leijae** [comment]
for the time being I added boostrap classes with jquery. this kind of helped... it's not perfect or ideal, but it gets the job done

        $('.css-83').addClass('col-sm-6 mx-auto');
        $('.css-111').addClass('col-sm-6 mx-auto text-center');
        $('.css-82').addClass('row pt-2 d-block');
        //$('.css-82').addClass('d-block');
        $('.css-112').addClass('mx-auto text-left');
        //$('.root-110').remove();
        $('.css-73').text('')
        $('.flexContainer-133').text('JOIN CALL');

**Comment by ddematheu2** [comment]
Captured in our backlog. If there any additional specific bugs, please create new issues to tackle them individually.
