### ISSUE TITLE
[Feature request] CallComposite features should be disabled if they are not available

### ISSUE THREAD

**Issue by iMicknl** [Azure/communication-ui-library#514]
**What feature are you requesting?**

It would be great if the CallComposite (of full UI SDK) could implement graceful degradation or progressive enhancement principles. It can be confusing for the end-user when features are not working, due to device or browser limitations.

Think of;

1. Disable screen sharing button when user is using mobile (iOS / Android)
2. Disable speaker picker in pre-join screen when not available (iOS / Android (?))
and perhaps more that I couldn't think of yet.

**What would be the benefit of adding this feature?**

Currently the button is visible and enabled which confuses users and developers. They think this is a feature that is supported, where it is not supported (which is already documented).

**What solution would be ideal for you?**

Best would be if the SDK / CallComposite could detect if screen sharing is possible in the users browser, and enable/disable accordingly. However, I am not sure if it is possible to detect this programmatically. 

**What alternatives have you considered?**

n/a

**Is there any additional information for your request?**

CallComposite is currently not used by my customer case, since we require other modifications. And in the end, screen sharing should not be possible by the guest, thus this will be disabled entirely. However we faced this and I can imagine that this is problematic for other customers eventually.

**Attach screenshots or images add detail to your request:**

**Comment by JamesBurnside** [comment]
I fully support this idea. Out of interest do you think we should hide functionality like this when unavailable on certain devices, show the button/feature as greyed out (or equivalent), or when interacted with present an informational with something like: "this feature is not available on your device". (+ @alkwa-msft @ddematheu2).

As a note specifically for detecting screenshare availability we should be able to use this API: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia

**Comment by iMicknl** [comment]
> Out of interest do you think we should hide functionality like this when unavailable on certain devices, show the button/feature as greyed out (or equivalent), or when interacted with present an informational with something like: "this feature is not available on your device".

I wasn't sure about this one, thus I hope that a UI/UX designer wants to think about this. 😃 

If the feature is greyed out, it would make sense to show a tooltip / message that this functionality is not supported on the current device. However, having all those disabled features could clutter the interface a lot, especially on mobile.

**Comment by leijae** [comment]
Personally, I'd like to programatically remove features also. In my use case there are certain times that I don't even want screen-sharing as an option. But all the buttons have the same css class.

**Comment by iMicknl** [comment]
> Personally, I'd like to programatically remove features also. In my use case there are certain times that I don't even want screen-sharing as an option. But all the buttons have the same css class.

This is something that I would love as well for the CallComposite. Perhaps best to log this as a new issue @leijae?

**Comment by ddematheu2** [comment]
I have added both enhancements as feedback to our backlog.
