### ISSUE TITLE
Camera/audio toggles on mobile devices

### ISSUE THREAD

**Issue by paddotk** [Azure/communication-ui-library#516]
These findings are based on the sample app that uses the CallComposite.

**Describe the bug; what happened?**
1) Trying to switch cameras freezes/crashes the page. This seems to happen when the camera is turned on in the app, when I switch my camera and then turn it on, it works fine. This occurs on both the config page as well as in the call itself.

2) The speaker dropdown says 'select an option', tapping it doesn't do anything. Presumably because the device only has one speaker, but it can't be selected. When starting the call, the speaker does work.

**In what environment did you see the issue?**
A deployed online app.

- OS & browser:
  - Device 1: Android 11 / Chrome 88.0
  - Device 2: Android 8.1.0 / Chrome 91.0

**Is there any additional information?**

**Comment by JamesBurnside** [comment]
Hi @paddotk thanks for filing these issues!

For 1 - I can't repro this on ios, I'll have someone try repro on an android device shortly
For 2 - I _can_ repro this every time on my ios device. Currently we are doing our internal bug tracking through Azure DevOps so I have filed a bug there and will update this thread when it is addressed. We have a large item in our backlog to tackle the interface on mobile so it should be addressed then (but unlikely before then). ADO bug: https://skype.visualstudio.com/SPOOL/_workitems/edit/2506754. We should either not be showing the unselectable speaker dropdown - or have the default speaker showing inside the dropdown and still show the speaker icon:
![image](https://user-images.githubusercontent.com/2684369/124518323-f7618e80-dd9a-11eb-91ef-b3ce6f22d48e.png)

**Comment by JamesBurnside** [comment]
Hi @paddotk we've been unable to repro on our android devices either, what specific device are you using?

**Comment by JamesBurnside** [comment]
@paddotk closing this issue as we cannot repro the cameras freezes/page crash. We have a large work item to make the composites mobile friendly where we will be addressing the speaker button bug. If you are able to provide further details on the crash we will be happy to reopen and take another look
