### ISSUE TITLE
[Question] Are the libraries from the StaticHTMLCompositeSample available on NPM?

### ISSUE THREAD

**Issue by leijae** [Azure/communication-ui-library#532]
If I have an existing web app that isn't a reat-app to begin with, and I want to implement calling, I already have to install the react components for this work. 

If I understand the docs correctly, I also must now work with yet another package manager, Rush.  Or is there an npm package that I can add to packages for the necessary components?

**Comment by JamesBurnside** [comment]
Hi @leijae! Our package is available to use here from npm: https://www.npmjs.com/package/@azure/communication-react.

For more information check out our storybook documentation here: https://azure.github.io/communication-ui-library/?path=/story/quickstarts-composites--page

**Comment by leijae** [comment]
yea there's just a ton of moving parts and I'm getting dizzy... I'd love to see a: Add ACS Calling to an existing MVC app (sans-react)...  haha

thanks for the info @JamesBurnside
