### ISSUE TITLE
Reactions Button is not exported from 1.20.0

### ISSUE THREAD

**Issue by juanmanuelpuhl** [Azure/communication-ui-library#5370]
Hi, I'm in the process of updating my app and its libraries to the latest version and I noticed that I can't compile because I have some of my imports wrong. One of them is ReactionButton. This component is marked as @Public (checking here) and I noticed that I can import ReactionButtonProps and ReactionButtonStrings from "@azure/communication-react", but for some reason, ReactionButton is only imported from "@azure/communication-react/dist/dist-esm/react-components/src", which isn't an exported path and my app doesn't compile. 
This wasn't an issue in older versions, but now I can't continue updating. 
I was using  "@azure/communication-react": "1.19.0-beta.3", and I wanted to update to  "@azure/communication-react": "1.20.0".

Also I was wondering if this is already fixed in latest version (I can't test right now due to the above issue):
My team and I were testing the reactions button and noticed that if we want to use our app with keyboard and select any reaction from the menu we can't, which is an accessibility issue. We haven't changed any of the logic of the Reaction button, we just import it and let it handle everything on its own.
If this was already solved in latest version please let me know and we can disregard it :)

**Comment by dmceachernmsft** [comment]
Hi @juanmanuelpuhl Thanks for filing the issue! For the Reaction button component itself we do not currently export it from the API. We can discuss this if this is a feature you would like for building a component based application, but it is included with our composites as of today. 

As for the accessibilty issue this bug should be fixed in the newer versions and should have been included in 1.20.0.

**Comment by juanmanuelpuhl** [comment]
Hi @dmceachernmsft thanks for the quick response. We are building a custom control bar just to display buttons and settings in a more compact way. It would be awesome to have it accesible outside of the composite. 
I tried using the composite control bar, but it isn't as customizable as we would want. So I guess we will stick with the custom approach

**Comment by dmceachernmsft** [comment]
Thanks for letting us know about your scenario. If the button was exported from the API are you wanting to create the props for the button yourself for it to be more compact with say 3 reactions? its not impossible for us to release it just want a strong signal before we add something to the API. 

Side question: For your CallAdapter are you constructing it from a stateful client and CallAgent? This will make the reactions button hook into the composite (and other custom buttons for that matter) more easily if you use our `createAzureCommunicationCallAdapterFromClients` factory function.

**Comment by juanmanuelpuhl** [comment]
> If the button was exported from the API are you wanting to create the props for the button yourself for it to be more compact with say 3 reactions?

We don't have any requirements for it to have less reactions, but could be a nice to have. 

It would be awesome to also have access to other features that are inside call composite, for example, closed captions. Currently in the older library version we are able to create our own button for that, and call the `CaptionsSettingsModal`. But with the latest changes we are not able to do so, because of it being private now. 

> Side question: For your CallAdapter are you constructing it from a stateful client and CallAgent? This will make the reactions button hook into the composite (and other custom buttons for that matter) more easily if you use our createAzureCommunicationCallAdapterFromClients factory function.

Not right now. As part of the update to the latest version we need to rethink how we create the adapters. We are currently using `createAzureCommunicationCallWithChatAdapter` and then we create `CallWithChatBackedCallAdapter` and `CallWithChatBackedChatAdapter` to pass to the components for the CallComposite, and ChatComposite. I know those are private now, and we would need to take a look into that factory function you mention, and the new apis.

**Comment by dmceachernmsft** [comment]
Hi @juanmanuelpuhl so for the reactions button we will be hoping to include it in our next stable release per your request. 

For your ask for captions we should be including the `adapter.startCaptions()` on the Adapters. This will allow you to bring up the captions UI in the composite. There should be accompanying handlers for the captions feature like setting language as well. For the release of the actual component of the captions banner we will need more time to make a decision there and will get back to you about it.

For other composite items do you happen to have a list of the features you and your team might want? we love to get more signals that customers are looking for new things in our component offerings so please fire away if you have them and I will take them to the team!

**Comment by dmceachernmsft** [comment]
Hi @juanmanuelpuhl we have made a new release 1.21.0. The Reaction button component is released with it. Just like with the reactions for our composites you will need to provide the reaction resources to the button just like to our adapter with an object like this
```typescript
    const reactionResources: ReactionResources = {
      likeReaction: { url: 'path/to/your/sprite/like.png', frameCount: 128 },
      heartReaction: { url: 'path/to/your/sprite/heart.png', frameCount: 128 },
      laughReaction: { url: 'path/to/your/sprite/laugh.png', frameCount: 128 },
      applauseReaction: { url: 'path/to/your/sprite/applause.png', frameCount: 128 },
      surprisedReaction: { url: 'path/to/your/sprite/surprised.png', frameCount: 128 }
    };
```

you can read more about this here: https://azure.github.io/communication-ui-library/?path=/docs/concepts-meeting-reactions--docs

Going to close this issue as the button is now released. please re-open the issue if there is any other problems related to the Reactions button
