### ISSUE TITLE
Unable to start captions automatically when starting/joining the call

### ISSUE THREAD

**Issue by deshneni-akhil** [Azure/communication-ui-library#5429]
**Describe the bug; what happened?**

After initializing the adapter I want to enable captions, here I have used startCaptions configuration however the screen is stuck at starting Captions and does not start captions during the entire duration of the call with agent. Further, setting startInBackground flag to true doesn't start captions facing the same issue here also.

await newAdapter.startCaptions({
        spokenLanguage: "en-us",
        startInBackground: false
  });

**What behavior did you expect?**
Captions start to work after user manually enables them through the more options, here we want to enable the captions in background so upon call being connected with an agent captions screen should be shown currently this configuration is not being honored.

**If applicable, provide screenshots:**

![Image](https://github.com/user-attachments/assets/84f44014-4b90-49ae-8b44-022a686faa7d)

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): [1.20.0]

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser: [e.g. Microsoft Edge 131.0.2903.51]

**Comment by alkwa-msft** [comment]
We haven't gotten any response from the developer in a number of weeks. We are going to close this now. @deshneni-akhil  feel free to re-open when you have more to share based on this comment https://github.com/Azure/communication-ui-library/issues/5429#issuecomment-2486366858
