### ISSUE TITLE
Control Bar Buttons with labels don't have cursur: pointer on hover

### ISSUE THREAD

**Issue by iMicknl** [Azure/communication-ui-library#553]
**Describe the bug; what happened?**
Very small bug, but when you hover over a button in the control bar, you won't always see the `cursor: pointer` ('hand'). This happens when you hover over the label text.

The `<label>` has a `cursur: default`, instead of `cursor: pointer`.

**What are the steps to reproduce the issue?**
See above.

https://azure.github.io/communication-ui-library/?path=/story/ui-components-controlbar-buttons-camera--camera

**What behavior did you expect?**
Button should have cursor pointer for the whole element.

**If applicable, provide screenshots:**
Couldn't manage to have this on my screenshot yet, but can make a video if you can't reproduce.

**In what environment did you see the issue?**

- OS & Device: macOS / Windows
- Browser: Edge Chromium
- Version: 91.0.864.64 (Official build) (64-bit)

**Is there any additional information?**

**Comment by mgamis-msft** [comment]
Thanks for the detailed big report (and fix for it as well :)). I will work on this bug today.

**Comment by mgamis-msft** [comment]
#567

**Comment by iMicknl** [comment]
@mgamis-msft could it be that this issue is here again? I can still reproduce it on my environment.

`"@azure/communication-react": "^1.0.0-alpha-20210929.10.0",`
