### ISSUE TITLE
[Feature Request] When Call session is over don't return to start a call screen.

### ISSUE THREAD

**Issue by leijae** [Azure/communication-ui-library#555]
**What feature are you requesting?**
When a call has been completed, a user is forwarded back to the "Start a call" view. Es no bueno, a customer could make additional calls after the host has left incurring more charges than inticipated.

**What would be the benefit of adding this feature?**
proper business logic

**What solution would be ideal for you?**
Some kind of thanks for participating screen. Google meets looks like this (not saying it should exactly like theirs, but something like it...)
![image](https://user-images.githubusercontent.com/50371033/124985494-1876e900-e000-11eb-803f-64b124be0649.png)

**What alternatives have you considered?**
I tried catching the click event with jquery on css class root-157 and forwarding to a different page with window.href, but the event isn't caught... darn the DOM!

**Comment by JamesBurnside** [comment]
@leijae great feedback! We should be showing a call ended screen or perhaps simply nothing. We do expect consumers to want to present their own call ended screen after the callended event but we need a better default action.

If you want to detect when the call ends, currently the `callComposite.js` returns the adapter that was created:
```
export const loadCallComposite = async function (args, htmlElement) {
  const { userId, token, groupId, displayName, onCallEnded } = args;
  const adapter = await createAzureCommunicationCallAdapter(userId, token, { groupId }, displayName ?? 'anonymous');
  adapter.on('callEnded', onCallEnded);
  ReactDOM.render(React.createElement(CallComposite, { adapter }, null), htmlElement);
  return adapter;
};
```

Using the returned adapter you can hook into the callEnded event by doing:
```
const adapter = await loadCallComposite(myArgs, myHtmlElement);
adapter.on('callEnded', (e) => {
    // do something when the call ends
});
```

**Comment by leijae** [comment]
confirmed. that did work. not does forward to my custom page. merci beaucoup

**Comment by leijae** [comment]
closing this issue because I think it's probably on your radar, and I'm still able to accomplish what I need to.
