### ISSUE TITLE
[Bug] Full text of system message is not displayed in `Message Thread` component

### ISSUE THREAD

**Issue by aakashbhardwaj619** [Azure/communication-ui-library#573]
**Describe the bug; what happened?**
The `Message Thread` component does not display the full text of any system message if it is overflowing the parent container.

**What are the steps to reproduce the issue?**
Add the `Message Thread` component to a React component and add any system message. Reduce the screen width and notice that the overflowing text of the system message is not displayed.
 OR
Reduce the screen width of the `Message Thread` [story page](https://azure.github.io/communication-ui-library/?path=/story/ui-components-messagethread--message-thread) and notice that the overflowing text of the system message is not displayed.

**What behavior did you expect?**
The overflowed text should be displayed in the next line similar to user messages.

**If applicable, provide screenshots:**
![AcsSystemMessageIssue](https://user-images.githubusercontent.com/33526902/125436011-00a74794-8f51-4b22-8940-68e1b133742b.jpeg)

**In what environment did you see the issue?**

- OS & Device: **Windows**
- Browser **Microsoft Edge**
- Version **1.0.0-beta.1**

**Is there any additional information?**

**Comment by mgamis-msft** [comment]
Thank you for the detailed bug report. I will work on this bug today.
