### ISSUE TITLE
Messages with type 'html' are ignored in chat thread

### ISSUE THREAD

**Issue by artempl** [Azure/communication-ui-library#583]
Trying to display messages sended from java client with 'html' type (valid values for java SDK of azure communication are 'text' and 'html' https://github.com/Azure/azure-sdk-for-java/blob/af17a1edd24e440b8ea83535a5ebcd3acce9f9b8/sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/models/ChatMessageType.java#L17; ), and chatThread component doesn't display it (beacause of filtering of messages with types 'text' and 'richtext/html').
But from Java side we can't pass 'richtext/html' value for type field, it fails validate message:

`Request processing failed; nested exception is com.azure.communication.chat.models.ChatErrorResponseException: Status code 400, "{"communicationError":{"code":"BadRequest","message":"One or more validation errors occurred.","details":[{"message":"The input was not valid.","target":"type"}]}}"`

Please add support 'html' type at this point:
https://github.com/Azure/communication-ui-library/blob/67d957723e67f2a3fd5ab444f085cb89113966de/packages/chat-component-bindings/src/chatThreadSelector.ts#L48

**Comment by mgamis-msft** [comment]
Thanks for filing this issue. I will file a bug and work on the fix.
