### ISSUE TITLE
Add the option to set margin values for the chat message container

### ISSUE THREAD

**Issue by aakashbhardwaj619** [Azure/communication-ui-library#605]
**What feature are you requesting?**
Add the option to set margin values for the chat message container.

**What would be the benefit of adding this feature?**
This will give more control to style the containers as per requirement.

**What solution would be ideal for you?**
The **margin-left** and **margin-right** options should apply to the chat message container.

**What alternatives have you considered?**
I tried setting **margin-right** to **0px** using the below code but it does not work.

```typescript
const messageThreadStyle: MessageThreadStylesProps = {
  chatMessageContainer: {
    marginRight: '0px'
  }
};
```

**Attach screenshots or images add detail to your request:**
<img width="773" alt="AcsAlignMessage" src="https://user-images.githubusercontent.com/33526902/126287939-3ce4de17-38ab-4cc3-8033-febe307b8b7d.png">

**Comment by JamesBurnside** [comment]
@aakashbhardwaj619 thanks for filing this issue, I agree it would be useful to be able to remove these margins and by default there doesn't look to be a way to do that through our current API - we'll look into creating a fix for this

**Comment by JamesBurnside** [comment]
For more context on this issue this component is currently wrapping around fluent northstar's (N*) chat component: https://fluentsite.z22.web.core.windows.net/0.57.0/components/chat/definition
By default they add this spacing in there without an interface to remove it.

The culprit component lies in an implictly defined element between the chat container element: https://github.com/Azure/communication-ui-library/blob/2cbec06050204f200bda2c5034a02b30f638f6af/packages/react-components/src/components/MessageThread.tsx#L833 and the head element of our rendered chat messages: https://github.com/Azure/communication-ui-library/blob/2cbec06050204f200bda2c5034a02b30f638f6af/packages/react-components/src/components/MessageThread.tsx#L330

(note: it is _not_ related to the gutter property the N* chat component exposes)

For fixing this we would likely need to target the parent element of the message but we should engage with the fluent team to provide a mechanism from which to do so. We could directly override the parent element's css but this would be a brittle fix. @alkwa-msft would you be able to continue this investigation further?
