### ISSUE TITLE
Update to latest Calling SDK (v1.2.1-beta.1)

### ISSUE THREAD

**Issue by iMicknl** [Azure/communication-ui-library#751]
**What feature are you requesting?**

Is there an ETA when the `@azure/communication-calling` dependency will be updated to the latest version, especially for the composite? This is a relatively small change (hopefully), but it will make it a lot easier to test if the new calling SDK fixes.

https://github.com/Azure/Communication/blob/master/releasenotes/acs-javascript-calling-library-release-notes.md#v121-beta1-2021-08-26

Especially issues with Android phones should be fixed now, thus it is good to have this tested with the UI library.

**What would be the benefit of adding this feature?**

**What solution would be ideal for you?**

**What alternatives have you considered?**
Run it from source, which is cumbersome.

**Comment by alkwa-msft** [comment]
Thanks for sharing this issue. Currently looking into this.

**Comment by alkwa-msft** [comment]
https://www.npmjs.com/package/@azure/communication-react/v/1.0.0-alpha-20210910.10.0

The change should be in the build
https://github.com/Azure/communication-ui-library/commit/e337a0813532da34430795921a4bfc324453d881

**Comment by iMicknl** [comment]
Thanks @alkwa-msft! :)

We will do some testing in the coming weeks, and this will help a lot.
