### ISSUE TITLE
Options button does not work with `react-full-screen` in CallComposite

### ISSUE THREAD

**Issue by harrychy8** [Azure/communication-ui-library#775]
**Describe the bug; what happened?**
When the page is at full screen (note this is with react-full-screen, not an F11 full screen), the options button does not work

**What are the steps to reproduce the issue?**
Wrap the composite with Full Screen following this [link](https://www.npmjs.com/package/react-full-screen), start the call, enter full screen and click on the options button

**In what environment did you see the issue?**

Windows on PC
Google Chrome

**Comment by alkwa-msft** [comment]
It looks like both the flyout menu and react-fullscreen use fixed positioning in order to achieve their goals. This creates collisions. @harrychy8 

https://github.com/microsoft/fluentui/issues/2178

**Comment by alkwa-msft** [comment]
This issue is stale and we will close it. If others feel strongly about this issue we can re-open it and look further into this.

**Comment by PorterNan** [comment]
The fixed #1950 was checked in, the problem should be fixed, close this issue and feel free to reopen this you still can repro it
