### ISSUE TITLE
"html" messages do not render in chat in ChatComposite

### ISSUE THREAD

**Issue by mmarinhomac** [Azure/communication-ui-library#824]
All messages of type "html" are not rendered in chat!

With two chats open in parallel, sending a file through the first one, in the second chat in real time it is possible to see the message (tag a with link) that has just been sent, but when closing the chat and reopening all html messages are not rendered.

I'm sending a message like this:
```
const threadClient = new ChatThreadClient(endpointUrl, threadId, new AzureCommunicationTokenCredential(token));
threadClient.sendMessage({
  senderDisplayName: chatData.userName,
  content : `<a href='google.com' target='_blank'>Arquivo</a>`
}, { type : "html" });
```

Chat - Image:
![chat-without-links](https://user-images.githubusercontent.com/47289225/134737318-7693a082-d55d-420f-990f-84da3e7d1408.png)

HTML DevTool - Image:
![html-without-links](https://user-images.githubusercontent.com/47289225/134737342-fdb991d6-c243-47a9-8310-100a692712f1.png)

Response API - Image:
![response-api-with-links](https://user-images.githubusercontent.com/47289225/134737364-54038e59-d968-4267-9217-8e74d6693588.png)

- Windows on PC
- Browser [Google Chrome]
- Version lib beta.4 and beta.5 ❌

Version beta.3 working normally ✅

**Comment by prprabhu-ms** [comment]
Thanks a lot for filing this bug. I'll take a look shortly.
