### ISSUE TITLE
Height/Width should be 100% in Quickstart or Generated Boilerplate

### ISSUE THREAD

**Issue by anujb-msft** [Azure/communication-ui-library#939]
Height/Width should be 100% in Quickstart or Generated Boilerplate

**Describe the bug; what happened?**
The Composite Quickstart experience does not automatically adjust the React app styling to expand too 100% height/width

**What are the steps to reproduce the issue?**
Follow the quickstart here
https://azure.github.io/communication-ui-library/?path=/story/quickstarts-composites--page

And achieved the result in the screensot

**What behavior did you expect?**
That the Composite should take up 100% of the available height/width within the context of the div it was given

**If applicable, provide screenshots:**
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/72949357/137539077-6f8d98fc-b38a-4ca2-8630-59dccf98e928.png)

**In what environment did you see the issue?**

- OS & Device: macOS
- Browser Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox
- Version:    "@azure/communication-react": "^1.0.0-beta.6",

**Is there any additional information?**

**Comment by JamesBurnside** [comment]
We have this mentioned in the storybook here: https://azure.github.io/communication-ui-library/?path=/docs/composites-call-basicexample--basic-example#styling

We're not allowed to set these properties by default as we can't be adjusting elements outside of the compsite.
One option would be a flag in the composite itself - `expandToFillScreen` that then did touch those properties?

But very open to suggestions here
