### ISSUE TITLE
Adding Support for Angular

### ISSUE THREAD

**Issue by pablo-meyer** [Azure/communication-ui-library#994]
This is awesome but it seems like everything here is tailored around react. Can/Will this be provided in angular or somehow in pure html/css/javascript?

**Comment by rceraline** [comment]
Hi,

Angular support would be great. In the meantime, I've tried the pure html/css/javascript for call composite and it works fine. 

@alkwa-msft  My question is related to localization. How do we use the localization provider as described [here](https://azure.github.io/communication-ui-library/?path=/story/localization--page) without react?

Thanks,

**Comment by alkwa-msft** [comment]
@PorterNan  can we wrap the localizationProvider around the component we expose through the vanillaJS bundle?

A problem I foresee is that we can't treeshake and this bundle would include string for every locale?

@rceraline if we exposed the structure of local strings we are expecting would you be able to pass in a JSON with the locale strings that we expect to use?

**Comment by rceraline** [comment]
@alkwa-msft the best would be to be able to change the language easily as explained in the react doc but in the meantime yes, we I can pass a JSON with the locale strings it would already be OK for me.

**Comment by rceraline** [comment]
Hi @alkwa-msft, I was able to translate the component but it seems that some translations are missing. I created a new issue to explain: https://github.com/Azure/communication-ui-library/issues/1041

**Comment by anjulgarg** [comment]
Closing this issue as all the concerns have either been resolved or new items have been created to resolve them in the future.
